### ISSUE TITLE
Genetic Material appears inside city and research stores even without the relevant talent.

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#10247]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Merchants from city or research outposts sell all genetic material, even without a medic with the Blackmarket Genes talent.

I'll take this time to say that selling 100% genes for 300-400 marks is extremely cheap. 100% genes requires from ~4-10 refines, and so getting high quality genes is rather laborious, and certainly worth a fair bit more than 400 marks.
In addition, some genes should perhaps be valued differently. Husk, Mudraptor, and Spineling genes have no difference between 10% and 100% genes, so they are less valuable compared to the rest. Some other genes are also comparatively better or worse, but that's neither here nor there. 

UGM (unidentified genetic material) also seems to be priced at a similar amount to the spliceable genes. Since creating 100% genes requires 4-10 UGM, and you don't know which types of UGM you are purchasing, there really should be a price difference.

Of course, I don't know how the talent will work when functioning properly, so this is partially just speculation.

### Reproduction steps

1. start a single-player campaign
2. enable cheats and toggle campaign teleport to travel to a city or research outpost
3. access the general merchant, they will be selling all genetic materials.

Tested on the faction test branch, but I have also experienced it on the 20.3 unstable branch.

Attached are the crew list and talents that I tested with.
![crewlist](https://user-images.githubusercontent.com/37850646/200106386-525092a6-7050-4a09-929b-3afd8558e439.JPG)
![talent3](https://user-images.githubusercontent.com/37850646/200106379-88249d2a-b725-4d2b-ac36-ef9311e2432f.JPG)
![talent2](https://user-images.githubusercontent.com/37850646/200106380-5e017c33-98e6-491d-9078-5a2349a51826.JPG)
![talent1](https://user-images.githubusercontent.com/37850646/200106385-04d878ab-fb6e-4675-91bb-bebe23bb71ab.JPG)
![shopgenes2](https://user-images.githubusercontent.com/37850646/200106376-7231aeee-5d7c-48b0-b862-99ab688e144d.JPG)
![shopgenes](https://user-images.githubusercontent.com/37850646/200106377-1deeafad-2274-43f6-a9b4-a8b25021502a.JPG)

### Bug prevalence

Happens every time I play

### Version

Faction test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5f9b0ab2812155d3fe84a7b3216ca5ce3e2aa80a

**Comment by Wheatley1001** [comment]
Issue still exists in 100.5.0.0
![image](https://user-images.githubusercontent.com/105495756/202919164-cf31e842-d2b4-492d-8d5e-10835708bb5d.png)

**Comment by Rokvach** [comment]
Moved to Team1

**Comment by 3e849f2e5c** [comment]
https://github.com/Regalis11/Barotrauma-development/commit/22947ecff74d354ded1d77de2b2c4aaf444dcf52

**Comment by Regalis11** [comment]
Can't spot any issues in the commit, moving to QA

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.

**Comment by NilanthAnimosus** [comment]
Actually one thing I've noticed - the processed genetic materials are no longer purchasable (while in the above images before, they appeared to be purchasable) - is this intended?

**Comment by JeroonBosch** [comment]
requiresunlock="true" and sold="true" should be removed probably, but I think selling identified genes proved to be too strong

**Comment by JeroonBosch** [comment]
requiresunlock="true" removed here: 
f0ab2e76ce7f8ce64f16f6c9e0c056e9a1772e8c

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
