### ISSUE TITLE
Security Chief Quest ("bigbrother") Not Working Properly

### ISSUE THREAD

**Issue by thedude3253** [Regalis11/Barotrauma#10294]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Playing the single player campaign, I got the event where the security chief asks to speak with you. I selected not interested when talking with him, but the dialog upon entering the room to bug still occurred as if I had heard him out and accepted

### Reproduction steps

1. Start singleplayer campaign with tutorial
2. Play the first few missions
3. talk to the security chief and decline
4. find the room to bug

### Bug prevalence

Just once

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Linux

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3e091b57d44251a0626b614c31ee7f5e387bcb2e

**Comment by Regalis11** [comment]
Seems to not have been fixed, see https://github.com/Regalis11/Barotrauma/issues/10391

**Comment by Regalis11** [comment]
Attempt 2 https://github.com/Regalis11/Barotrauma-development/commit/a719d1cc70061e6c9e6b4789a548bd3c71a14c41

**Comment by Rokvach** [comment]
Still doesn't seem to be fixed, the second time you have the option to say that you'd rather not get involved the event doesn't end there. 

![image](https://user-images.githubusercontent.com/7299826/206140300-ae60584e-e8e2-4f3d-96d3-084a2c5e8692.png)

![image](https://user-images.githubusercontent.com/7299826/206139938-538fe19d-18df-4a42-85ba-13f1f3dc9842.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/592d55a24b5d02a1daf6ffa30e8c0168b091309a

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/c74b9de1ded83ed269a2a470b9a849e9eda8aeaf, no issues found, closing.
