### ISSUE TITLE
Oxygen Low Resistance doesn't slow the not breathing effect from unconscious

### ISSUE THREAD

**Issue by MrBubz03** [Regalis11/Barotrauma#10318]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

As the title says, using Oxygen Low resistances such as "Physical Conditioning" talent from the Security or "The Waiting List" from the assistant don't seem to work properly against the **not breathing** effect from the **unconscious** state.

Also (for modded gameplay) the bleeding ignores any resistances to the bloodloss affliction. Resulting in a quick death the more bleeding we have regardless of our bloodloss resistances. _Probably is intented?_

### Reproduction steps

1. Start any game (campaing or multiplayer)
2. Get any crewmember down
3. See how fast the oxygen low affliction build
4. Revive the downed crewmate and give it resistance to such affliction
5. Get it down again
6. The oxygen low builds at the same rate even with resistance

### Bug prevalence

Happens every time I play

### Version

0.20.3.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
-
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/7b30fe3e2721667a09a82101ef4733a9f24afe38

**Comment by ubertpendragon** [comment]
Still not fixed on current Faction build

The conditional trigger works just fine for "Implacable" (security talent), tried as well with the old talent "Still Kicking"
`        <AbilityConditionAboveVitality invert="true" vitalitypercentage="0"/>`


It applies statuseffects properly, but it can't seem to apply resistances passively

**Comment by MrBubz03** [comment]
> Still not fixed on current Faction build
> 
> The conditional trigger works just fine for "Implacable" (security talent), tried as well with the old talent "Still Kicking" ` <AbilityConditionAboveVitality invert="true" vitalitypercentage="0"/>`
> 
> It applies statuseffects properly, but it can't seem to apply resistances passively. Afflictions build up just as fast as normal

This is about talents that give oxygen low resistance not working against the **not breathing** status effect of unconscious.

If you mean that the Implacable talent is wasted because of the Still Kicking revive, then one of these talents deserve a rework.

**Comment by MrBubz03** [comment]
> Still not fixed on current Faction build
> 
> The conditional trigger works just fine for "Implacable" (security talent), tried as well with the old talent "Still Kicking" ` <AbilityConditionAboveVitality invert="true" vitalitypercentage="0"/>`
> 
> It applies statuseffects properly, but it can't seem to apply resistances passively. Afflictions build up just as fast as normal

What does Implacable and Still Kicking talents has to do with oxygen low resistance?

**Comment by Regalis11** [comment]
@ubertpendragon Neither of those talents apply any affliction resistances, did you accidentally comment on an incorrect ticket?

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/24aad1892591b07abbfdda1680c759abec9ffe9e no issues found, closing.

Notes: The assistant talent "Waiting list" gives this effect (75% resistance to oxygen low), which does work correctly.
