### ISSUE TITLE
[Factions] Autoinjectors dont do anything

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#10389]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Pucs nor autoinjector headsets use up any of the medicine inserted inside, no matter what is put in. Short video to demonstrate.
https://user-images.githubusercontent.com/104232152/201723437-f0cb6257-f473-45b5-9372-4a2d2b36937c.mp4

### Reproduction steps

1.Try equipping an autoinjector
2.Damage until normally triggered
3.Find nothing happened

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/92aa4533f02bafa79b1c199a79dcc51de2acd9d9

**Comment by Rehexr** [comment]
Works in current build, so im closing it

**Comment by Orum** [comment]
This still happens in the current stable.  Put morphine in an auto-injector headset, take blunt force/laceration damage, and it uses the morphine without any healing of the character.

**Comment by Rehexr** [comment]
Reopening because this is kinda an obvious issue

**Comment by Regalis11** [comment]
Oh, looks like we never tested this internally because the ticket was closed before we got to it. :/

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/84efff7192b389fb547f2aac5545c123239e2038

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
