### ISSUE TITLE
Null id card spawn on reputation bot

### ISSUE THREAD

**Issue by CaptainDrowns** [Regalis11/Barotrauma#10417]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

Id card spawned on reputation bots are null and are unable to do anything IE open doors or use restricted containers assigned to their class

### Reproduction steps

1. Recruit a bot requiring reputation
2. Exit game 
3. Have the bot first spawn in the station it was recruited

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/808a3d6abf269599a093b9f984be1bd207adaf81

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Additions commit https://github.com/Regalis11/Barotrauma-development/commit/64bdfc9887d23d7c3c2b9f3d6ead0ab9836983c1

Fix does not seem to be effective based on following the repro steps.

I hired coalition reputation crew from a station in single player, save and quitted then loaded the game to have them spawn on the station. They can use station doors but not my typhon 2's doors, implying they either have none or perhaps got the spawnpoint tags from the station perhaps instead of the submarine.

Medics couldn't access toxin lockers too, nor could security access weapons safe lockers. On top of all the doors.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8fd5d51102394c6daada6ec99e6599cc0245ed93

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/307f89d6fad8cb458206f814d5b108ae830bd564

Fix did not work, appears the ID card is still missing essential tags for the submarine for that job (was unable to open any doors or the secure cabinet)

**Comment by Regalis11** [comment]
3rd time's the charm? https://github.com/Regalis11/Barotrauma-development/commit/1c3da9c02fb97105dca22477187712ee7825982d

> Fixed hired bots with pre-configured items (faction-specific bots) still not getting functional ID cards for the sub. The tags were correct now, but card's SubmarineSpecificID (which makes it only work in a specific sub) was set to the outpost the character 1st spawns in.

**Comment by NilanthAnimosus** [comment]
Tested against WIP-Fixes commit https://github.com/Regalis11/Barotrauma-development/commit/1c3da9c02fb97105dca22477187712ee7825982d, no issues found, closing.
