### ISSUE TITLE
Event line for radio host shows for everyone regardless of location

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10437]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When idly waiting for people to finish outpost activities, the event text for the radio host event showed up on my screen despite me being outside the outpost and nowhere near the event trigger. 

Image below for reference.

![image](https://user-images.githubusercontent.com/105495756/202828623-afcd79ba-f93d-4972-868a-24d0b232f1a3.png)

From my understanding, this is a common issue or reoccurring bug. I unfortunately have nothing new to add to the discussion as to why it triggers, only that it happened in the most recent build.

### Reproduction steps

1. Have someone interact with the questline that discusses the radio host
2. Exist (anywhere)
3. Observe how text dialogue appears 

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e9e8ce42e8f089b1ddd596d64bbb02bd27c7456

**Comment by Wheatley1001** [comment]
Issue persists in 100.13.0.0. I was away from my keyboard when the event popped up on my screen as shown in the image below.
![image](https://user-images.githubusercontent.com/105495756/212445802-ac4acb8d-c71a-4278-bd7f-92d7dca7025d.png)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
