### ISSUE TITLE
[Factions] Mission reputation rewards displaying incorrectly

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#10465]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

At random but regular intervals, mission reputation rewards will be doubled and then halved depending on the menu you look at. The end of round screen shows double rewards whilst the reputation menu in the tab screen shows halved rewards (which are accurate according to the mission description).

![image](https://user-images.githubusercontent.com/105495756/202921601-57e976a3-cefd-4169-ba70-6a02e1f77440.png)
_Figure 1. End of round screen showing double reputation rewards after mission completion._

![image](https://user-images.githubusercontent.com/105495756/202921605-18bcda5a-2b45-4c95-a588-dd6437eecbe5.png)
_Figure 2. Reputation menu immediately after showing the correct reputation values._

What is not pictured here is that the reputation on the campaign map uses the false doubled values. This causes extreme confusion as to what the true reputation value is.

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I unfortunately couldn't find a way to reproduce this. I suspected it might have something to do with the "Affiliation" talent which doubles reputation gains, but couldn't repro the problem after unlocking that talent either.

**Comment by Wheatley1001** [comment]
Credit for the following investigation goes to Hawkins: 
"captain affiliated with clowns should turn this into +10 and -6 right"
![image](https://user-images.githubusercontent.com/105495756/203329169-53aab2a3-1b18-4372-a5f3-496870f8f1c8.png)
![image](https://user-images.githubusercontent.com/105495756/203329196-916041f7-46a8-4211-98b6-a945f40ff701.png)

Further testing showed:

"i used the youngcultists event to test out affiliation 
-5 rep with husk when refusing to get involved
-20 rep when refusing while affiliated with coalition
-20 rep when refusing while affiliated with husk
does it just quadruple rep loss no matter which faction"

From the original instance, I don't know if Hex had the Affiliation talent active at the time. By the end of the session, he did have it picked and went with the Coalition, but from memory I believe this specific instance of the issue occurred two nodes before he chose the talent.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/90474296bb2c2b8c804888e8d964be515f7c7744

**Comment by Wheatley1001** [comment]
Issue still persists as of 100.8.0.0

We started a brand new campaign so there shouldn't be any issues regarding saves from 100.0.0.0. This was a campaign save started in 100.8.0.0. Reproduction seems to be simply hosting a server and finishing a campaign mission. After completion, the reputation rewards are doubled in the end-screen.

![image](https://user-images.githubusercontent.com/105495756/205411358-e37e4a34-369d-400f-98a4-c4ed3fc8c979.png)
![image](https://user-images.githubusercontent.com/105495756/205411364-0d3568f3-24fc-41b9-bc11-fcdc447eec3b.png)

**Comment by Wheatley1001** [comment]
Issue still persists as of 100.13.0.0, seems to occur every time now. Campaign map and tab menu reputation is consistent as far as I can tell, but the recorded end of round rep gain/loss is double what is actually registered. 

Images below to support:

![image](https://user-images.githubusercontent.com/105495756/212445152-1a4c283d-b7ee-4cc4-891b-dde4d47292a0.png)

Independent instance of issue (above)

Grouped images representing a single instance of this issue (below)

![image](https://user-images.githubusercontent.com/105495756/212445226-fdfe4a20-a5be-425e-a0cd-049347b92bc1.png)
![image](https://user-images.githubusercontent.com/105495756/212445234-7f30acc9-53b5-4367-be1c-8efab70c72b6.png)
![image](https://user-images.githubusercontent.com/105495756/212445237-0b245a58-ab96-4090-b725-016a10e85c94.png)
![image](https://user-images.githubusercontent.com/105495756/212445245-3c2eeaa3-4b6b-4ec9-9588-0a897ffb5b8b.png)
![image](https://user-images.githubusercontent.com/105495756/212445250-50c3efa7-e36d-48d8-9d49-6843341a8252.png)


![image](https://user-images.githubusercontent.com/105495756/212445325-fd64b8d5-b150-42cf-9d3d-dce61abf2255.png)
Image showing issue with clown and husk factions


![image](https://user-images.githubusercontent.com/105495756/212445346-ffc5faa4-3c10-46e5-aebe-6c563e3a754b.png)
+1 rep mission being shown as +2

**Comment by JeroonBosch** [comment]
Definitely still an issue:
![image](https://user-images.githubusercontent.com/8641689/213121401-f6dfe674-7088-4b36-946a-d655f8119eb7.png)

**Comment by Regalis11** [comment]
Steps to repro pls? I couldn't get that to happen. Which branch/commit are you on? Single player or multiplayer?

**Comment by JeroonBosch** [comment]
Multiplayer, latest commit on the wip branch. Don't have exact steps, it just happened on the first mission I tried.

**Comment by Wheatley1002** [comment]
Every instance of this issue (from my end) occurred in multiplayer. Server type is P2P hosted over steam, basic direct join. In previous builds it was an occasional issue, but as of the most recent factions branch, it feels like every single mission taken has this issue (I have no statistics to back this claim, so I will not state that it occurs 100% of the time despite it absolutely feeling this way).

**Comment by Regalis11** [comment]
Thanks for the extra info!

I was able to repro this now: the key information was that it happens in multiplayer. I also had to use the simulatedlatency command to get it to occur.

The problem was the rep gains were also applied client-side, and if the client happened to receive the up-to-date reputation values from the server before ending the round and applying the rep gains themselves, they'd essentially get applied twice client-side.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/57ae0320e2029c9a75514290060f2fa83fbc56d0

**Comment by Wheatley1001** [comment]
Reputation gain now seems consistent, but the new issue is that the mission description doesn't match the end reward. The end screen shows you +20 rep and you _do_ get +20 rep, but the written text says +10 (this is with the affiliation talent, so I assume the two are linked). This would be problematic as you don't know how the affiliation talent impacts reputation gain until you complete the mission.

![image](https://user-images.githubusercontent.com/105495756/213842666-4c5a5fcf-d212-4a03-847b-107c93bcc9e3.png)

**Comment by NilanthAnimosus** [comment]
Tested against Feature/WIP commit https://github.com/Regalis11/Barotrauma-development/commit/56fafbb092c7eaf6261be40c637fb9aededd590f

Tested on multiplayer campaign with SteamP2P with a fresh campaign - At first trying simulated latency on the host client and server (300). I had used set reputation for 1 in coalition and 0 all other factions then got the affiliation talent for the captain (As to boost the coalition related reputation gain) and then two level transitions (undock and redock).

In outpost used triggerevent missionevent_escort1coalition (Should reward 1100 marks, 5 coalition -3 separatists) and saw this as the result:
![image](https://user-images.githubusercontent.com/29177976/216263508-37981e62-316f-4267-8549-46bfb4da81ba.png)

As you can see, the host client essentially did not apply any of the reputation gains, in the end mission/loading screen and next loaded outpost. Checking reputation screen it did apply the correct values (+5 * 50% bonus = +8, -3 was the correct decrease for separatists) and the money gained is correct (1320 is 1100 * 1.2) however the mission reward screen does not correctly reflect the bonus marks nor bonus reputation correctly.

![image](https://user-images.githubusercontent.com/29177976/216264248-3f84c90b-3224-43f5-b77d-b21c2b1b969d.png)

**Comment by Regalis11** [comment]
Hopefully fixed for 4 now: https://github.com/Regalis11/Barotrauma-development/commit/c366dcf358a0af67733bb9ca957115c132fe8d3c & https://github.com/Regalis11/Barotrauma-development/commit/b484646c0331b759bff05ab2aa4567ce77be47a9

**Comment by NilanthAnimosus** [comment]
Tested against Fix/wip-fixes-january commit https://github.com/Regalis11/Barotrauma-development/commit/69454ec1e34e4b3119250e4fc71947048670ad61

The syncing issues appear to be fixed now (At least, I couldn't reproduce anymore errors there), though there is some truncation or rounding issues causing the round end screen to not always match (at times being 1 off or so) due to decimal values in reputation gains/amounts:

![image](https://user-images.githubusercontent.com/29177976/216649971-a75c19a0-9745-4b93-bcfb-3da5b75aa212.png)

**Comment by NilanthAnimosus** [comment]
Tested against Fix/wip-fixes-january commit https://github.com/Regalis11/Barotrauma-development/commit/a1f14c233cf50eb6f5b632d68103db2483f6f4ab, no issues found, closing.

Notes: there are cases of very minor rounding visuals left (IE. when having talent multipliers on relation gains) causing invisible fractions of reputation.

One such example is with the captain politician talent "Affiliation" for 50% bonus faction gain, from a relations of 1.0 and the mission rewarding +5 (thus about +7.5) shows as +8, and after mission the reputation will show as (8) (+8) instead of (8.5) (+7.5). Though a very minor visual detail the root problems are fixed (And there is no simple way to fix the above in all cases, some work has been done to round it a little better).
