### ISSUE TITLE
Korean characters display incorrectly when typed

### ISSUE THREAD

**Issue by Grovac** [Regalis11/Barotrauma#10515]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When typed into a text field, Korean characters will not display in real time. Any input only shows after a syllable block is completed or return is pressed prematurely.

### Bug prevalence

Happens every time I play

### Version

0.19.14.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Wheatley1001** [comment]
There's also an issue with Korean characters being considered illegal and preventing players with Korean characters in their name from joining servers. I posted a comment about it in issue #10156. Have you had issues joining servers with Korean characters in your name? Have you seen players with Korean characters in their name struggle to join servers?

**Comment by Grovac** [comment]
Yes I've had that issue as well, I had to change my name when I first started playing (shortly after update v0.18.11.0). I tested it again today, and that issue persists.

**Comment by Grovac** [comment]
Thank you both for the responses!

I'm not very familiar with Chinese, however native Korean characters don't require any "candidate box". I tested typing in v0.20.7.0 today and there are still issues that make typing difficult, including invisible characters, and the interaction these characters have with what I'm assuming to be the candidate box (smaller text box beneath the primary one).

**Comment by Wheatley1001** [comment]
@Grovac I would encourage you to do so since this ticket has been closed and is unlikely to be relooked at as a result. 

In the off chance that Regalis does come back to read these comments, would you (Regalis) be able to address the issue of non-English characters being considered illegal by default? It essentially shadow bans specific languages from the game unless they know about the issue ahead of time, which many people don't

**Comment by itchyOwl** [comment]
So, I guess this should now be fixed, right? Moving to QA.

**Comment by 3e849f2e5c** [comment]
Bringing this comment in from the other issue since these are still an issue https://github.com/FakeFishGames/Barotrauma/issues/9509#issuecomment-1325794651 but there's no mention on why this ticket is still up so it might be a bit confusing

Some additional notes:
I faintly remember looking into this at one point since it also affects Japanese and I think I deducted it was caused by the game not loading CJK fonts if they weren't present causing the first character to fail to load but since CJK writing is now present the fonts load and rest of the characters load correctly, I thought this was a bit of a too complex issue and assumed it wouldn't affect if you were already running the game in Chinese/Korean/Japanese language which most people would

**Comment by itchyOwl** [comment]
Should be fixed in the next unstable (and release). Let us know if it doesn't work.
