### ISSUE TITLE
[Factions] Beaconstation2_research entrance impossible to reach

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10685]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The research beacon station has a tendency to get blocked by terrain.

Since it goes on the ceiling please consider another beacon shape with a bottom entrance, dare I suggest a docking port on the bottom left as seen on [this beacon right here](https://user-images.githubusercontent.com/73229309/206248831-b1a483ff-ef9f-4748-b6d7-ffbb246671f6.png)

![image](https://user-images.githubusercontent.com/73229309/206247707-b6c04408-f8c3-48ca-a105-c4b3fab266a0.png)
![image](https://user-images.githubusercontent.com/73229309/206247736-afdd6139-4955-4594-ad7b-272c0054f302.png)

### Bug prevalence

Happens every now and then

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/72b93bf0feeaf077df664863b5dc3144fc83420e

**Comment by JeroonBosch** [comment]
Not entirely fixed working as intended. As a player you can get semi-stuck here in the airlock that's facing the bottom of the beacon station. There is a pump operated by a water detector, but it doesn't actually pump out water - I had to manually set it to pump out
![image](https://user-images.githubusercontent.com/8641689/212319434-1a27ad46-85b1-465e-88e2-b5523e01f8d7.png)
![image](https://user-images.githubusercontent.com/8641689/212319548-a5e04b95-8b4a-498f-bc84-d60a1749e6aa.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/57cfc9cec80ac3c32e0479ce007ffa1f93e3acaf

**Comment by JeroonBosch** [comment]
Airlock now works as intended - closing
