### ISSUE TITLE
Submarine gun/searchlight/turret light can not be turned off

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#10704]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

tried setting submarine gun light to off

entered test mode, gun light was on

exited test mode, gun light is now on in the lightcomponent's settings.

### Reproduction steps

1. dugong
2. set top left coilgun to off for lightcomponent
3. check by toggling lighting layer
4. enter test mode, check periscope. gun light is on
5. exit test mode, coilgun light is set to on and lightcomponent is as well.

### Bug prevalence

Happens every time I play

### Version

0.20.9.0 (Unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Orum** [comment]
This happens on the current stable as well.  For whatever reason the "Is On" parameter isn't being saved, and thus the gun light is being stuck on.

I ended up working around it by just putting in a component that sends a 0 constantly, and wiring it up to the "Set Light" on the gun.  Annoying, but until there's a fix this seems to be the best workaround.

**Comment by Regalis11** [comment]
It seems this happens because the LightComponent is a child of the Turret component, and inherits the state of the Turret when it's loaded (i.e. because the turret starts in the active state, the light does so too). Need to think about this a bit to figure out a solution that doesn't cause side-effects with other similarly configured items.

**Comment by PanmanS** [comment]
Oh, well gotta vary words next time searching for already existing report lol

**Comment by JeroonBosch** [comment]
Does not seem fixed. Repro steps:
1. Open subeditor, load Dugong, enable Lighting view
2. Untick "Is On" property of light component to be false/off
3. Notice the light is actually off
4. Enter test mode
5. Leave test mode
6. Notice the light is back to being on.
Back to TODO

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/pull/4607/commits/7c791e9fe8b6540465fc7a93a7e50c6319fd4666

**Comment by JeroonBosch** [comment]
Tested:
- Sub editor: disable Light Component, enable Lighting inside sub editor (light is indeed off)
- Test mode, check that the light is still off (correct)
- In Sub editor, ensure the light is still off
- Save the submarine
- Load the submarine, ensure the light is still off
- Ensure turning on the light again works (works as expected)

**Comment by drmahorin** [comment]
Feels like for modded lights bug is still here.
I've looked into .xml and it looks like unmodded item, but unmodded one can save "Is On" state and modded - can't.
