### ISSUE TITLE
"Flak Cannon" cause an error in multiplayer campaign

### ISSUE THREAD

**Issue by LInternationale** [Regalis11/Barotrauma#10732]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When I use "Flak Cannon" to fire to the empty direction rapidly in a multiplayer campaign, an error will happen.

### Reproduction steps

1. Start a multiplayer campaign.
2. Use "Flak Cannon" to fire to the empty direction rapidly.
3. Wait and observe how the game crashes.

### Bug prevalence

Happens every time I play

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error in game console:

Error while reading a message from the server. Entity event data exceeds the size of the buffer (current position: 8072, length: 8088).
Previous entities:
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
NULL
EntitySpawner
Flak Fragment (ID: 6828)
Flak Fragment (ID: 6828)
Flak Fragment (ID: 6825)
Flak Fragment (ID: 6825)
Flak Fragment (ID: 6824)
Flak Fragment (ID: 6824)
Flak Fragment (ID: 6805)
Flak Fragment (ID: 6805)
Flak Fragment (ID: 6788)
Flak Fragment (ID: 6788)
Flak Shell (ID: 6785)
Flak Shell (ID: 6785)

Error in DedicatedServer:

Failed to write an event for the entity "破片 (ID: 6817)" {Object reference not
set to an instance of an object.}
   at Barotrauma.Items.Components.Projectile.ServerEventWrite(IWriteMessage msg,
 Client c, IData extraData) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\It
ems\Components\Projectile.cs:line 64
   at Barotrauma.Item.ServerEventWrite(IWriteMessage msg, Client c, IData extraD
ata) in <DEV>\Barotrauma\BarotraumaServer\ServerSource\Items\Item.cs:line 52
   at Barotrauma.Networking.NetEntityEventManager.Write(IWriteMessage msg, List`
1 eventsToSync, List`1& sentEvents, Client recipient) in <DEV>\Barotrauma\Barotr
aumaShared\SharedSource\Networking\NetEntityEvent\NetEntityEventManager.cs:line
28
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/993fc759d616a62d0e760243beb03a2cb4af0db3

**Comment by LInternationale** [comment]
Thank you for your reply! I've tested it but this error still exists. Should I do something? Or wait the next update?

**Comment by Regalis11** [comment]
The fix is not yet included in the current public release, so unfortunately you'll have to wait until it's out.

**Comment by LInternationale** [comment]
OK, I understand. Thank you very much for your work! I will look forward to the next update!

**Comment by Regalis11** [comment]
We've pushed a hotfix (v0.20.16.1) to this and a couple of the other issues in the Holiday Update.

**Comment by LInternationale** [comment]
I just tested it. This problem no longer exists. Thank you very much!

**Comment by LInternationale** [comment]
I just tested it. This problem no longer exists. Thank you very much!
