### ISSUE TITLE
Camel medical compartments sprite depth issue

### ISSUE THREAD

**Issue by HawkinsThe71st** [Regalis11/Barotrauma#10766]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The two small medical compartments on the Camel have their sprite depth set to the same value as the label causing them to sometimes be rendered behind it like so:
![image](https://user-images.githubusercontent.com/115734437/208308109-b068557a-4c0d-4351-bec2-e581f40f8cf5.png)
The medical compartment:
![image](https://user-images.githubusercontent.com/115734437/208308144-9247bd61-e764-4fb1-a2ef-1297fd792d3a.png)
The label: 
![image](https://user-images.githubusercontent.com/115734437/208308238-ee1b4625-e28c-44ea-986c-87d3cd8a5723.png)

Unrelated, bots seem to continuously crouch up and down in the short space above the air lock and on the other side in the main ballast tank but I don't think it has any negative effects (they don't appear to be stuck in place or anything):

https://user-images.githubusercontent.com/115734437/208308533-9fffb831-478d-4eb3-824c-8be33cca3230.mp4

### Bug prevalence

Happens every now and then

### Version

0.20.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
I don't think the label should be there in the first place, but I'm not sure, so didn't touch it. I'll leave it to you @JeroonBosch .

Fixed the issue with bots crouching in Regalis11/Barotrauma-development@a249b59. It's not related to this ticket in any other way except it happens on the same sub.

**Comment by Regalis11** [comment]
Couldn't spot any issues with the crouching fix, but the sprite depth issue remains unaddressed. Moving back to team 2.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/e424d480b87ebd02e9cc3c4cf815fdb99f1cdffe, no issues found. Closing.
