### ISSUE TITLE
ConnectionPanel tried to read too much data from a segment when trying to join when trying to join an on going round

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#10872]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When i tried to spectate an on going round i got thrown back to the server browser and got the following error:
```cs
Error while reading a message from server. 
Exception thrown while reading segment EntityEventInitial at position 16.
Inner exception: Tried to read too much data from segment.
   at Barotrauma.Networking.SegmentTableReader1.SegmentReadMsg.Check() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 168
   at Barotrauma.Networking.SegmentTableReader1.SegmentReadMsg.ReadUInt16() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 189
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\ConnectionPanel.cs:line 169
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1362
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime, List1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 221
   at Barotrauma.Networking.GameClient.<>c__DisplayClass116_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2127
   at Barotrauma.Networking.SegmentTableReader1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 302

```

### Reproduction steps

No known reproduction steps

### Bug prevalence

Happens every now and then

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Error while reading a message from server. 
Exception thrown while reading segment EntityEventInitial at position 16.
Inner exception: Tried to read too much data from segment.
   at Barotrauma.Networking.SegmentTableReader1.SegmentReadMsg.Check() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 168
   at Barotrauma.Networking.SegmentTableReader1.SegmentReadMsg.ReadUInt16() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 189
   at Barotrauma.Items.Components.ConnectionPanel.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Components\Signal\ConnectionPanel.cs:line 169
   at Barotrauma.Item.ClientEventRead(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Items\Item.cs:line 1362
   at Barotrauma.Networking.ClientEntityEventManager.Read(ServerNetSegment type, IReadMessage msg, Single sendingTime, List1 entities) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\NetEntityEvent\ClientEntityEventManager.cs:line 221
   at Barotrauma.Networking.GameClient.<>c__DisplayClass116_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2127
   at Barotrauma.Networking.SegmentTableReader1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 302
```

**Comment by Regalis11** [comment]
Caused by the same issue as https://github.com/Regalis11/Barotrauma/issues/10719, fixed in https://github.com/Regalis11/Barotrauma-development/commit/48f2b551802792e075e0818b6e068bf4a8c732f2

**Comment by evilfactory** [comment]
Maybe need to reopen this? The issue #10719 doesn't happen anymore, but this issue still happens.

**Comment by NilanthAnimosus** [comment]
Are you sure its the same error with the same "Tried to read too much data from segment." as the reason?

When doing testing I couldn't get this to occur (and I surprisingly still have the image for this when I tested it) with as many connections as I could concievably add with mid round joining and loading saves and such attached in a round which I felt should cause this issue, and it appeared resolved (and should be in the current versions):

![image](https://user-images.githubusercontent.com/29177976/216810033-2025f382-22f2-4386-9f1e-8528e44bcebf.png)

If it is, that would imply something reverted somehow, as this fix should have been fairly universal (that is, everything using segmenting tables that would throw this error should have had the same changes as its shared in all places it occurred)?

**Comment by evilfactory** [comment]
I just checked again, and i was wrong, seems like i looked too fast at the error and for some reason thought it was the tried to read too much data from segment error. Although it still seems odd to me how this error even happened originally, to read too much data from a segment table, don't you have to first write too much data into it? (causing it to throw the error on the side of who is writing instead of the side of who is reading)

**Comment by Wheatley1001** [comment]
Hey everyone, I might have an error log which relates to this issue. Came from 1.0.2.0 I think? Sadly with the removal of the watermark I've been struggling to keep up with the builds specifics  ;^<>^

![image](https://user-images.githubusercontent.com/105495756/221012961-e8c145b4-698d-4041-87a4-9a9cf5c2a393.png)


![image](https://user-images.githubusercontent.com/105495756/221012731-ab381db2-bdac-483c-a076-4903799f8b31.png)

Both errors came from the same issue and instance, so they might be related or they might be unrelated.

**Comment by Krzeszny** [comment]
Is this the same?

```
Error while reading a message from server. 
Exception thrown while reading segment EntityPosition at position 1288. Previous segments: Segment { Identifier = SyncIds, Pointer = 32 }, Segment { Identifier = EntityPosition, Pointer = 185 }, Segment { Identifier = EntityPosition, Pointer = 376 }, Segment { Identifier = EntityPosition, Pointer = 560 }, Segment { Identifier = EntityPosition, Pointer = 736 }, Segment { Identifier = EntityPosition, Pointer = 920 }, Segment { Identifier = EntityPosition, Pointer = 1104 }
Inner exception: Tried to read too much data from segment.
   at Barotrauma.Networking.SegmentTableReader`1.SegmentReadMsg.Check() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 162
   at Barotrauma.Networking.SegmentTableReader`1.SegmentReadMsg.ReadSingle() in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 195
   at Barotrauma.Character.ClientReadPosition(IReadMessage msg, Single sendingTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterNetworking.cs:line 263
   at Barotrauma.Networking.GameClient.<>c__DisplayClass116_0.<ReadIngameUpdate>b__0(ServerNetSegment segment, IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2122
   at Barotrauma.Networking.SegmentTableReader`1.Read(IReadMessage msg, SegmentDataReader segmentDataReader, ExceptionHandler exceptionHandler) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\SegmentTable.cs:line 296
```

**Comment by Regalis11** [comment]
@Krzeszny does not seem to be the same issue
