### ISSUE TITLE
Cannot start Linux dedicated server using LinuxGSM due to incorrect EOL character in `DedicatedServer.exe`

### ISSUE THREAD

**Issue by nickgbasso** [Regalis11/Barotrauma#10905]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

I installed a Barotrauma server using LinuxGSM on a fresh instance of Debian 10. After installing all dependencies and making sure my user had permissions, `./btserver start` would crash without producing any error message, and the logs were empty for the console and server.

Looking into the configuration I found that LinuxGSM's script running the `DedicatedServer.exe` bash script, which in turn runs the `DedicatedServer` binary. When trying to run the binary on it's own it seemed to start, however when running `DedicatedServer.exe` I would get:
```
./DedicatedServer: No such file or directory
```
After doing some research I found that having an incorrect end of line character can cause Linux to be unable to execute a file from a bash script. I deleted `DedicatedServer.exe` and recreated it in Vim, typing the same contents back into and then ran the server and it worked as expected.

I'm unsure if this problem is specific to LinuxGSM but I saw mention of `DedicatedServer.exe` in other issues and figured it would be worth reporting.

### Reproduction steps

1. On a fresh instance of Debian 10, install a Barotrauma server using LinuxGSM.
2. Run `./btserver start`.
3. Navigate to `~/serverfiles`.
4. Delete `DedicatedServer.exe`, and recreate it with the same contents, but linux end of line characters.
5. Navigate back to `~` and run `./btserver start` and it should work.

### Bug prevalence

Happens every time I play

### Version

0.20.16.1

### Which operating system did you encounter this bug on?

Linux

**Comment by mygamingaccount** [comment]
Check https://github.com/GameServerManagers/LinuxGSM/issues/4003 for any updates regarding Barotrauma support in LinuxGSM

**Comment by mygamingaccount** [comment]
I can not find any `Barotrauma.exe` in my distribution, either through steam, or when I compile from source. Where is it from?

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/99254a436b41c6ffa137e72fa5da9b86f2eb3b8f

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by phillipinman** [comment]
I can confirm this issue is still present on Barotrauma Dedicated Server 1.0.7.0 (ReleaseLinux, branch release/1.0, revision e1df60d5cc).

Saving it using nano and de-selecting dos format using Alt-D when saving fixes the issue.

**Comment by mygamingaccount** [comment]
@phillipinman Were the files upgraded or is it a fresh install?

I built from the latest source and the file had correct line termination.
I validated the local files in Steam and the file still had correct line termination characters.
Deleted and reinstalled, still correct.

I can not repeat what you're experiencing.
