### ISSUE TITLE
Empty Canister Shell condition not going down to 0

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#10940]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

After shooting a canister shell, the condition sometimes doesn't go to 0 and it cant be recycled

![image](https://user-images.githubusercontent.com/73229309/212503825-2f45c00c-b6ba-48ab-bf47-bdebc4b184c7.png)

### Bug prevalence

Happens regularly

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/23e2a0ec90cee70122e0e66510560ef785535c47

**Comment by Rokvach** [comment]
I'm still unable to recycle, moving back to Team1

![image](https://user-images.githubusercontent.com/7299826/213128473-512e0e39-c63c-4387-9ceb-33c1b77d1c23.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/2e063bb9f6e94f6691e71506d11fcee097d566d0
