### ISSUE TITLE
Two salvaging an artifact missions had the same artifact 

### ISSUE THREAD

**Issue by Wheatley1001** [Regalis11/Barotrauma#11051]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### Key Information
Game mode: Campaign
Game type: Multiplayer
Campaign save version: Started in 100.13.0.0, issue occurred in version 100.15.0.0
Server type: Steam P2P

### Issue Report
Upon accepting two salvaging an artifact missions, we only had the game tell us to take one artifact. Upon mission complete, we received the following error code (pictured in the images below). We received the appropriate money and reputation gain, however.

![image](https://user-images.githubusercontent.com/105495756/213843012-1aba509c-e871-409d-bbc0-d929d25544fe.png)
_Figure 1. Mission menu showing two salvaging an artifact missions._

![image](https://user-images.githubusercontent.com/105495756/213843014-be1abf47-dd36-4770-b074-88fb013c4f04.png)
_Figure 2. Image showing a single Psychosis artifact on the submarine._

![image](https://user-images.githubusercontent.com/105495756/213843016-573de572-23b9-4e62-8d75-835de64b2bc0.png)
_Figure 3. Error code upon completing the mission._

![image](https://user-images.githubusercontent.com/105495756/213843019-730b03d5-a025-4fda-b9a6-98a445de8154.png)
_Figure 4. Error code upon completing the mission (alternative view)._

![image](https://user-images.githubusercontent.com/105495756/213843022-223ad954-05b4-482c-a114-e9991a199aac.png)
_Figure 5. End result showing missions as completed._

### Bug prevalence

Just once

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/86131ff9e15dc7d0c5ec6825b08d8149ffcd9e15

**Comment by juanjp600** [comment]
Tested, found a scenario where this bug isn't completely fixed yet

**Comment by juanjp600** [comment]
Waiting for misc-fixes-jan27 to get merged into feature/wip

**Comment by Regalis11** [comment]
The fix has been merged to `wip` now

**Comment by juanjp600** [comment]
Tested on `wip`, the fix appears to be working correctly.
