### ISSUE TITLE
Oxygenite can be exploded in your hand with "e" 

### ISSUE THREAD

**Issue by Rehexr** [Regalis11/Barotrauma#11300]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

For some inexplicable reason, you can make oxygenite shards in your hand immediately explode by pressing e, no clue why, but its cetainly a tad funny. 

https://user-images.githubusercontent.com/104232152/220208572-ff4b8264-a435-41e5-8ff6-b38ff43a5e57.mp4

### Reproduction steps

1.Hold an oxygenite Shard
2.Press "e"
3.Poof

### Bug prevalence

Happens every time I play

### Version

Faction/endgame test branch

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fe1601d980abb1312f1b82a97665c9cda8bcc494

**Comment by StruggleDuck** [comment]
I almost wish that this wasn't fixed, because this is fucking hilarious. Better have fun with this before it's gone.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
