### ISSUE TITLE
Herja: offset oxygen tank visuals in the oxygen generator

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#11431]
![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/fc255f14-aee3-4f35-944b-28d7ea9fcdea)

**Comment by ubertpendragon** [comment]
Kastrull as well

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f3d47b226a7b683b654b9373d8b767a80d3ac5cc

**Comment by Rokvach** [comment]
Tested and the issue still seems to be present in both Herja and Kastrull
![image](https://user-images.githubusercontent.com/7299826/230341811-239f4915-0674-4f25-91fb-6bc8aa500687.png)
![image](https://user-images.githubusercontent.com/7299826/230342122-200bc116-4e50-4a1c-aa69-061e0f3967e8.png)

**Comment by Regalis11** [comment]
Looks like the changes done with the "refreshrect" command weren't saved, fixed in https://github.com/Regalis11/Barotrauma-development/commit/aa9941ab9b8568f35b9b58d3c44058a2c0efd638

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
