### ISSUE TITLE
Character's skill level gets clamped when exceeded 100

### ISSUE THREAD

**Issue by BiffW** [Regalis11/Barotrauma#11876]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

This happens after hiring the jestmaster.
He has 3 skills that are level 150.
When he does something related to the skills, the skill level will be decreased to 100.

### Reproduction steps

1. goto sub editor
2. give yourself 200 mechanical skill
3. weld a broken wall
4. your mechanical skill gets decreased to 100

### Bug prevalence

Happens every time I play

### Version

v1.0.9.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/57e6bb4f15b1b56e0a0c5aac834d45c9ee8cc48c

**Comment by EvilBabai** [comment]
> Addressed in https://github.com/Regalis11/Barotrauma-development/commit/57e6bb4f15b1b56e0a0c5aac834d45c9ee8cc48c

The link is 404

Can confirm the problem is still present, but I hope it would be fixed in further updates.

**Comment by Regalis11** [comment]
@EvilBabai that's a link to our private repository, just for our internal use. The fix isn't included in the public version yet, but should be coming in the near future. Sorry for the inconvenience!

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
