### ISSUE TITLE
Bots stucking when moving through the ladders on Camel/Outpost

### ISSUE THREAD

**Issue by Xardion495** [Regalis11/Barotrauma#11984]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Bots stucking when moving through the ladders on Camel/Outpost.
See every time on Camel and Outposts.

![image](https://github.com/Regalis11/Barotrauma/assets/17722887/57297c58-b1cc-4755-b2f1-8806736cfc3f)
![image](https://github.com/Regalis11/Barotrauma/assets/17722887/67f6393e-936b-4bbe-93d4-637d88558f0e)
![image](https://github.com/Regalis11/Barotrauma/assets/17722887/e9ead924-1e48-4d36-87f6-d361c8840dd8)

### Reproduction steps

1. Start singleplayer campaign
2. Wait until some installations will break on Camel
3. Watch how bot makes unsuccessful attempts to climb the ladder to reach a broken item

### Bug prevalence

Happens every time I play

### Version

v1.0.13.1

### Which operating system did you encounter this bug on?

Windows

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@af98752. Bloody can of worms...

**Comment by pavel4win** [comment]
Also bots do not want to repair navigation terminal on camel sub when sub holding position

**Comment by itchyOwl** [comment]
The Camel issues are addressed in https://github.com/Regalis11/Barotrauma-development/pull/4202 (merged) and the outpost issue fixed in https://github.com/Regalis11/Barotrauma-development/pull/4247 (waiting to be tested).

**Comment by DragonFire101** [comment]
In unstable branch on the camel the AI still gets stuck on the ladders though better than on current stable there still having issues with moving around.

**Comment by itchyOwl** [comment]
> In unstable branch on the camel the AI still gets stuck on the ladders though better than on current stable there still having issues with moving around.

Do you have any specific steps on this?

**Comment by Xardion495** [comment]
Will test soon on current campaign version

**Comment by Xardion495** [comment]
Seems the problem is gone. I'll make one more playtest later and close ticket if all will be fine

**Comment by itchyOwl** [comment]
Thanks for reporting. But please don't close the ticket: our QA team will handle that.
