### ISSUE TITLE
Grid is misaligned by 8cm when placing Components in-game compared to the Submarine Editor

### ISSUE THREAD

**Issue by WJohn** [Regalis11/Barotrauma#12257]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

The in-game component placement grid is misaligned by 8cm on the x and y axis. Specifically, players will place items on where the lines intersect in-game, compared to in the middle of the grid squares when doing so in the submarine editor.

This can be frustrating due to pulling items off a wall being impossible to place the way they were, notable water detectors will always hover over the floor.

**Note:** A workaround exists in by shifting the entire submarine in the editor by 8cm diagonally in any direction, and some vanilla submarines like the Orca 1 do seem to have done this (or predate when this issue first arose).

![grid_editor](https://github.com/Regalis11/Barotrauma/assets/5988156/f6494a14-ccb7-4ccf-8c8b-344a88feb073) ![grid_ingame](https://github.com/Regalis11/Barotrauma/assets/5988156/657cf763-edb1-4f6b-ba6c-5a5b6368549a)

Relates to issue #4446 

### Reproduction steps

1. Start a campaign with any submarine
2. Acquire components
3. Place components down next to existing pre-placed ones that came with the submarine
4. Compare the grid alignment of the two components

### Bug prevalence

Happens every time I play

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by mygamingaccount** [comment]
It's kind of stupid, but I changed the grid size to 8x8 and this is no longer an issue for me. Client side fix that you can use.

```diff
diff --git a/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs b/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs
index 57d2d0424..2991747dd 100644
--- a/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs
+++ b/Barotrauma/BarotraumaShared/SharedSource/Map/Submarine.cs
@@ -42,7 +42,7 @@ namespace Barotrauma

         public static bool LockX, LockY;

-        public static readonly Vector2 GridSize = new Vector2(16.0f, 16.0f);
+        public static readonly Vector2 GridSize = new Vector2(8.0f, 8.0f);

         public static readonly Submarine[] MainSubs = new Submarine[2];
         public static Submarine MainSub
```

![image](https://github.com/Regalis11/Barotrauma/assets/68995233/3e3ba64a-1512-432c-85df-fe01800de14e)

![image](https://github.com/Regalis11/Barotrauma/assets/68995233/438ee9d3-f9a3-4474-8f84-9d29a007533a)

**Comment by giists** [comment]
Repro steps confirmed

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fd91e22834bb7191560bf40b5279cf9959c9c3c1

**Comment by giists** [comment]
No more issues, closing.

**Comment by Remodor** [comment]
> No more issues, closing.

@giists @Regalis11, we have the same problem in the Azimuth. No mods. This is not fixed. Can you reopen the issue, or should I create a new one?

![Image](https://github.com/user-attachments/assets/9cc001ea-d908-4a1d-9b23-a445b41460d7)

**Comment by HOMECODERNEO** [comment]
I also encountered this problem on the Orca2 submarine. The screens installed near the control panel are misaligned, and installing other screens in the company will result in the panel being displayed incorrectly. I understand that this is not critical, but I would like the editor grid to be compatible with the game grid. This directly affects my comfort and perception of things.
