### ISSUE TITLE
Disabling ragdoll breaks npcs and sometimes causes strange behaviour when being hit by doors

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#12276]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Disabling ragdoll in server settings (which I don't think I have literally ever seen anyone do deliberately - why does this toggle exist?) has some funny side effects.

Firstly, it breaks some outpost npcs' ai. This doesn't seem to affect crew npcs, so you can still play campaign with it, but it's pretty jarring.

https://github.com/Regalis11/Barotrauma/assets/37850646/f4768754-9cc9-419f-bc0c-68658da9912f

Secondly, when being hit with a door/hatch with ragdoll disabled will very rarely put the player's character into a weird ghost like state where they are constantly ragdolling and unable to interact with items, yet able to move around.

https://github.com/Regalis11/Barotrauma/assets/37850646/01334f79-9c1c-4168-9424-069ac03e2851

(Used a hatch here, but it works on doors too)

This second bug does softlock the character for a time (I don't know if it persists between rounds since I didn't have anyone to test with) so should probably not be a thing. On the upside, it is exceedingly rare to occur; it happens maybe 1 in every 20 times I've closed the door on myself, so it's not likely that it will affect anyone.

### Reproduction steps

1. disable ragolling in server settings
2. go to an outpost and observe the behaviour
3. close a door/hatch on yourself repeatedly until you get the buggy ragdoll state

### Bug prevalence

Just once

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/cb4622b8cef49bad17861d358f43b937e2f79cb8

**Comment by DanielVango** [comment]
I can't follow the above link, but as of yesterday this bug was still happening - glad I found this thread and was able to understand what was happening. I reported the strange behavior that happens if the checkbox ever somehow becomes unchecked here: https://steamcommunity.com/app/602960/discussions/1/3811785047378968290/

Hopefully the fix for this gets deployed soon, but for now just keeping an eye on the checkbox is a workaround

**Comment by giists** [comment]
No issues found, closing.
