### ISSUE TITLE
Pressure flickering when water goes in and out at the same time

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#12429]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

You can see the pressure indicator flicker as water comes in the hull from the breach, and out from the duct

Pressure does not build up, and thus cannot kill you even if you don't have a suit equipped

https://github.com/Regalis11/Barotrauma/assets/73229309/cd118370-4ce5-4bfa-b8d1-1f3572ec239c

Pressure not flickering, but still not dying 

![image](https://github.com/Regalis11/Barotrauma/assets/73229309/7d11593e-dcfe-40a7-be24-92766b35382b)

A single duct counteracts a giant breach
![image](https://github.com/Regalis11/Barotrauma/assets/73229309/2a4883a9-5415-407b-8351-bb83a01f6af3)

### Reproduction steps

Do like the video

### Version

Unstable (v1.1.3.0)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f87cd4d102c71a27400395b31dca8f6341de210d

**Comment by AdamH-Daedalic** [comment]
Tested on feature/misc-balance-tweaks

I'm still seeing this issue when there is a hull breach in the command room of the Typhon 2. The player receives this constant flickering pressure warning when in the lower half of this room but does not die from the pressure, however when moving to the top of the room above the walkway, the warning becomes persistent. Tested this in the sub editor and singleplayer with the same outcome every time. Sending back for further investigation.

https://github.com/Regalis11/Barotrauma/assets/135589009/e81cf739-7322-45c4-9c7f-c9f7726b3df3

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/8cd447ec732f55afdc7139147c8bbe030d9309df

**Comment by AdamH-Daedalic** [comment]
Tested on feature/misc-balance-tweaks with the new change.

Pressure behaves normally now, with the indicator displaying consistently and without flickering, the pressure builds as expected and will kill the player if they are not wearing a diving suit.

Closing
