### ISSUE TITLE
[Error]Failed to find a target item for the mission "gotoend2"

### ISSUE THREAD

**Issue by beiming2017** [Regalis11/Barotrauma#12575]
In the second run, no red target is avaliable at the end mission.
![1](https://github.com/Regalis11/Barotrauma/assets/53556524/5078d253-4460-42b6-9bf4-b86740bf8496)
![2](https://github.com/Regalis11/Barotrauma/assets/53556524/4287aaa9-ccad-4f7a-ad84-bfb078add6b3)

**Comment by Regalis11** [comment]
Thank you for the report!

Would it be possible to send us the save file this happened in? Note that you need to .zip it first to send it here, because github doesn't support attaching files with the .save file extension.

Were you using any mods when this happened?

Thanks and sorry for the inconvenience!

**Comment by beiming2017** [comment]
> Thanks.
No mods have been used.
It was in version v1.0.21.0.

[current.zip](https://github.com/Regalis11/Barotrauma/files/12459869/current.zip)

**Comment by Regalis11** [comment]
Thank you! It seems the issue here was that the logbook no longer spawned because it had been taken from the level on the previous campaign playthrough. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/c05fdf351451fe7c4cd44aca4dbdbef77b7d0464 (commit in our private repository).

I also edited the save you provided so the logbook doesn't get removed from the level, hopefully you can continue the campaign with this save: 
[current.zip](https://github.com/Regalis11/Barotrauma/files/12461769/current.zip)

**Comment by Rokvach** [comment]
I still received errors, the anomaly also teleported me directly to the empty Jove level rather than the second end level. 

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/75e0d8a2-1b4f-4a09-a0f2-dd24181bc620)

Not sure if this matters but in the second end level under the entrance there's two alien chests with a logbook, I looted both of them and I still have one of them after the transition

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/1ab6ba82-39c5-499c-9210-751223343d98)

**Comment by Rokvach** [comment]
The logbook from the second end level doesn't seem to respawn, I was able to complete the ending a second time by looting another logbook instead. 

The X chest has the logbook to complete the mission, but in this case I looted the logbook from the chest at top and that completed the mission while the X chest didn't have any logbook. 
![image](https://github.com/Regalis11/Barotrauma/assets/7299826/5642647d-ec30-4d2d-a602-58cfe37a3ffa)

**Comment by Rokvach** [comment]
Tested, working correctly. Can be removed and closed.
