### ISSUE TITLE
LevelGenerationParams.ForceBeaconStation doesn't support ContentPath

### ISSUE THREAD

**Issue by zhu-rengong** [Regalis11/Barotrauma#12653]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

I found the content of Vanilla has used ForceBeaconStation here: Map\Biomes\EndBiome\EndBiome.xml
```xml
<LevelGenerationParameters>
  <EndLocationBasic
    ...
    WallEdgeExpandOutwardsAmount="128"
    WallEdgeExpandInwardsAmount="128"
    ForceBeaconStation="Content/Map/BeaconStations/BeaconStation2_AlienResearch.sub">
    <WaterParticles
      texture="Content/Map/Biomes/EndBiome/BackgroundParticles.png" />
    ...
  </EndLocationBasic>
  ...
</LevelGenerationParameters>
```
But this path cannot be extended by %ModDir%, for example:
`forcebeaconstation="%ModDir%/PEL/Map/BeaconStations/PEL_BeaconStation_Dummy.sub"`

### Reproduction steps

1. Download and enable the mod: [Pure Empty Level.zip](https://github.com/Regalis11/Barotrauma/files/12567728/Pure.Empty.Level.zip) or https://steamcommunity.com/sharedfiles/filedetails/?id=3033618197
2. Open Level Editor
3. Select pureemptylevel from the LevelGenerationParams list in the upper left corner
4. Click “Generate”
5. You might get this error:
![image](https://github.com/Regalis11/Barotrauma/assets/73634685/764fae1d-bd9b-463d-9c58-a6b5de4d188a)

### Bug prevalence

Happens every now and then

### Single player or multiplayer?

Happens in both single player and multiplayer

### Version

v1.0.21.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/529924e1a21ea2109da48811d186fb259aa4bf9a

**Comment by Jasontti** [comment]
Tested in https://github.com/Regalis11/Barotrauma-development/commit/583af8944170dd17273c1f825662c724110a1459

Modified the localmod provided so that beaconstation is more visible.
Beacon loaded in succesfully.

No issues found.

Closing ticket

**Comment by HomelessMage** [comment]
Hi!
Making the same steps, provided by @zhu-rengong, I still get an error in `corepackage` failing to find the `forcebeaconstation`.
Please confirm whether the contentpackage logic applies for corepackage as well.
