### ISSUE TITLE
The "insurgency" achievement is bugged with the new update and can not be unlocked 

### ISSUE THREAD

**Issue by Habhelio** [Regalis11/Barotrauma#13053]
- [x]  I have searched the issue tracker to check if the issue has already been reported.
- [ ]  My issue happened while using mods.

What happened?
If a traitor task is completed, the corresponding achievement "insurgency"(Successfully complete a traitor objective.) isnt unlocked. This has been tested with all game modes in multiplayer and nothing triggers its unlock despite completion of the traitor task
![20231027214319_1](https://github.com/Regalis11/Barotrauma/assets/151304912/8d448454-46ab-488d-9af0-f4109ae4f6ff)

Reproduction
1.  Play Multiplayer, set traitor chance to 100%
2.  Get traitor
3.  Finish the Traitor task
4.  Complete the Round

Cannot get the achievement "insurgency"

Bug prevalence
Happens every time

Single player or multiplayer?
Multiplayer

Version
v1.1.19.3

Which operating system did you encounter this bug on?
Windows

Relevant error messages and crash reports
None

**Comment by Regalis11** [comment]
Thank you for the report! Fixed in https://github.com/Regalis11/Barotrauma-development/commit/77c800b5945a61a6a14dfd86e1bddf42127cf8ca

**Comment by Rokvach** [comment]
Tested, I successfully unlocked the achievement, working correctly. Closing.

![image](https://github.com/Regalis11/Barotrauma/assets/7299826/433c72aa-0107-4ed6-b0a5-789e6caa6e83)

**Comment by MrRaymanViy** [comment]
I checked and the achievement still doesn't work.
![20231121135641_1](https://github.com/Regalis11/Barotrauma/assets/151395707/2fe54e54-640a-4c8d-a221-493b9c383c90)

**Comment by Regalis11** [comment]
The fix is not yet included in the public version of the game, but will hopefully be included in the next patch/update. Sorry for the inconvenience!

**Comment by MrRaymanViy** [comment]
Understood. Thank you very much for the clarification.
