### ISSUE TITLE
[File Selection] [Crash] File selection crashes randomly, seems to happen after any initial file selection

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1506]
Game seems to crash if you select "Add File" after you've "Remove"d any file from the to-be-uploaded list. In the workshop file upload menu, I mean.
Technically you can work around this by just removing all the necessary files after you've added everything you need. But it's still a crash.
discord excerpt:
![2019-05-30-113649_638x90_scrot](https://user-images.githubusercontent.com/47284081/58648442-5193e980-82cf-11e9-9b48-721750cf5ded.png)

**Comment by Regalis11** [comment]
Unfortunately I wasn't able to reproduce this. Which version did it happen in, and do you by any chance still have a crash report?

**Comment by hubismal** [comment]
Game doesn't leave behind crashlogs for reasons unknown. spooky.
Here's the exception, and a single message before it that might be related to the dialogue.
`Gtk not found (missing LD_LIBRARY_PATH to libgtk-x11-2.0.so.0?), using built-in colorscheme

Unhandled Exception:
System.InvalidOperationException: Cannot call Invoke or BeginInvoke on a control until the window handle is created
  at System.Windows.Forms.Control.FindControlToInvokeOn () [0x0001f] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at System.Windows.Forms.Control.Invoke (System.Delegate method, System.Object[] args) [0x00000] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control.Invoke(System.Delegate,object[])
  at System.Windows.Forms.MWFFileView+ThumbnailCreator.MakeThumbnails () [0x00072] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <7768781867c04892b60eb12ebb814c26>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <7768781867c04892b60eb12ebb814c26>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <7768781867c04892b60eb12ebb814c26>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <7768781867c04892b60eb12ebb814c26>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <7768781867c04892b60eb12ebb814c26>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Cannot call Invoke or BeginInvoke on a control until the window handle is created
  at System.Windows.Forms.Control.FindControlToInvokeOn () [0x0001f] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at System.Windows.Forms.Control.Invoke (System.Delegate method, System.Object[] args) [0x00000] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.Control.Invoke(System.Delegate,object[])
  at System.Windows.Forms.MWFFileView+ThumbnailCreator.MakeThumbnails () [0x00072] in <8aef12e05d8341c2ba53ae50a7bb2ab8>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <7768781867c04892b60eb12ebb814c26>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <7768781867c04892b60eb12ebb814c26>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <7768781867c04892b60eb12ebb814c26>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <7768781867c04892b60eb12ebb814c26>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <7768781867c04892b60eb12ebb814c26>:0 
AL lib: (EE) alc_cleanup: 1 device not closed
AL lib: (EE) alc_cleanup: 1 device not closed
`

**Comment by Regalis11** [comment]
Should be fixed in b294aee

**Comment by hubismal** [comment]
This is still an issue. One thing I recently noticed is that all the files I upload are listed as red and say "File not found". Maybe this is a permission error? I'm looking to see if I can fix the red "file not found" error first.

**Comment by Rokvach** [comment]
This seems to be working correctly now, as there hasn't been any new reports of it causing issues. Closing this.
