### ISSUE TITLE
Fabricator window opens weird

### ISSUE THREAD

**Issue by MagnumIndustries** [Regalis11/Barotrauma#1683]
- [ ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When opening the Fabricator window, the large steel cabinet window opens on top of it, and when opening the large steel cabinet window, the fabricator window opens on top of that

**Steps To Reproduce**
1. start new game with humpback sub
2. go to fabricator and/or large steel cabinet
3. access UI

**Version**
0.9.0.6
Windows

**Additional information**
please see attached video for clarification:
https://youtu.be/zCsUPceY1FQ

**Comment by hubismal** [comment]
This is because someone has linked the interfaces of the two so that you see both UIs when opening it. I think it's disabled in the next update iirc.

**Comment by MagnumIndustries** [comment]
> This is because someone has linked the interfaces of the two so that you see both UIs when opening it. I think it's disabled in the next update iirc.

Do you know when the next update is?

**Comment by CatchFire1101** [comment]
In the interim you can easily fix this and run the sub.  

In sub editor, load the humpback.  Make sure links checkbox is selected on the left hand side; you will see a purple line from the cabinet to the fabricator.  Click the fabricator, hold space, click the locker.  The purple linking line will disappear.  Save as a new sub (i.e. Humback MkII).

BTW devs I really like this idea, but I think the algorithm that places the pop up interfaces needs to be updated to not allow them to overlay (i.e. open side by side, not on top of one another).

**Comment by Rokvach** [comment]
Tested, this issue has been fixed in 3fd1b80, closing.

**Comment by llamerr** [comment]
I'm still seeing this problem. Why not make windows movable? This will solve this and every other related problem
![20220523175031_1](https://user-images.githubusercontent.com/1281970/169846693-9f131acd-5d1f-4b56-b51e-a6d4d80dfaac.jpg)
