### ISSUE TITLE
[Issue] [Network] [0.9.5.1] "Repair" noise only plays locally, peers hear wiring buzz

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#1885]
What the title sounds like. When you are repairing something, other players will hear the buzzing rewire noises instead of the repair noises that you hear. it would be much more helpful if the sounds were heard correctly.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b587f2721026bd40d71a12dae6eec4f0a67ba803 (private repo)

**Comment by Rokvach** [comment]
This should be working correctly now as the issue is gone with bots. Moving to Done.

**Comment by Regalis11** [comment]
We still have an open ticket about this in the private repo (#1149) and according to @ekqvist there are still some issues with this, so this should not be moved to done yet.

**Comment by Rokvach** [comment]
Tested, working correctly. Moving to Done.
