### ISSUE TITLE
When reconnecting from a excessive desync kick, unable to hear existing player mic chat. Also now can't see any chat messages!

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2076]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When reconnecting to a server with high killdisconnecttime after a excessive desync, mic chat from and to all existing players cannot be heard. You can hear new players that spawn in though. This persists even through the lobby until the person that desync rejoins the game in the lobby when the round is over. 

**Steps To Reproduce**
Increase server killdisconnecttime
Play on server with someone with mic chat
Get a excessive desync kick
Rejoin the game before your character dies
Try mic chatting in game

**Version**
0.9.703

**Comment by Kaillera** [comment]
Happens in 0.9.703, but also seemed to have made it so that the person reconnecting cannot see text chat. They can type in it, but not see it themselves.

**Comment by NilanthAnimosus** [comment]
I joined kaillera's server on 0.9.703.0 unstable and within the first 3-5 seconds (More or less the split second my loading green went away) I was immediately greeted with this:

![image](https://user-images.githubusercontent.com/29177976/73782272-b3bfbb00-4789-11ea-94bd-d0191efee3ed.png)

After that I was in the lobby a little later without rejoining, as the server had automatically reconnected me. I then tried to send messages noticing I couldn't. Kaillera could see these messages.

It also turns out Kaillera was using his mic, to which I could not hear as I neither received my own/others messages or kaillera's mic output.

Demonstration of my trying to chat (I always type r; and I use the tab key for local chat and radio anyways):

https://i.gyazo.com/2372cadd9e77a79c10797ab1a5618b51.mp4

This was caused by reconnecting from excessive desync (Too old of a message), maybe this will help in reproduction.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/5eb9abeab6f40b2f530694a3ea3341a291502f8b

**Comment by Kaillera** [comment]
still happening in released 0.9.7

**Comment by Rokvach** [comment]
No reported cases of this happening in the latest build even tho the excessive desync issue is still around

**Comment by Rokvach** [comment]
There was a similar ticket about this which has already been closed, so I think I'm going to close this one as well as the issue hasn't occurred since.
