### ISSUE TITLE
Weapon Holder Layering Issue

### ISSUE THREAD

**Issue by mrjpjr** [Regalis11/Barotrauma#2326]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When on a ladder your character appears behind the horizontal bar of a weapon holder.

**Steps To Reproduce**
Place a weapon holder next to a ladder and climb up or down the ladder, passing in front of the weapon holder.

**Version**
9.7.0
Windows 10

**Additional information**
The issue only happens when you are on a ladder. When walking/running, the layering is as it should be.
![ladder_weapon holder layering](https://user-images.githubusercontent.com/58775950/74664369-f44d0a80-5173-11ea-8d0b-1267aae119ce.jpg)

**Comment by Regalis11** [comment]
Fixed in 4f46209

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by mrjpjr** [comment]
This issue is back.

**Version**
Unstable 0.1003.0.0 revision 7b3c34c2a
Windows 10, 64 bit

**Comment by mrjpjr** [comment]
Guess who's back.....back again....

**Version**
Unstable 0.10.0.0, branch dev, revision 954a95c221
Windows 10 64-bit

**Comment by mrjpjr** [comment]
**Description**
When on a ladder your character appears behind the horizontal bar of a weapon holder.

**Steps To Reproduce**
Place a weapon holder next to a ladder and climb up or down the ladder, passing in front of the weapon holder.

**Version**
Unstable 0.10.502.0, revision 8e288660bf

**Additional information**
It seems my last comments were taken as a joke/was not clear. I apologize for that.
I know this is low priority, but it has been around since June (see the dates of my last 2 comments).
