### ISSUE TITLE
Crashes on launch.

### ISSUE THREAD

**Issue by PelmeshkiDD** [Regalis11/Barotrauma#2383]
Barotrauma Client crash report (generated on 01.03.2020 23:15:54)

Barotrauma seems to have crashed. Sorry for the inconvenience! 

82D5F98C9FFDE58E64CF140A88952446

Game version 0.9.6.0
Graphics mode: 1280x1024 (BorderlessWindowed)
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: None
SteamManager initialized

System info:
    Operating system: Microsoft Windows NT 10.0.18362.0 64 bit
    GPU name: Intel(R) HD Graphics
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,777778}
    GPU status: Normal

Exception: Steam UGC AllRequest Query Handle invalid!
Target site: Void RunInternal()
Stack trace: 
   в Facepunch.Steamworks.Workshop.Query.RunInternal()
   в Barotrauma.Steam.SteamManager.AutoUpdateWorkshopItems()
   в Barotrauma.GameMain.<>c.<Load>b__91_0()
   в Barotrauma.CrossThread.ProcessTasks()
   в Barotrauma.GameMain.Update(GameTime gameTime)
   в Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   в Microsoft.Xna.Framework.Game.Tick()
   в Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   в Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   в Barotrauma.Program.Main(String[] args)

Last debug messages:
[01.03.2020 23:15:35] Logged in as Oberaufseher "SГјd" (SteamID **i dont want for it to be seen**)

**Comment by Regalis11** [comment]
Based on the crash report, it seems this is somehow caused by the game trying to autoupdate some workshop item (or checking if there are items that need to be updated).

This should be fixed in the next update, but for now you might be able to work around the problem by disabling autoupdates. You can do this by opening a file called config_player.xml inside the game folder in notepad, and changing the line `autoupdateworkshopitems="true"` to `autoupdateworkshopitems="false"`. Sorry for the inconvenience!

**Comment by PelmeshkiDD** [comment]
> Based on the crash report, it seems this is somehow caused by the game trying to autoupdate some workshop item (or checking if there are items that need to be updated).
> 
> This should be fixed in the next update, but for now you might be able to work around the problem by disabling autoupdates. You can do this by opening a file called config_player.xml inside the game folder in notepad, and changing the line `autoupdateworkshopitems="true"` to `autoupdateworkshopitems="false"`. Sorry for the inconvenience!

I dont know why,
![image](https://user-images.githubusercontent.com/51423792/75672850-491b7580-5c8a-11ea-9214-19616adab648.png)
But when i edited it, the problem still remains the same as It was, just the same crash report,
I guess it's unfixable At the moment?

**Comment by PelmeshkiDD** [comment]
Also, when i was trying to edit other stuff in config.xml like graphics settings nothing changed, i guess everything I edit doesnt make a change.
