### ISSUE TITLE
Kastrull drone creates an AI/bot blackhole

### ISSUE THREAD

**Issue by Erars** [Regalis11/Barotrauma#2452]
- [x] I have searched the issue tracker to check if the issue has already been reported.
**Description**
The AI/Bots does not know what to do with the Kastrull drone. 

**Steps To Reproduce**
The bots easily get trapped in the Kastrull drone, and AI commands such as follow me, repair ETC does not work once the bots are trapped in the Kastrull drone.

**Version**
v0.9.7.1

**Additional information**
Playing Kastrull with bots is impossible because the bots easily fall into the Kastrull drone, and worst of all, once the bots fall into the Kastrull drone, they aren't able to follow command orders. 
![602960_20200317231050_1](https://user-images.githubusercontent.com/62313026/76910024-ca872080-68a4-11ea-98c8-b8308e79e601.png)

**Comment by itchyOwl** [comment]
I just adjusted the waypoints. Should be fixed in Regalis11/Barotrauma-development@99dc1d2. Requires testing.

**Comment by Rokvach** [comment]
AI can still get stuck in there but its a lot less common now, for example if you have ordered 5 bots to follow you and you walk inside the drone 1-2 will be stuck there once you walk out of the drone.

They are getting stuck at these specific positions:
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9b99ef70-b12b-4c50-9388-2ed65cc883e1)

Video:
https://streamable.com/6e2c6b

Couple ways to repro:
Example 1:
1. Take a EMP grenade from the armory
2. Throw it inside the drone
3. Wait for bot to go repair the devices
4. Notice that the bot is stuck

Example 2:
1. Order a lot of bots to follow you
2. Walk inside the drone
3. Walk all the way to the right in the drone
4. Walk out of the drone
5. Notice that some of the bots are stuck

I also noticed that there's a area between the drone and the sub where the bots will report that they need a diving suit, even tho there isn't any water there. So they will run off to fetch diving gear.

**Comment by Regalis11** [comment]
Potentially fixed in https://github.com/Regalis11/Barotrauma-development/commit/6277af4b6cfc624c5ed354e9437467d0cf1ba41b (commited in bugfixes and merged to dev as well). The waypoints at the hatches would not get linked to the hulls created between the drone and the sub, causing the bots to think they need a diving suit to get through the hatch.

**Comment by Rokvach** [comment]
This is still a issue, tested with the example 2 method, but it did feel a bit different, now the bots did stay on follow instead of dropping the order entirely when I left the drone. But they can't leave the drone and will keep spamming "Can't get there" if I stand above the drone. @Regalis11

**Comment by Kaillera** [comment]
The main issue is the existence of waypoint 1653. The bottom left docking port on the kastrul also need reworking

**Comment by itchyOwl** [comment]
At least this seems to be wrong:

![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/94a2e7dd-a03f-4323-a489-551807621964)

**Comment by itchyOwl** [comment]
Tested it quickly with only one bot and fixing that waypoint seems to have helped. So let's re-evalue it again: is there still something wrong?

**Comment by Rokvach** [comment]
Now they are getting stuck in here, when they go through the hulls between the drone and the sub they report that they need a diving suit which seems to stop them from following, so it might a issue on the hull configuration.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/9fa47693-cc79-4de7-8d41-abc4d004412c)

**Comment by itchyOwl** [comment]
It's probably because some of the waypoints are not linked to the hull -> the bots think that they need the diving gear to go there. Need to look into it.

**Comment by itchyOwl** [comment]
Should be fixed in Regalis11/Barotrauma-development@354d2be

**Comment by Rokvach** [comment]
No issues, closing.
