### ISSUE TITLE
[Issue] [Bug] [Modding] SpeechImpediment property set does not work

### ISSUE THREAD

**Issue by hubismal** [Regalis11/Barotrauma#2462]
~~Unable to set speechimpedement through statuseffect despite itchyowl's suggestion. A simple way of testing this is to just modify the clownmask's hideface statuseffect to also set speechimpediment to 100:~~
```
<StatusEffect tags="clown" type="OnWearing" target="Character" HideFace="true" duration="0.1" stackable="false" speechimpediment="100.0"/>
```
Nevermind, chad husk has essentially confirmed you can't just change public character properties with xml. Consider this a shameful feature request I guess.

EDIT:
But this part of Character.cs (responsible for determining whether speechimpedimentset is true) even mentions editing speechimpediment with a statuseffect? there doesn't seem to be any reason why editing speechimpediment shouldn't work. i'm keeping this as a bug.
```
            if (!speechImpedimentSet)
            {
                //if no statuseffect or anything else has set a speech impediment, allow speaking normally
                speechImpediment = 0.0f;
            }
            speechImpedimentSet = false;
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/16305d0d94f436f1deb659b42e78aa9ea48ad60c

**Comment by hubismal** [comment]
It works! The only issue is really that "unsent" messages still appear as sent to the player and aren't blue (like death messages) the way it is with husk. Interestingly enough, the text cursor is blue but the text isn't.

**Comment by hubismal** [comment]
This is still an issue as of 0.9.901 where setting it to 90 or something completely mutes a person instead of properly impeding their range.

**Comment by Regalis11** [comment]
Are you sure you're setting it to 90, not incrementing it by 90 per second? The effect in your example code for example increments it by 100 per sec.

**Comment by hubismal** [comment]
really? how would i simply set instead of increment?

**Comment by Regalis11** [comment]
By default, the status effects add to the property (or subtract if the value is negative). To set the value instead, you need to add `setvalue="true"` to the status effect.

**Comment by Rokvach** [comment]
No issues, closing
