### ISSUE TITLE
Plasma Cutter/Welding Tool beams are blocked by destroyed doors and organs

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2766]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When fighting a Thalamus Wreck, I decided to be cheap and used Plasma Cutter/Welding Tool to fight the cells inside, The problem is when I was trying to cut/weld cells that are chasing me, the beams keeps hitting dead organ and doors, preventing me from dealing any damage to cells as I am backing away through a long hallway of organs and doors.

This also makes it impossible to cut down certain doors when there are organ hitboxes that extend beyond the door (Thalamus Brain in Dugong Airlock Access Shaft is notorius for instance)

**Version**
0.9.9.1

**Comment by Kaillera** [comment]
Alien Pistol seems to also be affected.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/bf2821068bdf17302bf575dfbf63a81b0a526b74

**Comment by Rokvach** [comment]
I am still unable to plasma cut through broken doors. Only when the plasma cutters beam is on the other side of the broken door it does damage to the wall. @Regalis11 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/77a847d2-c59f-440e-be99-8c6d86db47e4)

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c05369c5-173d-4349-98a1-72bcb1e85972)

**Comment by Regalis11** [comment]
Related: https://github.com/Regalis11/Barotrauma/issues/2813 (the fire extinguisher is implemented as a repair tool)

**Comment by Kaillera** [comment]
[0.9.10.0] Still unable to cut doors when there's a dead organ infront of it.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1abb06dc0503b501f975fc43a184d2d951960f1e

**Comment by Rokvach** [comment]
Tested on Dev, wasn't able to use a plasma cutter through broken doors to repair walls nor extinguish fires through broken doors. Moving back to To do.

**Comment by Regalis11** [comment]
Third time's a charm? https://github.com/Regalis11/Barotrauma-development/commit/2b552979b2c8c23d1e60660487631ec534f24b82

**Comment by Rokvach** [comment]
Wasn't able to reproduce the issue anymore, working correctly. Closing.
