### ISSUE TITLE
Fire Extinguisher doesnt "flow" through a cracked-open door

### ISSUE THREAD

**Issue by Melolatius** [Regalis11/Barotrauma#2813]
- [ x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When I tested the Flamer a bit, I noticed that the extinguishers "CO² Beam" doesnt go through a door which a Mudraptor has broken. But on a normal opened door, it works fine

**Steps To Reproduce**
-Break a door (spawn mudraptor cursor, control mudraptor, destroy door, kill mudraptor (teleport him outside of the sub)
-Place a fire (Either using the Flamer or "fire" as a console command)
-Try to extinguish the fire using a extinguisher through the door
**Version**
Windows 10
![grafik](https://user-images.githubusercontent.com/63376072/81799968-65515380-9512-11ea-9b4b-9088b52247f5.png)

**Additional information**
https://youtu.be/RI_CDshkkwQ
https://youtu.be/nn0QD6Gu8OA
PS: I dont know why the recording is having low FPS, but you can still see the problem

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1abb06dc0503b501f975fc43a184d2d951960f1e

**Comment by Rokvach** [comment]
This looks to be an issue still, I already moved another ticket related to this back to the to do

https://github.com/Regalis11/Barotrauma/issues/2766

**Comment by Rokvach** [comment]
Wasn't able to reproduce the issue anymore, working correctly. Closing.
