### ISSUE TITLE
Could not start voice capture; suitable capture device not found. (40964)

### ISSUE THREAD

**Issue by Araxan** [Regalis11/Barotrauma#2900]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I'm am unable to use voice chat in game.

**Steps To Reproduce**
In settings on voice chat tab, defaultly voice chat is disabled; Whenever I choose diferently in this setting (either Push-to-talk or Voice activity) popup window appears stating:
ERROR
Could not start voice capture; suitable capture device not found. (40964)

**Version**
Currently running Barotrauma v0.9.9.1 (ReleaseWindows, branch release, revision 1968ab79f)
OS: Windows 10 Pro N, version 1909, build 18363.836

**Additional information**
As a audio device my headset is choosed (Genius GX GAMING HS-G680) named in game as Mikrofon (3 - USB Audio Device)
No problem with microphone in any other game/application

**Comment by Araxan** [comment]
error still present in Barotrauma v0.9.10.0 (ReleaseWindows, branch release, revision 2876b0a66)
![40964](https://user-images.githubusercontent.com/66110379/83841291-d8f51380-a700-11ea-97a5-458420831141.PNG)

**Comment by Regalis11** [comment]
@juanjp600 I'm assuming https://github.com/Regalis11/Barotrauma-development/tree/feature/openal-soft-diagnostics is related to this? Should this ticket be moved to "in progress"?

**Comment by juanjp600** [comment]
Moving to QA Todo, I'm expecting more thorough error reports as the most I've done has been add some logging

**Comment by Araxan** [comment]
Is there supposed to be some log file generated? In game error pop-up window is still the same.

**Comment by juanjp600** [comment]
Additional logging is not live yet, it should come in the next update in the form of WASAPI-related messages in the console.

**Comment by Araxan** [comment]
Ok so update is there and below you can see output of debug console..

![image](https://user-images.githubusercontent.com/66110379/88936750-87da4980-d283-11ea-8450-61c178521167.png)

**Comment by Araxan** [comment]
After update, error is persistent, but message has changed a little:

![Barotrauma (mic error) more detail update](https://user-images.githubusercontent.com/66110379/93896662-78123b00-fcf1-11ea-8a27-151ab0da42d7.PNG)

**Comment by Rokvach** [comment]
Moving back to backlog

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0ed8cdf9ce81f5e09119815343d19446107b8b2f? @juanjp600 should this be moved to QA?

**Comment by juanjp600** [comment]
Not gonna get my hopes up too much on this one, moving to QA Backlog.

**Comment by Araxan** [comment]
With version v0.11.0.9 error still the same with same mesage as posted before.

**Comment by Regalis11** [comment]
The fix above didn't make it to v0.11.0.9 unfortunately

**Comment by Araxan** [comment]
Hello can confirm that cave update fixed microphone issue for me.

**Comment by Rokvach** [comment]
Thanks for the confirmation, closing the ticket.

**Comment by aktoja** [comment]
I faced the same problem
