### ISSUE TITLE
0.1001.0.0 Research outpost module has no power wired to it

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#2956]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Title
![image](https://user-images.githubusercontent.com/59519434/83656581-04241980-a5c0-11ea-8022-9b67e1b9a0f2.png)
**Version**
0.1001.0.0 Unstable
**Additional information**
Junctions are wired to each other and they are wired to lamps, but they are isolated from the rest of the outpost.

**Comment by Regalis11** [comment]
I think this was fixed along with #2986

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by hubismal** [comment]
This was not fixed, still happens with the latest 1005. Requesting this be reopened.

**Comment by Rokvach** [comment]
Still an issue, moving back to To do.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/d75bb8a21b1a938f2b882f6970dec012ae836e72

**Comment by Rokvach** [comment]
No issues, closing.
