### ISSUE TITLE
[0.1001.0] Crafted/Purchased Headset and Spawnitem Headset has incorrect team id

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#2976]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Crafted Headset and Spawnitem Headset has incorrect team id

**Version**
0.1001.0

**Comment by Regalis11** [comment]
Fixed crafting in https://github.com/Regalis11/Barotrauma-development/commit/cb80967dee39e9ffc21c3d494d793e6638dee501

**Comment by Regalis11** [comment]
Fixed purchased headsets in https://github.com/Regalis11/Barotrauma-development/commit/bb9cebd5142892f6b636c3910d21873d8dbbc45a

Note that the 1st commit was done in bugfixes and the second in campaign-groundwork, might make sense to wait for the branches to be merged before testing

**Comment by Rokvach** [comment]
Still an issue on Unstable 0.1002.0.0 which should have the bugfixes merged

**Comment by Regalis11** [comment]
Seems to work correctly in single player. Fabricators should now also work in multiplayer https://github.com/Regalis11/Barotrauma-development/commit/2b516f51640708259247d89978cc78b84e7712ff, need to look into the issue with the purchased ones in mp campaign.

**Comment by Regalis11** [comment]
Purchased headsets seemed to work as expected, steps to repro?

**Comment by Regalis11** [comment]
Closing this for now, will reopen if we figure out a way to repro this
