### ISSUE TITLE
[0.1003.0] Multiplayer - Purchasing too many subs causes issues on level transitions.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3110]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
So we made it to a outpost and decided to purchase every single vanilla submarine, as well as a duplicate Orca. The save sort of bricked now whenever we try to transition levels. If you reload the campaign save, you can play for that round until the next transition.

[Multiplayer.zip](https://github.com/Regalis11/Barotrauma/files/4782164/Multiplayer.zip)

![](https://cdn.discordapp.com/attachments/668819422919524352/722152672282542190/Capture.PNG)

Followed by:
![](https://cdn.discordapp.com/attachments/668819422919524352/722152746672848996/Capture.PNG)

**Version**
0.1003.0

**Comment by Kaillera** [comment]
Upon decompressing and reducing the amount of owned submarines, the errors stopped happening.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b933f1481bb8658998ad90601428a3c88a500e6d

**Comment by Rokvach** [comment]
I was still able to reproduce this issue while playing as a client on my own dedicated server and buying all the submarines, but the save didn't brick for me it just disconnected me from the server and I was able to continue from where I left off. It does however seem that my submarine was switched without me ordering the switch. 

I had Orca selected as my submarine from the start, bought all the subs and loaded in to a round and Orca was still selected but no characters spawned for a while, then I got disconnected and returned to the server and now Azimuth is selected instead of Orca. @Regalis11  

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/d1e64d03-2eee-468e-b052-3200bd1cc2ca)

**Comment by EdusFF** [comment]
Tested after the submarine sync improvements and wasn't able to reproduce, bought 18 subs and transitions worked correctly.

**Comment by Regalis11** [comment]
@EdusFF Note that this happens because receiving the save file takes too long, so the results may not be accurate if you're testing this locally (the files aren't sent over the network when you're the host so they "arrive" immediately, and even if you're not the host the transfers are way faster when both the client and the server are running on the same machine).

**Comment by Rokvach** [comment]
This is still an issue, tested by buying all the vanilla submarines while I had 2 other players on the server

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/2a62b15e-9df6-46dc-9cd1-b0c47a1f1b68)

**Comment by Regalis11** [comment]
Sped up the transfers further in https://github.com/Regalis11/Barotrauma-development/commit/46037d5cff493502a0ebdab824db71a0efc59caa. Sending all the vanilla subs now only takes a couple of seconds, but I think we should still add some kind of a cap to the number of subs you can buy.

**Comment by Kaillera** [comment]
If you're going to add a limit, I think allowing us to sell subs / sell and switch sub at the same time will make that limitation not as bad. I think we only need one sub per class type anyways.

**Comment by Rokvach** [comment]
Still an issue in 0.10.3.0, looks like it depends on the amount of submarines or if there's a mixture of vanilla and custom subs. 

Worked correctly if I selected all the vanilla subs
Worked correctly if I selected 3 custom submarine at once

Failed when I bought all the vanilla subs + 2 custom subs
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/5ffafd13-a349-475b-8ca6-a8c951b29300)

**Comment by Regalis11** [comment]
Assuming the issue had something to do with the speed of file transfers, this might have been fixed, as there's been significant improvements to the file transfer logic since.

https://github.com/Regalis11/Barotrauma-development/commit/778290f2f03128e1da8d15d003c3cea00bfbba76
https://github.com/Regalis11/Barotrauma-development/commit/3d53be75d7e8cc144158783e5766c81e946239e2
https://github.com/Regalis11/Barotrauma-development/commit/e1f9a4a07f160de60d89ee7c9e8d89b036bda079

**Comment by Rokvach** [comment]
I wasn't able to reproduce this no matter what I threw at it when playing on my dedicated server as a client, will need to test this with more players. I have seen the error message still appearing in GA but that also might not be related to this issue but something else throwing it.

**Comment by NilanthAnimosus** [comment]
Tested against Release/traitor-update commit https://github.com/Regalis11/Barotrauma-development/commit/bc34924c6209b5f6ec8749afa6fe213466f33cfd

Used many submarines to create an almost 10mb save file (Which I don't think any campaign will reasonably exceed) and saw no issues except longer load times, however this was on the same machine. Will need to do some testing over the web to see if there are any issues when downloading the save files as a remote client.

**Comment by NilanthAnimosus** [comment]
Tested (using the same above save file) W/ a remote client. Had no issues thus closing.
