### ISSUE TITLE
Unstable - Infinite outpost event farming

### ISSUE THREAD

**Issue by Udrakan** [Regalis11/Barotrauma#3267]
**Description**
By redocking, it's possible to complete many events per minute, which in turn allows you to discover all events branches in a matter of minutes and no traveling at all, and also gain reputation.
**Steps To Reproduce**
Do an outpost event
Undock and redock the sub
New event is available
**Version**
Unstable

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/149d7fdd771381f458eca9d77bd6ba4599dd121f

**Comment by Rokvach** [comment]
No issues, closing.

**Comment by Udrakan** [comment]
This was not fixed, unfortunately. Here is a save:
[Gauge_1.zip](https://github.com/Regalis11/Barotrauma/files/6137051/Gauge_1.zip)
STR:
1) Find a captain NPC at the outpost, talk to him
2) finish the event any way you like
3) re-dock
4) captain is going to be there again, allowing you to farm reputation and helm skill to 100 in 1 outpost for free

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0edd10f4b78375132bd400166938fcdfc9589a4c

**Comment by Xeavas** [comment]
[V0.1300.0.3] - Used save provided by Udrakan, I got different events each time I redock, but I've also gotten 2 giving directions events back to back. I think the Issue is not resolved.

**Comment by Rokvach** [comment]
Moving back to Misc

**Comment by Regalis11** [comment]
Found yet another issue, looks like the list of non-repeatable events didn't save properly between rounds. Fixed in https://github.com/Regalis11/Barotrauma-development/commit/8b5b28b9b6fac5307c4839377961e7146790bb21

**Comment by Xeavas** [comment]
[v0.1300.0.6] - Still able to replicate, with the provided save (by Udrakan) and with starting a fresh save, this time it just gave the 'giving directions' event back to back to back using the same replication methods, thus the issue is still present.

**Comment by Rokvach** [comment]
Moving to back to Misc again, as that would be a bit too easy way to gain helm skill

**Comment by Regalis11** [comment]
Looks like this happened when after all of the non-repeatable events had been triggered (which was the case in that save). 4th time's the charm: https://github.com/Regalis11/Barotrauma-development/commit/6368316dea39ee61bf74222dc9a814eff6dcf6dc

**Comment by Rokvach** [comment]
Tested, I was only able to get 1 event per outpost no matter if I re-docked, restarted save or traveled to another outpost and back I never unlocked more than that 1 event. So it does seem to be fully restricted now, working correctly. Closing. Lets hope I don't need to open this ticket again
