### ISSUE TITLE
Custom asset disappears from ship upon first save in the editor

### ISSUE THREAD

**Issue by GophTheGreat** [Regalis11/Barotrauma#3351]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Custom asset disappears from submarine when I save it in the editor, but only on the first manual save upon opening the editor.

**Steps To Reproduce**
Download this ship: https://steamcommunity.com/sharedfiles/filedetails/?id=2158340193 and enable its assets in the mod menu.

Open the ship in the editor.

Save the ship. The Chasm Block 1 blueprint on Deck A will disappear. Replace the object then save again and it's fine.

Exit the editor. Reopen the editor and the ship. Save again and the blueprint will disappear again.

**Version**
0,9.10 (unstable), Windows 10.

**Additional information**
It could have something to do with the asset being categorized as an OpDeco? I have a several other custom assets aboard the ship that are categorized as "labels" and they never exhibit this behavior.

**Comment by Regalis11** [comment]
Does not seem to occur in v0.10.4.0, so I guess this has been fixed

**Comment by GophTheGreat** [comment]
I'm still getting the bug unfortunately. Here's a gfycat of it: https://gfycat.com/meekgoodnaturedgroundhog.

**Comment by Rokvach** [comment]
Moving back to To Do

**Comment by Regalis11** [comment]
Found a way to repro this now. The problem was that I just created a copy of the sub, but this issue only occurs if the sub is included in the same content package as the custom items.

Steps to repro:
1. Create a content package that defines items and a custom sub (or create a copy of the Chasm 1 mod and publish it as a hidden item in the workshop).
2. Make sure the sub has some of the custom items in it
3. Save the sub

**Comment by Regalis11** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/e7b9d86e65f7c9c0df16a6f0637dd5cfc28151f6. The content package is no longer reloaded when saving a sub in the editor.

@juanjp600 Could you take a look at the changes and see if they make sense to you? I'm not sure why the package was reloaded when saving, but I might've missed something.

**Comment by juanjp600** [comment]
No issues found with this, waiting for Rokvach to test

**Comment by Rokvach** [comment]
Wasn't able to reproduce, looks to be working correctly. Closing.
