### ISSUE TITLE
Unable to craft stun gun darts because of #2425

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#3588]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Unable to craft stun gun darts because of #2425

**Comment by Regalis11** [comment]
Marking this as a code issue, because I think we should make it possible to define fabrication ingredients based on tags instead of identifiers (i.e. any type of wire should be usable as an ingredient).

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ca894b61f191b20a68f97e25c8fb8e5ffcc3258d

**Comment by Rokvach** [comment]
This seems to be still broken, I'm trying to craft a Stun Gun Dart using a Steel Bar and a Black Wire but the Create button is still grayed out, only seems to work when using a Wire

Also a minor visual bug, when I place a Black Wire in to the input slot it doesn't take the place of the Wire indicator but instead pushes the Wire indicator in to a different slot. Not sure if this is only because I am unable to use the Black Wire in this case.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/faa62759-605a-4884-9f10-c244b6229c4b)

**Comment by Regalis11** [comment]
I think something went wrong with a merge somewhere along the line: the fabrication recipe was changed from `<Item identifier="wire" />` to `<Item tag="wire" />` in the earlier commit but seems to have been reverted at some point. Should be fixed now.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
