### ISSUE TITLE
Oxygen bottles misaligned in submarine oxygen generator

### ISSUE THREAD

**Issue by ignis05** [Regalis11/Barotrauma#3642]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Bottles in the submarine oxygen generator are not centred properly like in the outpost oxygen generator.

**Version**
v0.10.4.0 Windows

**Additional information**
If you compare bottles positioning in the submarine oxygen generator to the outpost oxygen generator you can clearly see that all bottles in the submarine oxygen generator are misaligned.
![image](https://user-images.githubusercontent.com/48099798/91345050-15f01400-e7df-11ea-9c36-e1687f8c8fcf.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f0629414241884c77fa9473c8ae70800f6ca1681

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by ignis05** [comment]
Issue still present, even though unstable patch notes state otherwise.

![unknown](https://user-images.githubusercontent.com/48099798/92417205-55185080-f161-11ea-986c-d9ccc3c16e59.png)

**Comment by ignis05** [comment]
Version v0.1100.0.6, bottles still misaligned slightly to the right (screenshot from the beacon station)
![image](https://user-images.githubusercontent.com/48099798/99149290-4b452900-268d-11eb-83d6-10d2f126352c.png)
