### ISSUE TITLE
WIFI input does not respect link to chat status

### ISSUE THREAD

**Issue by Xacorman** [Regalis11/Barotrauma#3913]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The wifi component accepts input from chat regardless of it's 'link to chat' status. The link to chat button only modifies the wifi output going to chat instead of turning off chat integration completely.

**Steps To Reproduce**
Place wifi component and hook the output to a text display. Verify link to chat is disabled. Use the chat running on the same channel and see your output going to the display.

**Version**
0.10.5.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/0c13bd084b20ac41a029d952ba85558b857339a9

**Comment by Xeavas** [comment]
[0.1100.0.5] - Unfortunately I am still able to replicate, using the setup below.

[LTCTest.zip](https://github.com/Regalis11/Barotrauma/files/5526722/LTCTest.zip)

**Comment by Xeavas** [comment]
[0.1100.0.5] - Progress on fix (radio doesn't register for linktochat false wifi components for the output pin) but still receiving messages from other wifi set to the same channel. This issue is still present for me using the setup I provided.

**Comment by Regalis11** [comment]
If I understood the problem correctly, that's actually how I intended it to work. Linking to chat doesn't mean the item is only able to receive messages sent from the chat, just that the component is able to receive messages from the chat and that received messages are displayed in the chat of the character holding the item.

**Comment by Xacorman** [comment]
My argument of having wifi components not always accept input from chat is that it can potentially break logic by forceing acceptance of 
non-expected input. If it's intended that wifi always accepts input then is it possible to allow us to secure it?

**Comment by Regalis11** [comment]
To be clear, wifi components that aren't linked to chat should no longer receive messages from the chat. But components that _are_ linked to the chat can receive messages from non-linked components as well.

**Comment by Xacorman** [comment]
I haven't had a chance to test, but sounds like you fixed the issue then. Didn't realize you were responding to the other comment when you said it was working as intended.

**Comment by Rokvach** [comment]
Working correctly, closing.
