### ISSUE TITLE
Do not load coop save

### ISSUE THREAD

**Issue by ULiX80** [Regalis11/Barotrauma#3986]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I began another mission to destroy the swarm.
An error message appeared. Exit in the lobby. Tried to continue, but the error message keeps repeating. Restarting the game also doesn't fix the situation. 

Message text: 
**Received an update for entity that doesn't (event id 356, entity id 8449)**

I started looking for where the save files were stored. I was hoping for backups, but there were none. Now I am unable to continue the game. I really don't want to start a new company.

**Steps To Reproduce**
Try to load the save yourself. I attach the files.

**Version**
Windows v.0.10.5.1  (revision 9e259b2148)

I see that there were reports of similar errors more than a year ago, but errors and keep repeating. No solution proposed. This is bad.

![20201003025327_1](https://user-images.githubusercontent.com/6950252/94951740-2efb8b80-0528-11eb-8bd5-fc5da2700bd6.jpg)

[Barotrauma.zip](https://github.com/Regalis11/Barotrauma/files/5319434/Barotrauma.zip)

**Comment by Regalis11** [comment]
This seems to have been caused by a bug in the way monster missions are synced that sometimes lead to entity IDs getting mixed up client-side. The issue should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/ad780a646cec44bde24114047dcace20963b1a27, but unfortunately you'll have to wait for the next patch for the fix to be released.

However, with that fix in place I was able to re-enter the previous outpost and save the campaign, which should allow you to continue as long as you don't select that specific crawler swarm mission before leaving the outpost: [COOP1.zip](https://github.com/Regalis11/Barotrauma/files/5323612/COOP1.zip)

**Comment by ULiX80** [comment]
Many thanks!
It turned out to continue the game.

**Comment by Rokvach** [comment]
Reopened the ticket as the provided save is just a temporary fix, the overall issue still needs testing.

**Comment by Rokvach** [comment]
There hasn't been any sightings, working correctly. Closing.
