### ISSUE TITLE
[0.1100.0.3] Failing Beacon Mission. Probably due to deterioration rate.

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4231]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
It seems like the only way to complete the new Beacon mission is to leave a character behind to maintain the station because the junction boxes and/or sonar monitor deteriorates pretty fast, or to complete the level very fast after fixing it.

**Version**
0.1100.0.3

**Comment by ezjamsen** [comment]
fixed in dev

**Comment by Xeavas** [comment]
Note : Still an issue in [0.1100.0.4], specifically Junction Boxes(deterioration) and the Reactor(fuel consumption) of BeaconStation1 
**Testing methods :**
1) disable eventmanager and teleport to beacon station
2) drain/repair everything inside it and 4 fulgurium rods in the reactor(and stabilize power)
3) power on beacon, afk from it for 30mins
4) return to it, and drive it back to complete mission without touching beacon station
5) observe

**Test results**
- 14 minutes in. the junction box to the navigation terminal blew, resulting in failure of mission if I did return to a station.
- 20 minutes in. the junction box connecting the reactor to the grid blew, resulting of power outage throughout the whole beacon
- All fulgurium rods are ~5% deteriorated at the 20minute mark after said Junction boxes blew

Checking in subeditor confirms the above.
![be1](https://user-images.githubusercontent.com/72674994/98444629-b2bf1e00-214d-11eb-88c6-750a54396206.jpg)
![be2](https://user-images.githubusercontent.com/72674994/98444632-b488e180-214d-11eb-8766-3908211a0984.jpg)

**Comment by Regalis11** [comment]
Fuel consumption fixed in https://github.com/Regalis11/Barotrauma-development/commit/20c18e4, deterioration still needs to be disabled on the junction boxes

**Comment by ezjamsen** [comment]
Fixed deterioration. Issues were due to save location causing confusion and incorrect versions being committed.

**Comment by Xeavas** [comment]
[0.1100.0.5] - Retested, unable to replicate 👍

**Comment by Rokvach** [comment]
Closing.
