### ISSUE TITLE
Medic grabbed my engineer and wouldn't let him go 

### ISSUE THREAD

**Issue by NyarlathotepZERO** [Regalis11/Barotrauma#4324]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I had a medic grab an injured engineer as if to heal him, but he would not let him go.

**Steps To Reproduce**
I was in station and assigned the medic (from the radial menu) to heal injured, he ran straight for my injured mechanic, grabbed him and would heal him, nor would he let him go. 

**Version**
Unstable v0.1100.0.6  [Windows 10]

**Additional information**
Checking the medic's inventory I assume it was because he did not have appropriate equipment to heal the particular damage. 

I'm all for having a friendly crew, and I wish more than anything that they would all get along with each other, but nonetheless, my sub is a busy place, and I believe that upon realizing this, the medic should have run off to grab what he needed rather than hold up my mechanic in idle conversation, keeping him from his assigned tasks.

I'm not entirely sure as to how the AI performs, but perhaps the fact that he was in station made it difficult for him to path to a locker on the sub to grab any required items (of which I had plenty of) to complete his task. 

The 3 screenshots I have attached are:

![1](https://user-images.githubusercontent.com/26475624/99197854-19e17000-27e9-11eb-9b3a-39fa30159c74.png)
1. The medic grabbing the mechanic (and showing inventory).

![2](https://user-images.githubusercontent.com/26475624/99197852-164de900-27e9-11eb-928f-f86430829e34.png)
2. The injuries that the mechanic was suffering from.

![3](https://user-images.githubusercontent.com/26475624/99197853-18b04300-27e9-11eb-8d53-1691ed602738.png)
3. The medic's stats/skill levels.

**Comment by itchyOwl** [comment]
The medic should pick the items that he/she needs for healing before grabbing. Not sure what happened here, but maybe the medic run out of the ingredients. Need to test and try to repro it.

**Comment by itchyOwl** [comment]
Should be fixed in Regalis11/Barotrauma-development@8cae651. Related to #1989 (dev)

**Comment by Rokvach** [comment]
> Steps to repro (there might be simpler steps, but this is how I did it):
> 
> 1. Remove most of the medical items from a submarine in the editor. Leave some bandages or bloodpacks.
> 2. Play in the submarine
> 3. Shoot a bot so that it bleeds (don't kill it)
> 4. Order a medic/bot to heal, if it doesn't do it already
> 5. Ensure that the healer doesn't have any medical items with it (teleport outside and just drop the items in the sea, then quickly teleport back before you die)
> 6. Allow the bot to take some medical items from a container
> 7. Select the bot when it's in the middle of running to the patient.
> 8. Take all the medical items and repeat step 5.
> 9. Type "freecam" to uncontrol the bot.
> 10. Before the fix the bot would be stuck on holding the patient and then releasing it periodically. After the fix the bot should release the patient, yell "no can do" and continue with other things, ignoring the target for a while.

**Comment by Jlobblet** [comment]
Tested, still present.  
Steps used to reproduce:  
1. Edit Dugong. Remove the medical cabinet. Remove all supply cabinets except one in medical room.
2. Enter test mode. Spawn a doctor.
3. Swap to the doctor and use all the medicine on yourself.
4. Swap to captain, shoot mechanic.
5. Order medic to heal people.
6. After medic has grabbed supplies from the medical room (you can spot them running back through diving suit room), swap to medic and use medicine on yourself.
7. Observe  

Some things I noted:  
If you grab the bot with the heal interface, the medic will stop grabbing the bot. Ordering the medic to heal again will cause the grabbening to continue.

![image](https://user-images.githubusercontent.com/37539527/101966707-af1d2c00-3c10-11eb-932e-43ac784f3e53.png)

**Comment by Rokvach** [comment]
Moving back to to do

**Comment by itchyOwl** [comment]
Can't reproduce it anymore: the medic always stops treating and tells that there's nothing to be done for the patient, as intended. Tested on the dev branch (debug) and in the unstable build (release, Steam version).

Did you test it in the unstable or release? The fix is not yet in the release build.

**Comment by Rokvach** [comment]
Could be that this was fixed in the latest Unstable we released on December 18th

**Comment by itchyOwl** [comment]
Ah, true, didn't notice that the comment was that old. That's probably the case.

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
