### ISSUE TITLE
Scaling Text Display Misaligns Text

### ISSUE THREAD

**Issue by bavarianblacksmith** [Regalis11/Barotrauma#4370]
- [X] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Changing the scale of the text display, specifically down, misaligns the text, even if the text is set to the same downscale.

**Steps To Reproduce**
Spawn display, change scale, view text.

**Version**
v10.6.2 Windows

**Additional information**
None

**Comment by 3e849f2e5c** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/05645ec979c3e9be77c330883103074d317fe3a0

**Comment by Regalis11** [comment]
The fix seems to only work in the editor (easy to notice by setting the padding of the label to something else than 0)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/1d4df6a4fefeb9d73cd3140f605fc6511cb7d97c

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by KrusteDE** [comment]
The Issue is back, i resized the text inside of the planel to 0.9 to fit inside. In the editor its working but as soon i'm playing online with the updated submarine on a new session, the text wont be shown.
