### ISSUE TITLE
Submarine getting stuck in terrain

### ISSUE THREAD

**Issue by Gwilt** [Regalis11/Barotrauma#4632]
- [yes ] I have searched the issue tracker to check if the issue has already been reported.
(May be related to #1243)

**Description**
During a couple of different playthroughs our submarine has gotten 'wedged' in terrain, such that it cannot move in any direction.

**Steps To Reproduce**
Essentially the submarine slides in between terrain pieces such that it is stuck in place and cannot maneuver outside of it. Pictures are available here:
https://drive.google.com/drive/folders/1d-P6PPOz5BFJHgrno30LQNUzjDyj6Ned

Methods to free the stuck ship include removing parts of the sub including damaging the engine to see if that would allow it to be freed. In the latest playthrough we enabled cheat commands in the console to teleport the sub.

**Version**
Latest steam version (0.11.0.10, Windows, Branch release, revision dc7157029e)
OS - Windows 10 Pro

**Additional information**
Happened during a 4 player multiplayer scenario

**Comment by MonstraG** [comment]
Happened to me in this way:
![image](https://user-images.githubusercontent.com/17963791/104486298-5cf37000-55ed-11eb-80b5-d7b5e923f7e2.png)

**Comment by Ras-Tafari** [comment]
I'm new to the game but it seems the problem still occurs. Got stuck between terrain, seems like the non room portion of the sub clipped with the surrounding rocks. Enclosing screen, I was even able to get my character behind my Dugong's frontal part.

![20211114231008_1](https://user-images.githubusercontent.com/4569855/141702411-576fc3c8-0f97-4404-a88d-7313d4a82f2c.jpg)
![20211114231256_1](https://user-images.githubusercontent.com/4569855/141702413-7f93fec2-9855-4f12-88e2-1ddee4cdf2f9.jpg)
![20211114231414_1](https://user-images.githubusercontent.com/4569855/141702414-6a8e0ec1-2edd-47de-89cf-e92f79d50f75.jpg)
s.

**Comment by Camper125Lv** [comment]
![image](https://user-images.githubusercontent.com/32136089/150641989-e3f01e72-fbcf-48c6-b690-e5249f7af51c.png)

Got stuck too. Seed: 6zDGBCyK (v0.15.23.0) was moving from Krytogorsk City to The city of Delgovskov using Humpback

**Comment by ElwoodHogan** [comment]
july 1st, getting this issue as well

**Comment by HighError** [comment]
![image](https://user-images.githubusercontent.com/46526245/182246684-b7578207-e3bb-4892-a899-8086080bdd05.png)

**Comment by HighError** [comment]
omg The shuttle is saved, dock and pull the shuttle

**Comment by HighError** [comment]
1) 1 crew member dies
2) We wait for 5 minutes
3) Having revived, the crew member docks the shuttle to the ship
4) The shuttle pulls the ship with its own power

In the video it looks like I pulled the boat out with my own power, but that's not the case, it was actually the shuttle that did it

Clip:
https://medal.tv/games/barotrauma/clips/uROKrAY2_RVUI/d1337BrBK3pn?invite=cr-MSwyVkQsNTE5MDQzOTMs

Hope this helps you

**Comment by IndirectCell** [comment]
![image](https://user-images.githubusercontent.com/60559077/206917186-30ed5af9-d007-4fcf-b55c-8ab715200e38.png)

This is still the case as of Unstable - Public unstable version.

Mission demands i head up this place as im still in early game, no scooters and stuff.. and theres a 500m swim wich isnt realy viable if one gets attacked along the way.. anyway decided to push my up seeing it looked like i could get trough... however instead of getting trough sub got stuck or wedged.... i allready did as some of the people higher up commented that they did, i tried cutting off the front of the sub to where it visually looks like it could go.. but nope.

Really sucks as i had been mineing minerals and spent well over a hour only now decided to go to mission marker... and this happend...

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f9f7b1ec964c6437f158bece72376a7c88a479d3

**Comment by Greggho** [comment]
Seems to still happen in v1.0.7.0 - this was seemingly the only way through towards the waypoint, seemed the next few bends were possible so I thought to give it a shot but got the sub lodged inside the walls apparently
Only fix was teleportsub (and turns out the actual route was further below this maze)

![20230316004925_1](https://user-images.githubusercontent.com/20175112/225509764-e63ae192-e891-4cba-b719-d3906a7c1fef.jpg)

![20230316004958_1](https://user-images.githubusercontent.com/20175112/225509808-6c2db4e5-8b11-4d7f-81ca-d7f2f56148c7.jpg)

![20230316005019_1](https://user-images.githubusercontent.com/20175112/225509812-a8aec480-aa8b-4b5e-8330-f16776ed00e2.jpg)

**Comment by Regalis11** [comment]
The fix is not yet included in any public build. Sorry for the inconvenience!

**Comment by Rokvach** [comment]
Tested, working correctly. Can be merged and closed.

**Comment by IndirectCell** [comment]
Impressive, cant wait to test and see if i can actively wedge the sub between things, kinda wonder how youd go about fixing it :DSendt fra min iPad28. apr. 2023 kl. 05:12 skrev Roni Kovaniemi ***@***.***>:﻿
Tested, working correctly. Can be merged and closed.
