### ISSUE TITLE
Monsters spawning inside floating rocks

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#4875]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Monsters, particularly kill swarm mission monsters, can spawn inside the floating piezo crystal rock formations.

Needless to say, this alone stops a mission from being completable
Happened on multiple ocassions

**Steps To Reproduce**
take a kill (swarm) mission in the plateau/great sea

**Version**
0.11 stable

**Additional information**
screenshots/video

threshers
![image](https://user-images.githubusercontent.com/5103517/105569687-ba846c80-5d11-11eb-95aa-370a42015841.png)

crawlers
https://user-images.githubusercontent.com/5103517/105569695-ccfea600-5d11-11eb-81ae-5af7a28fc3ba.mp4

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/42a1fbf5a3aec148765cc09018968f29e5368dfe

**Comment by itchyOwl** [comment]
Still happens (inside a cave) ![image.png](https://images.zenhubusercontent.com/5c93b12055cf186934fc0a03/df620037-8f9f-4c8d-a2f4-94db2b1e6eae). On dev.

**Comment by Rokvach** [comment]
Afaik the cave ice is handled a bit differently than the floating one, so I would classify that as a separate issue

**Comment by Rokvach** [comment]
I've run quite a few levels now and haven't encountered any occasion where a creature has been stuck on the floating ice. I think this is working correctly now and if it still exists in some form it would be a rare encounter. As I stated the ice on caves I think is a separate issue and I don't view it as big of an issue as the floating ice ones. Closing.
