### ISSUE TITLE
Crash when starting or ending a round: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Krzeszny** [Regalis11/Barotrauma#4902]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was crashing to the main menu **each time** the round started or ended in a certain multiplayer game. 
I was a client, the server had no mods but was using a custom sub. 
It only started doing that after a few rounds, fresh campaign, but kept **crashing with each station docking/undocking**. 

Same errors each time, for example:
![Barotrauma_SQ5ciIenWD](https://user-images.githubusercontent.com/10529134/105779573-f10af300-5f6e-11eb-8871-0eb42735b4a0.png)
There was another error window under that one. I hope it's all in the log but more on that below.

There was only one instance after the crashing had started when I didn't crash to the main menu on a mission start, but it kept crashing on docking/undocking afterward.

**Steps To Reproduce**
???

**Version**
v0.11.0.10
Win 10 20H2

**Additional information**
This log was generated when I pressed "Yes" in a Ready pop-up that remained open after I crashed to the main menu. From what I can see, the errors are the same as in the start/end round crash.
```
Barotrauma Client crash report (generated on 25.01.2021 23:43:26)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


47BDC83F092CDFE5B755C0308161F31E


Game version 0.11.0.10 (ReleaseWindows, branch release, revision dc7157029e)
Graphics mode: 1920x1080 (Fullscreen)
VSync ON
Language: English
Selected content packages: Vanilla 0.9
Level seed: no level loaded
Loaded submarine: None
Selected screen: Barotrauma.MainMenuScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19042.0 64 bit
    GPU name: NVIDIA GeForce GTX 970
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Void CreateResultsMessage()
Stack trace: 
   at Barotrauma.ReadyCheck.CreateResultsMessage() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\ReadyCheck.cs:line 78
   at Barotrauma.ReadyCheck.<CreateMessageBox>b__16_0(GUIButton <p0>, Object <p1>) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\ReadyCheck.cs:line 50
   at Barotrauma.GUIButton.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIButton.cs:line 262
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 1214
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 951
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 656
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 500
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[25.01.2021 23:41:28] Coroutine "Barotrauma.Networking.GameClient+<StartGame>d__82" has failed
[25.01.2021 23:41:28] Error
[25.01.2021 23:41:28] There was an error initializing the round. {Object reference not set to an instance of an object.}
   at Barotrauma.Networking.GameClient.StartGame(IReadMessage inc)+MoveNext() in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 1567
[25.01.2021 23:41:24] WARNING: Cannot compress a texture because the dimensions are not a multiple of 4 (path: Submarines/Downloaded/Artemis.sub, size: 1920x797)
[25.01.2021 23:41:23] Error while reading a message from server. {Submarine equality check failed. The submarine loaded at your end doesn't match the one loaded by the server. There may have been an error in receiving the up-to-date submarine file from the server.}
   at Barotrauma.Networking.GameClient.ReadStartGameFinalize(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 959
   at Barotrauma.Networking.GameCl
```ient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 846
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 242
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 614
[25.01.2021 23:41:22] Task count: 0
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:13] WARNING: Junction Box has incorrect "Enhanced Resistors" level! Expected 2 but got 1. Fixing...
[25.01.2021 23:41:12] Generating an outpost for the end of the level... (Location: Echion Linea, level type: LocationConnection)
[25.01.2021 23:40:41] JonnyBlaze
[25.01.2021 23:40:41] Dakota
[25.01.2021 23:40:41] MagnustheWizard
[25.01.2021 23:40:41] IHuffPetrol
[25.01.2021 23:40:41] Kris
[25.01.2021 23:40:41] Wendy Juice
[25.01.2021 23:40:41] TymD
[25.01.2021 23:40:41] Manfred
```
The names keep looping, going back in time. I removed the rest of the loop.

I don't know if other players were crashing.

Also, how to allow Barotrauma to send crash logs automatically?
EDIT: formatting

**Comment by KimmoKari** [comment]
Duplicate ?

**Comment by Krzeszny** [comment]
[crashreport (2).log](https://github.com/Regalis11/Barotrauma/files/5920757/crashreport.2.log)
Is this also a duplicate? A random crash.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/79c2eeb1fb7deccafe3b7234bc03460821de0f5c

**Comment by pabimuri** [comment]
It is not fixed. 
[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/5986715/crashreport.5.log)

**Comment by pabimuri** [comment]
in my opinion to reproduce that bug, you need to give order to operate a turret

**Comment by Krzeszny** [comment]
> in my opinion to reproduce that bug, you need to give order to operate a turret

I was crashing each time, the moment we docked and undocked in multiplayer (this took place only on one server) so I don't think it had anything to do with AI.

**Comment by Regalis11** [comment]
@pabimuri That is not the same error as the one in this ticket, and this fix isn't yet available in either the public or unstable versions of the game.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
