### ISSUE TITLE
Crash - If you're missing sound file or using corrupted/fake .ogg file

### ISSUE THREAD

**Issue by Kaillera** [Regalis11/Barotrauma#4926]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Just messing around with putting in my own music in Barotrauma. Found out you will crash if a track is missing or you're using a corrupted .ogg or a non .ogg audio file disguised as .ogg.

[crashreport (5).log](https://github.com/Regalis11/Barotrauma/files/5889667/crashreport.5.log)
[crashreport (4).log](https://github.com/Regalis11/Barotrauma/files/5889668/crashreport.4.log)

**Version**
~0.12.0.1

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/802256bde22c6506bd3c124bbfa2dd6934df0ef5

**Comment by Rokvach** [comment]
The game wont crash anymore if a sound file is missing but it will still crash if the ogg file is either corrupted or a txt file disguised as a ogg file. Not sure if we have any means to prevent the game from crashing in that situation.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/19e97fba0a6adf2b340b18d8242ff2440dba3dca

**Comment by Rokvach** [comment]
Tested, only throws a error now about the file type, no crashing. Working correctly, closing.
