### ISSUE TITLE
[Unstable] - Endlocation endings are not where its supposed to be

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5224]
**Description**
![endbork1](https://user-images.githubusercontent.com/72674994/110968300-4f125f00-8392-11eb-8f66-69af3641dad6.jpg)
![endbork2](https://user-images.githubusercontent.com/72674994/110968309-520d4f80-8392-11eb-9a4e-60adfa065012.jpg)

**Steps To Reproduce**
Load up an endlocation in campaign or use save provided
[endborked.zip](https://github.com/Regalis11/Barotrauma/files/6131380/endborked.zip)

**Version**
V0.1300.0.2

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5a2e9d27ececb595b0fc3d1f0bbcf7e0f48a30f4

**Comment by Rokvach** [comment]
Doesn't seem to be fixed, I'm still seeing the end location in the wrong place

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c2238e56-0661-446d-ace8-41181c982a9b)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/47e50fb7de016af978d5e324b8ec919efe1e94ee

**Comment by Rokvach** [comment]
Wasn't able to repro it anymore, working correctly. Closing.

**Comment by Rokvach** [comment]
The end location is still wrong in terms of sonar position and going to the end particle effect doesn't complete the round

In this screenshot I'm at the end particle effect and the round just doesn't end

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6c745869-c49e-4902-a880-9c0f22b9ad2c)

**Comment by Regalis11** [comment]
Attempt 3: https://github.com/Regalis11/Barotrauma-development/commit/5d0745f7c2ee2b08c4523df7814589aedde518a6

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
