### ISSUE TITLE
[Unstable] - Slight bobbing from opening containers

### ISSUE THREAD

**Issue by Xeavas** [Regalis11/Barotrauma#5329]
**Description**
The screen will "bob" in and out if you open containers, a visual annoyance not seen in previous builds.

**Steps To Reproduce**
Place attention at the edges of the screen and rapidly open and close a container.

**Version**
V0.1300.0.3

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/c269c7b? @juanjp600 ?

**Comment by juanjp600** [comment]
Not fixed yet, this seems to be caused by a similar but ultimately different issue, still looking into it.

**Comment by juanjp600** [comment]
Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/62c0544f864137acbd403209a7ee03320fe43acb
