### ISSUE TITLE
"???" gate outpost located incorrectly

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#5358]
- [of course ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
"???" gate outpost appeared in an incorrect location, 2 locations away from where it's supposed to be.

**Steps To Reproduce**
Use the save attached 
[thedoodoonhewer.zip](https://github.com/Regalis11/Barotrauma/files/6218054/thedoodoonhewer.zip)

**Version**
v0.1300.0.3

**Additional information**
Is an outpost even intended to spawn here? there's no lock that prevents you from going into the center, and nothing special in the outpost.
![20210328175125_1](https://user-images.githubusercontent.com/55637865/112767888-85d1b180-8fef-11eb-84c1-72d5a3908633.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b054fcf66d8fe22c50f27191f16d062302541468

**Comment by LePiromano** [comment]
still happens in v0.1300.0.6
![image](https://user-images.githubusercontent.com/55637865/113377926-11c73e80-934c-11eb-8541-f277cbe31faa.png)

**Comment by Rokvach** [comment]
Could be that it happens in the same save still but wont happen in newer ones, not fully sure. Moving ticket to Misc for further checking

**Comment by LePiromano** [comment]
no longer happening, i was probably using an old save then.
![image](https://user-images.githubusercontent.com/55637865/113462091-a5087e80-93f5-11eb-84a2-4c38c75f6bf1.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/eab50d5022e387222ecfcb9245e37c4939e2fc81

**Comment by Rokvach** [comment]
Tested multiple campaign saves and didn't notice any, seems to be working correctly. Closing.
