### ISSUE TITLE
[Unstable] Reaper tax can't be cleared as the event doesn't spawn

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#5462]
Noticed the multiplayer campaign

**Comment by Regalis11** [comment]
Should be fixed now (commits listed above)

**Comment by Rokvach** [comment]
- [ ] If you speak with the NPC who has the event with a character who doesn't have affliction the event can't be closed
The button vanishes but I can still see the tooltip of it and can click something, the icon on top of the NPC flashes when I click the close button
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/76500c65-0443-4b0d-810a-8a0b23336cc3)

- [ ] The event closes prematurely, tested with the character who has the affliction and speaking to the NPC and closing the first part of the event just flashes the next part really fast and the event closes and doesn't allow me to interact with the NPC again.

**Comment by Rokvach** [comment]
- [ ] If you talk with the event NPC as a character who doesn't have the affliction and dismiss the event with the "E" key the event will just pop back up, pressing the close button properly closes the event

- [ ] Player who doesn't have the affliction but still has the event open while the player who does have the affliction goes through the event is given the option to buy the cure for Reaper's tax (No money is taken even if you happen to buy the cure for player who doesn't need it, which is good)
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/bdf83c04-27ae-465d-91d5-773ef2fece4e)

**Comment by Udrakan** [comment]
This might warrant another look at Speakertag conversations, because they don't work particularly well in multiplayer, like here: #5007. Being able to interact with the NPC alone and being able to cancel speakertag *during* the event and continuing the event would allow this tool to implement outpost NPC related features to work more easily. RN when player engages in speakertag conversation (one where you have to interact), selects an option that leads to normal conversation (that is given to players with a tag), other players start seeing the speakertag and can interact with the NPC till the end of the event.

**Comment by Rokvach** [comment]
Tested during Unstable community session, no issues were spotted. But I think it might still mess up if multiple players have the interface open at the same time as I mentioned above on the unticked part

**Comment by Rokvach** [comment]
Closing as the majority of the issues has been fixed
