### ISSUE TITLE
Players who spawn as their previous character mid-round always get the Reaper's Tax affliction in mp campaign

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#5517]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When a player joins a server they've previously played in (i.e. a campaign where they have an existing character), they get the Reaper's Tax affliction when they spawn mid-round even if their character has never died.

**Steps To Reproduce**
1. Start a new campaign
2. Disconnect with one of the clients
3. Start a new non-outpost round
4. Rejoin the server as the client who disconnected
5. Wait for a respawn

**Version**
v0.1300.0.x

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9bc99a71681b9670b855703dbd3bc13575b62cd8

**Comment by Rokvach** [comment]
I can still see the respawn with penalty toggle, but toggling it doesn't do anything

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/4e0d15ef-d2dc-4715-93ce-ab594f52e692)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ea078e3d194ff0e68da3299c25c5738a243860fa (referenced wrong ticket in the commit message)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
