### ISSUE TITLE
Backwall panels spriting

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#5567]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The "backwall panels" background does not cleanly tile, it has some area which bleed the background

**Steps To Reproduce**
If possible, describe how the developers can reproduce the issue. It is often extremely hard to fix a bug if we don't know how to make it happen.

**Version**
0.13 release

**Additional information**
![image](https://user-images.githubusercontent.com/5103517/115776468-23679900-a382-11eb-8d6d-70ce9b2eed82.png)
![image](https://user-images.githubusercontent.com/5103517/115776532-38dcc300-a382-11eb-9ec4-acd6ab2a940d.png)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/46a51e133e0ce2a1a07bf2cd41679a9c08f0bfd8

**Comment by Rokvach** [comment]
I'm still seeing some bleed from couple of the walls

Backwall Clean
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ecac4063-cbd7-483a-9a1f-df86cf0d3bf7)


Backwall Orange Panels
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/cc07907d-8a75-46a8-a6db-12fbc9b11751)


Backwall Orange Panels Window
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c5f790e3-fd3e-4b5b-93cf-e62be2ddc4f7)

This is more of a sprite issue

Backwall Window
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/2410e302-3400-4b6b-9267-5066dd529a31)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b5926f1406add14058c2e126923a4d9bf1b5cf66

**Comment by Jlobblet** [comment]
Still some gaps on BackWall Orange in the vertical direction.
Near the bottom here:
![image](https://user-images.githubusercontent.com/37539527/116131409-45d01e00-a6c4-11eb-9035-cc3285d99f80.png)

**Comment by Rokvach** [comment]
Tested, no issues. Closing.
