### ISSUE TITLE
Disguises do not change name colour in PVP

### ISSUE THREAD

**Issue by Tsunder** [Regalis11/Barotrauma#6031]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Disguising as a crew of the enemy team does not change the name colour

**Steps To Reproduce**
1. borrow ID card from enemy team
2. Enemy team still sees you as being a member of youru team

**Version**
0.13.3

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/19d3989d70debd0cf1a4627ef288a307739dc3a0

**Comment by Tsunder** [comment]
Related, in stable, unidentified (no named ID) characters also have team friendliness display (as ???). Would unidentified characters be identified as friend/foe?

**Comment by Rokvach** [comment]
The hover name is still shown as hostile, but the nametag color is correct, moving to Misc.

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/ec313020-1e33-4a48-b3de-81d47694ae3a)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/43bd6e9ffd12ccfe7438b0cf574da841fda5dd01

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
