### ISSUE TITLE
Pulse laser's beam particles cancelled by flora spores

### ISSUE THREAD

**Issue by LePiromano** [Regalis11/Barotrauma#6136]
- [no] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Trying to shoot a pulse laser inside a ballast flora spore colony will result in the beam effect not showing up, but the laser as a projectile is still there.
https://user-images.githubusercontent.com/55637865/122694439-b9e5f880-d213-11eb-90a0-90cc17127680.mp4

**Version**
0.14.6.0

**Comment by Regalis11** [comment]
This most likely happens as a result of the ballast flora particles causing the maximum number of particles to be reached. To address this, we implemented a "proprity system" for the particles that allows important particles like weapon effects to take up slots from less important ones, but it didn't quite make it into this update. 

https://github.com/Regalis11/Barotrauma-development/commit/d2b76811

**Comment by LePiromano** [comment]
it seems to still happen in 0.1400.7.0, but only when your laser is located in the center of the flora colony for some reason

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
