### ISSUE TITLE
[Disconnect from a server] Unauthorized multithreaded access to RandSync.Server

### ISSUE THREAD

**Issue by Showdoze** [Regalis11/Barotrauma#6184]
After some time playing in a multiplayer campaign with my friend (who was a host) i started to crash out of the server into a server browser every time a round ended (i.e Dock to an outpost, go on a mission, level transition, etc.) with an error message that i will post below, the issue seems like to be tied up to a save, since that didn't happen when i played by myself or on another save file, and persisted after restarting the game and even PC

Version 0.14.6.0

[event_error_log_client.log](https://github.com/Regalis11/Barotrauma/files/6720568/event_error_log_client.log)

the last part of the error log with the stack trace, it does say pirate mission, even tho the disconnect happened regardless of pirate missions existing in current round

```
6/25/2021 3:24:22 AM - Unauthorized multithreaded access to RandSync.Server
   at System.Environment.get_StackTrace()
   at Barotrauma.Rand.CheckRandThreadSafety(RandSync sync) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\Rand.cs:line 47
   at Barotrauma.Rand.Range(Single minimum, Single maximum, RandSync sync) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\Rand.cs:line 56
   at Barotrauma.PirateMission.GetRandomDifficultyModifiedElement(XElement parentElement, Single levelDifficulty, Single randomnessModifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\PirateMission.cs:line 142
   at Barotrauma.PirateMission.SetDifficulty(Single difficulty) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\PirateMission.cs:line 102
   at Barotrauma.PirateMission..ctor(MissionPrefab prefab, Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\PirateMission.cs:line 90
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Barotrauma.MissionPrefab.Instantiate(Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\MissionPrefab.cs:line 381
   at Barotrauma.Location.InstantiateLoadedMissions(Map map) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 621
   at Barotrauma.Map.LoadState(XElement element, Boolean showNotifications) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 1109
   at Barotrauma.MultiPlayerCampaign.Load(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 146
   at Barotrauma.MultiPlayerCampaign.LoadState(String filePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 907
   at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2626
   at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 379
   at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 944
   at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 243
   at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 632
   at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 986
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/ddf4ab82fb3be9fb3dbbdcf1518bc7f99cfcf125

**Comment by Rokvach** [comment]
Seems to be partially fixed, now clients are getting a event error disconnection when ever completing a pirate mission round, similarly as stated above the clients disconnect during the end round summary after docking to the destination outpost

- No event errors if you just teleport to the end without encountering the pirate sub. 
- No event errors if you sight the pirate sub and then teleport to destination and dock.
- Event error happens if you kill one of the pirates with the kill command and then dock to the destination outpost.

event_error_log_server_Jade Harley_842
[https://app.zenhub.com/files/93301055/3bc291a7-0911-437e-a094-b475f30a5c7f/download](https://app.zenhub.com/files/93301055/3bc291a7-0911-437e-a094-b475f30a5c7f/download)

event_error_log_client_Jade_Harley_842_AM
[https://app.zenhub.com/files/93301055/adac90c0-1185-47c2-a001-55ea80b9f85d/download](https://app.zenhub.com/files/93301055/adac90c0-1185-47c2-a001-55ea80b9f85d/download)

(Host) event_error_log_server_Rokvach_842
[https://app.zenhub.com/files/93301055/d42886c2-672b-4659-a054-28036749dd60/download](https://app.zenhub.com/files/93301055/d42886c2-672b-4659-a054-28036749dd60/download)

(Host) event_error_log_client_Rokvach_842
[https://app.zenhub.com/files/93301055/787b61d0-2ccd-4db8-af86-e15ad1ce8f56/download](https://app.zenhub.com/files/93301055/787b61d0-2ccd-4db8-af86-e15ad1ce8f56/download)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/6bddf89ca760347c2e1c19f534199c33e1469fe9

**Comment by Krab-ik** [comment]
> Fixed in [Regalis11/Barotrauma-development@ddf4ab8](https://github.com/Regalis11/Barotrauma-development/commit/ddf4ab82fb3be9fb3dbbdcf1518bc7f99cfcf125)



> После некоторого времени, играя в многопользовательской кампании с моим другом (который был хостом), я начал вылетать из сервера в браузер сервера каждый раз, когда раунд заканчивался (например, стыковка с аванпостом, переход к миссии, переход уровня и т. Д. .) с сообщением об ошибке, которое я опубликую ниже, проблема, похоже, связана с сохранением, поскольку этого не происходило, когда я играл сам или в другом файле сохранения, и сохранялось после перезапуска игры и даже ПК
> 
> Версия 0.14.6.0
> 
> [event_error_log_client.log](https://github.com/Regalis11/Barotrauma/files/6720568/event_error_log_client.log)
> 
> последняя часть журнала ошибок с трассировкой стека, в нем говорится о пиратской миссии, даже если отключение произошло независимо от пиратских миссий, существующих в текущем раунде
> 
> ```
> 6/25/2021 3:24:22 AM - Unauthorized multithreaded access to RandSync.Server
>    at System.Environment.get_StackTrace()
>    at Barotrauma.Rand.CheckRandThreadSafety(RandSync sync) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\Rand.cs:line 47
>    at Barotrauma.Rand.Range(Single minimum, Single maximum, RandSync sync) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Utils\Rand.cs:line 56
>    at Barotrauma.PirateMission.GetRandomDifficultyModifiedElement(XElement parentElement, Single levelDifficulty, Single randomnessModifier) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\PirateMission.cs:line 142
>    at Barotrauma.PirateMission.SetDifficulty(Single difficulty) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\PirateMission.cs:line 102
>    at Barotrauma.PirateMission..ctor(MissionPrefab prefab, Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\PirateMission.cs:line 90
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
>    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at Barotrauma.MissionPrefab.Instantiate(Location[] locations, Submarine sub) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Events\Missions\MissionPrefab.cs:line 381
>    at Barotrauma.Location.InstantiateLoadedMissions(Map map) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Location.cs:line 621
>    at Barotrauma.Map.LoadState(XElement element, Boolean showNotifications) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\Map\Map\Map.cs:line 1109
>    at Barotrauma.MultiPlayerCampaign.Load(XElement element) in <DEV>\Barotrauma\BarotraumaShared\SharedSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 146
>    at Barotrauma.MultiPlayerCampaign.LoadState(String filePath) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameSession\GameModes\MultiPlayerCampaign.cs:line 907
>    at Barotrauma.Networking.GameClient.OnFileReceived(FileTransferIn transfer) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 2626
>    at Barotrauma.Networking.FileReceiver.ReadMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\FileTransfer\FileReceiver.cs:line 379
>    at Barotrauma.Networking.GameClient.ReadDataMessage(IReadMessage inc) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 944
>    at Barotrauma.Networking.SteamP2PClientPeer.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\Primitives\Peers\SteamP2PClientPeer.cs:line 243
>    at Barotrauma.Networking.GameClient.Update(Single deltaTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Networking\GameClient.cs:line 632
>    at Barotrauma.GameMain.Update(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 986
>    at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 651
>    at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 504
>    at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
>    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
>    at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
>    at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59
> ```

Did you fix the error?

**Comment by Krab-ik** [comment]
> Fixed in [Regalis11/Barotrauma-development@6bddf89](https://github.com/Regalis11/Barotrauma-development/commit/6bddf89ca760347c2e1c19f534199c33e1469fe9)

Why when I click on this link, I get a 404 error (Didn't find anything here!)

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
