### ISSUE TITLE
[Alien Ruins] Artifact Transport Case issues

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#6790]
- [ ] There's no limit as to how many full cases you can carry in your inventory, should the case occupy your hand slots when it contains a artifact or should the case be similar to a crate where you can only carry it in your hand slots?

All of these contains a artifact
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b21f9be0-4943-402b-8edd-6a2a43ff64a1)

- [ ] Shows artifact particles on player character even when the case isn't equipped
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/0b6a216e-afbe-4d65-bb0d-d6e3b0efe38c)

- [ ] Doesn't display full when there's a artifact inside the case
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/108e2b3b-bba7-4f26-8b7a-d2c87255794c)

- [ ] Wrong inventory icon
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/6da7f3cf-ba52-4ebc-a444-f9761b43a944)

- [ ] Collider too small
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/f7bc9f28-4fea-47c0-b348-d67f6f8ed83d)

**Comment by danielasteljoki** [comment]
Fixed all but the first issue. There is no fitting slot for it right now, and limiting the options goes against its reason for existing.

**Comment by Rokvach** [comment]
Everything else seems to be working except it still doesn't seem to show that the case is full when it has a artifact in it
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/c0bd3f97-60b4-41c2-8907-dc44750a603b)

**Comment by Regalis11** [comment]
Should be fixed now
