### ISSUE TITLE
Scavenger Talent doesn't increase buff duration

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#7105]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The Tier 2 talent for Specialist Security should increase buff duration by 50%, but actually gives a reduced buff amount (buff bar is not filled as much compared to another player without the talent). The buff duration is also not increased since the tick rate (amount of time it takes for you to see a visible buff reduction on the bar) is the same as someone without the talent.

**Steps To Reproduce**
Give captain and security 100 medical skill.
Give them each a tonic liquid and combat stimulant.
Time it and confirm.
Also try to give affliction through console and check if there's any difference.

**Version**
Latest unstable, Windows 10.

**Additional information**
https://user-images.githubusercontent.com/69410159/139575768-734c48a4-4743-48d4-b614-43b1213c6467.mp4

**Comment by M61Dev** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5215faee6f1ef7721e327b358d0552311a18bd5b

**Comment by Lithosagym** [comment]
Tested, the buff bar is still not full for the Scavenger character but the duration of the buff is indeed 50% longer, technically fixed, close if result is desirable.

**Comment by M61Dev** [comment]
The buff bar is a different length likely because the affliction gained is dependent on the character's maximum vitality. Security has more vitality so he gains less of the buff.

**Comment by Rokvach** [comment]
Closing
