### ISSUE TITLE
Crowbar variants added through talents do not speed up opening of doors

### ISSUE THREAD

**Issue by Marutzo** [Regalis11/Barotrauma#7356]
- [ X ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
Hardened and Dementonite Crowbars fail to force open doors quicker despite what their descriptions clearly state.
Quote:
**Hardened Crowbar - A crowbar that has gone through a process of hardening using depleted fuel. The strengthened material makes it easier to pry open doors and bash open heads**

I searched through the xml's for the relevant items and doors and noticed "forcing open" uses a picking time of 10 no matter what type of crowbar is used. Maybe add conditionals here with lower pick times for Hardened and Dementonite?

Compare with Hardened and Dementonite Screwdrivers and Wrenches which actually have a working repair upgrade in their xml:
addedrepairspeedmultiplier="0.25" and addedrepairspeedmultiplier="0.40" respectively.

Additionally regarding crowbars, they cannot force open doors that have been damaged or welded even the tiniest bit.

**Steps To Reproduce**
Part 1 - Forcing open doors:
1. Give yourself one of each crowbar and time yourself forcing open a door.
2. Spawn a welder and start welding shut the door just barely touching it with the welder beam for a split second.
3. Notice you cannot force open door before you remove the welds with a plasma cutter.
4. You also cannot force open door since it was damaged by step 3.
5. Repair door and you will be able to force it open.

Part 2 - Repair screen bug while trying to force open doors.
1. Spawn any crowbar, a plasma cutter, and a wrench (keep in inventory).
2. Damage the door, then equip the crowbar.
3. Try forcing open the door (notice crew member list disappears), but it won't let you.
4. Switch to the wrench and notice repair screen is already opened, which it shouldn't be.
5. Close the repair screen with right click and switch back to crowbar and try forcing it again. (notice repair screen flash)
6. Fully repair the door, then try forcing it open.. it still won't let you!
7. While equipped with crowbar still in front of the repaired door, right click, then try again. Success?
7b. Alternatively - Walk some distance away from the door and return, now you will be able to force it open.
(Theory, repair screen is stuck open somehow but invisible. which prevents the crowbar to proceed with its action)

**Version**
Latest Unstable, Windows 10.

**Additional information**

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/42b062a2e77f2a1c9807809bef1b523c68b650fa

**Comment by Lithosagym** [comment]
Tested, crowbar variants now have faster speed when opening doors, fixed. However, part 1 and part 2 as described still occur.

**Comment by Rokvach** [comment]
Moved to Team1

**Comment by Regalis11** [comment]
Fixed part 1 in https://github.com/Regalis11/Barotrauma-development/commit/6b88c0724e70da07424f42677c5d050f01cf52b4 and part 2 in https://github.com/Regalis11/Barotrauma-development/commit/aab0cf316dd8f6784a9a2ee7a90b59427943eb4d

**Comment by Rokvach** [comment]
Tested, working correctly. closing.
