### ISSUE TITLE
Game crashed when loading into a level (Object reference not set to an instance of an object: Boolean <Draw>b__133_1(FarseerPhysics.Dynamics.Body))

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#7604]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
I was testing events on the bugfixes branch and teleported from the first biome to the second one and my game just crashed before I was loaded in

**Steps To Reproduce**
I had debugdraw enabled with the event information shown, maybe that caused it? 

**Version**
0.15.17.0
Branch: bugfixes
Build: Release
Commit: https://github.com/Regalis11/Barotrauma-development/commit/8bc2d6674edd6916b049fcf00a1348fb08058740

**Additional information**
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/dde8008b-26d3-406f-91af-2d2fc3629774)

```
Barotrauma Client crash report (generated on 4.12.2021 12:59:20)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


76E644EE1C201A8A88093E8BF92A7EE1


Game version 0.15.17.0 (ReleaseWindows, branch feature/bugfixes, revision 8bc2d6674e)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9
Level seed: Merrivale LineaButterdon Linea
Loaded submarine: Dugong (BF39EE50929A5E1A74EE4A4E728F19EE)
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Object reference not set to an instance of an object. (System.NullReferenceException)
Target site: Boolean <Draw>b__133_1(FarseerPhysics.Dynamics.Body)
Stack trace: 
   at Barotrauma.GUI.<>c.<Draw>b__133_1(Body b) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 441
   at System.Collections.Generic.List`1.FindAll(Predicate`1 match)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 440
   at Barotrauma.RoundSummaryScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\RoundSummaryScreen.cs:line 55
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1012
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 367
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58


Last debug messages:
[4.12.2021 12:59:03] Generating an outpost for the end of the level... (Location: Butterdon Linea Mining Claim, level type: LocationConnection)
[4.12.2021 12:58:50] Transitioning to Merrivale LineaButterdon Linea (current location: Merrivale Linea, selected location: Butterdon Linea Mining Claim, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[4.12.2021 12:58:37] Start a new round to apply the upgrades.
[4.12.2021 12:58:37] Upgraded oxygengenerators.decreasepowerconsumption by 5 levels.
[4.12.2021 12:58:37] Upgraded oxygengenerators.increaseoxygengeneration by 5 levels.
[4.12.2021 12:58:37] Upgraded reactors.increasemeltdowndelay by 5 levels.
[4.12.2021 12:58:37] Upgraded reactors.decreasefuelconsumption by 10 levels.
[4.12.2021 12:58:37] Upgraded reactors.increasereactoroutput by 5 levels.
[4.12.2021 12:58:36] Upgraded engines.decreasepowerconsumption by 5 levels.
[4.12.2021 12:58:36] Upgraded engines.increaseenginemaxforce by 5 levels.
[4.12.2021 12:58:36] Upgraded weapons.turretincreaseoffsetonselected by 3 levels.
[4.12.2021 12:58:36] Upgraded weapons.turretincreaserotationlowskill by 5 levels.
[4.12.2021 12:58:36] Upgraded weapons.turretdecreasepowerconsumption by 5 levels.
[4.12.2021 12:58:36] Upgraded deconstructors.decreasepowerconsumption by 5 levels.
[4.12.2021 12:58:36] Upgraded deconstructors.decreasedeconstructiontime by 5 levels.
[4.12.2021 12:58:36] Upgraded fabricators.decreasepowerconsumption by 5 levels.
[4.12.2021 12:58:36] Upgraded fabricators.decreasefabricationskillrequirement by 5 levels.
[4.12.2021 12:58:36] Upgraded fabricators.increasefabricationspeed by 5 levels.
[4.12.2021 12:58:36] Upgraded batteries.increasebatteryrechargespeed by 5 levels.
[4.12.2021 12:58:36] Upgraded batteries.increasebatterycapacity by 5 levels.
[4.12.2021 12:58:36] Upgraded supercapacitors.increasebatteryrechargespeed by 5 levels.
[4.12.2021 12:58:36] Upgraded supercapacitors.increasesupercapacitorcapacity by 5 levels.
[4.12.2021 12:58:36] Upgraded pumps.decreasepowerconsumption by 5 levels.
[4.12.2021 12:58:36] Upgraded pumps.increasemaxpumpflow by 5 levels.
[4.12.2021 12:58:36] Upgraded junctionboxes.increaseovervoltageresistance by 5 levels.
[4.12.2021 12:58:36] Upgraded junctionboxes.decreasefireprobability by 5 levels.
[4.12.2021 12:58:36] Upgraded mechanicaldevices.decreaserequiredskilllevel by 5 levels.
[4.12.2021 12:58:36] Upgraded mechanicaldevices.decreaselowskillfixduration by 5 levels.
[4.12.2021 12:58:36] Upgraded mechanicaldevices.decreasedeteriorationspeed by 10 levels.
[4.12.2021 12:58:36] Upgraded electricaldevices.decreaserequiredskilllevel by 5 levels.
[4.12.2021 12:58:36] Upgraded electricaldevices.decreaselowskillfixduration by 5 levels.
[4.12.2021 12:58:36] Upgraded electricaldevices.decreasedeteriorationspeed by 10 levels.
[4.12.2021 12:58:36] Upgraded walls.increasewallhealth by 10 levels.
[4.12.2021 12:58:36] maxupgrades
[4.12.2021 12:58:33] Enabled teleportation on the campaign map.
[4.12.2021 12:58:33] togglecampaignteleport
[4.12.2021 12:58:14] Generating an outpost for the start of the level... (Location: Dank Station, level type: Outpost)
[4.12.2021 12:58:03] Transitioning to Dank (current location: Erlangshen Station, selected location: Dank Station, leaving sub: Dugong, at start: False, at end: True, transition type: ProgressToNextLocation)
[4.12.2021 12:57:17] skipeventcooldown
[4.12.2021 12:57:07] skipeventcooldown
[4.12.2021 12:55:06] skipeventcooldown
[4.12.2021 12:55:05] skipeventcooldown
[4.12.2021 12:55:00] skipeventcooldown
[4.12.2021 12:54:10] spawncharacter "Medical Doctor" cursor
[4.12.2021 12:54:06] spawncharacter Engineer cursor
[4.12.2021 12:53:59] spawncharacter "Security Officer" cursor
[4.12.2021 12:50:08] Godmode on
[4.12.2021 12:50:08] godmode_mainsub
[4.12.2021 12:50:01] fixwalls
[4.12.2021 12:49:51] fixwalls
[4.12.2021 12:46:45] skipeventcooldown
[4.12.2021 12:46:37] Debug draw mode enabled
[4.12.2021 12:46:37] debugdraw
[4.12.2021 12:46:35] Steam achievements have been disabled during this play session.
[4.12.2021 12:46:35] Enabled cheat commands.
[4.12.2021 12:46:35] enablecheats
[4.12.2021 12:46:17] Generating an outpost for the start of the level... (Location: Dank Station, level type: LocationConnection)
[4.12.2021 12:46:16] Generating an outpost for the end of the level... (Location: Erlangshen Station, level type: LocationConnection)
[4.12.2021 12:46:00] Transitioning to DankErlangshen (current location: Erlangshen Station, selected location: Dank Station, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[4.12.2021 12:45:32] Generating an outpost for the start of the level... (Location: Erlangshen Station, level type: Outpost)
[4.12.2021 12:45:16] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[4.12.2021 12:45:16] (Msg) Ping location: sto=14+1,sto2=14+1,ams=38+3/34+1,waw=41+4/34+1,lhr=45+4/38+1,fra=41+4/40+1,par=54+5/42+1,vie=52+5/45+1,mad=62+6/65+1,iad=119+11/123+1,sgp=199+19/200+19,gru=228+22
[4.12.2021 12:45:16] (Msg) Ping measurement completed
[4.12.2021 12:45:15] (Verbose) Communications with routing cluster 'par' established.
[4.12.2021 12:45:15] (Debug) Destroying relay 'par#161 (185.25.182.68:27067)' because initial_ping_timeout
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'seo' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'tyo1' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'syd' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'tyo' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'sgp' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'scl' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'lim' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'jnb' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'maa' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'sea' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'dxb' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'lax' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'eze' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'vie' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'waw' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'ord' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'gru' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'hkg' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'sto' established.
[4.12.2021 12:45:13] (Verbose) Communications with routing cluster 'sto2' established.
[4.12.2021 12:45:12] (Verbose) Communications with routing cluster 'mad' established.
[4.12.2021 12:45:12] (Verbose) Communications with routing cluster 'bom' established.
[4.12.2021 12:45:12] (Verbose) Communications with routing cluster 'lhr' established.
[4.12.2021 12:45:12] (Verbose) Communications with routing cluster 'dfw' established.
[4.12.2021 12:45:12] (Verbose) Communications with routing cluster 'atl' established.
[4.12.2021 12:45:12] (Verbose) Communications with routing cluster 'iad' established.
[4.12.2021 12:45:12] (Verbose) Communications with routing cluster 'fra' established.
[4.12.2021 12:45:12] (Verbose) Communications with routing cluster 'ams' established.
[4.12.2021 12:45:12] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[4.12.2021 12:45:12] (Msg) Performing ping measurement
[4.12.2021 12:45:12] (Msg) Got SDR network config.  Loaded revision 354 OK
[4.12.2021 12:45:12] (Warning) SDR network config fetch first attempt failed.  HTTP 504.  .  Trying again.
[4.12.2021 12:44:58] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
[4.12.2021 12:44:57] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[4.12.2021 12:44:56] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4b109a766f3906f2f48c0c3113fc4375a26b3c57

**Comment by Rokvach** [comment]
I was still able to crash the game this way, the crash report doesn't seem to be the exact same however

Repro steps:
1. Load up singleplayer
2. Use commands debugdraw, maxupgrades and togglecampaignteleport
3. Use Ctrl + E to show event data on the oupost
4. Open campaign map and teleport to a outpost on the next biome over and press start
5. Hover you mouse over the event graph so its not minimized
6. Game should crash during loading to the next round

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/398df76c-390d-426c-bd79-ed034880df66)
```
Barotrauma Client crash report (generated on 5.12.2021 23:40:42)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


78A35D4CB62D6BD613E1E2039AE13351


Game version 0.15.18.0 (ReleaseWindows, branch feature/bugfixes, revision cde539af02)
Graphics mode: 2560x1440 (BorderlessWindowed)
VSync OFF
Language: English
Selected content packages: Vanilla 0.9
Level seed: Binnsmouth
Loaded submarine: None
Selected screen: Barotrauma.RoundSummaryScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.18363.0 64 bit
    GPU name: NVIDIA GeForce GTX 980 Ti
    Display mode: {Width:2560 Height:1440 Format:Color AspectRatio:1,7777778}
    GPU status: Normal


Exception: Collection was modified; enumeration operation may not execute. (System.InvalidOperationException)
Target site: Void ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
Stack trace: 
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source, Func`2 predicate)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 440
   at Barotrauma.RoundSummaryScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\RoundSummaryScreen.cs:line 50
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 1017
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 59


Last debug messages:
[5.12.2021 23:40:37] Transitioning to AlkonostAutonoe Linea (current location: Autonoe Linea Mine, selected location: Alkonost Habitation Outpost, leaving sub: Dugong, at start: True, at end: False, transition type: LeaveLocation)
[5.12.2021 23:40:26] Enabled teleportation on the campaign map.
[5.12.2021 23:40:26] togglecampaignteleport
[5.12.2021 23:40:24] Start a new round to apply the upgrades.
[5.12.2021 23:40:24] Upgraded oxygengenerators.decreasepowerconsumption by 5 levels.
[5.12.2021 23:40:24] Upgraded oxygengenerators.increaseoxygengeneration by 5 levels.
[5.12.2021 23:40:24] Upgraded reactors.increasemeltdowndelay by 5 levels.
[5.12.2021 23:40:24] Upgraded reactors.decreasefuelconsumption by 10 levels.
[5.12.2021 23:40:24] Upgraded reactors.increasereactoroutput by 5 levels.
[5.12.2021 23:40:24] Upgraded engines.decreasepowerconsumption by 5 levels.
[5.12.2021 23:40:24] Upgraded engines.increaseenginemaxforce by 5 levels.
[5.12.2021 23:40:24] Upgraded weapons.turretincreaseoffsetonselected by 3 levels.
[5.12.2021 23:40:24] Upgraded weapons.turretincreaserotationlowskill by 5 levels.
[5.12.2021 23:40:24] Upgraded weapons.turretdecreasepowerconsumption by 5 levels.
[5.12.2021 23:40:24] Upgraded deconstructors.decreasepowerconsumption by 5 levels.
[5.12.2021 23:40:24] Upgraded deconstructors.decreasedeconstructiontime by 5 levels.
[5.12.2021 23:40:24] Upgraded fabricators.decreasepowerconsumption by 5 levels.
[5.12.2021 23:40:24] Upgraded fabricators.decreasefabricationskillrequirement by 5 levels.
[5.12.2021 23:40:24] Upgraded fabricators.increasefabricationspeed by 5 levels.
[5.12.2021 23:40:24] Upgraded batteries.increasebatteryrechargespeed by 5 levels.
[5.12.2021 23:40:24] Upgraded batteries.increasebatterycapacity by 5 levels.
[5.12.2021 23:40:24] Upgraded supercapacitors.increasebatteryrechargespeed by 5 levels.
[5.12.2021 23:40:24] Upgraded supercapacitors.increasesupercapacitorcapacity by 5 levels.
[5.12.2021 23:40:24] Upgraded pumps.decreasepowerconsumption by 5 levels.
[5.12.2021 23:40:24] Upgraded pumps.increasemaxpumpflow by 5 levels.
[5.12.2021 23:40:24] Upgraded junctionboxes.increaseovervoltageresistance by 5 levels.
[5.12.2021 23:40:24] Upgraded junctionboxes.decreasefireprobability by 5 levels.
[5.12.2021 23:40:24] Upgraded mechanicaldevices.decreaserequiredskilllevel by 5 levels.
[5.12.2021 23:40:24] Upgraded mechanicaldevices.decreaselowskillfixduration by 5 levels.
[5.12.2021 23:40:23] Upgraded mechanicaldevices.decreasedeteriorationspeed by 10 levels.
[5.12.2021 23:40:23] Upgraded electricaldevices.decreaserequiredskilllevel by 5 levels.
[5.12.2021 23:40:23] Upgraded electricaldevices.decreaselowskillfixduration by 5 levels.
[5.12.2021 23:40:23] Upgraded electricaldevices.decreasedeteriorationspeed by 10 levels.
[5.12.2021 23:40:23] Upgraded walls.increasewallhealth by 10 levels.
[5.12.2021 23:40:23] maxupgrades
[5.12.2021 23:40:08] Debug draw mode enabled
[5.12.2021 23:40:08] debugdraw
[5.12.2021 23:40:08] Steam achievements have been disabled during this play session.
[5.12.2021 23:40:08] Enabled cheat commands.
[5.12.2021 23:40:08] enablecheats
[5.12.2021 23:40:06] Enabling cheats will disable Steam achievements during this play session.
[5.12.2021 23:40:06] You need to enable cheats using the command "enablecheats" before you can use the command "debugdraw".
[5.12.2021 23:40:06] debugdraw
[5.12.2021 23:39:43] Generating an outpost for the start of the level... (Location: Binnsmouth Station, level type: Outpost)
[5.12.2021 23:39:20] (Msg) SDR RelayNetworkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)
[5.12.2021 23:39:20] (Msg) Ping location: sto2=13+1,sto=14+1/13+1,ams=38+3/33+1,waw=41+4/33+1,lhr=45+4/37+1,fra=45+4/40+1,par=53+5/44+1,vie=52+5/45+1,mad=65+6/64+1,iad=117+11/120+1,sgp=198+19/199+19,gru=229+22
[5.12.2021 23:39:20] (Msg) Ping measurement completed
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'seo' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'tyo1' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'syd' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'tyo' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'sgp' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'scl' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'lim' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'jnb' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'maa' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'dxb' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'sea' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'lax' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'eze' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'vie' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'waw' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'hkg' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'ord' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'gru' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'sto2' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'sto' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'mad' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'bom' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'par' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'lhr' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'dfw' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'atl' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'iad' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'fra' established.
[5.12.2021 23:39:17] (Verbose) Communications with routing cluster 'ams' established.
[5.12.2021 23:39:16] (Msg) SDR RelayNetworkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
[5.12.2021 23:39:16] (Msg) Performing ping measurement
[5.12.2021 23:39:16] (Msg) Got SDR network config.  Loaded revision 354 OK
[5.12.2021 23:39:03] Attempting to open ALC device "OpenAL Soft on Kaiuttimet (Realtek High Definition Audio)"
[5.12.2021 23:39:03] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
[5.12.2021 23:39:02] Loaded languages: English, German, French, Russian, Polish, Brazilian Portuguese, Castilian Spanish, Latinamerican Spanish, Simplified Chinese, Traditional Chinese, Japanese, Turkish, Korean
```

**Comment by itchyOwl** [comment]
Still crashes. I don't see why though: neither FindAll nor Count should modify the collection.

**Comment by Regalis11** [comment]
> Count shouldn't modify the collection

The issue here is that it's being modified from another thread.

**Comment by Regalis11** [comment]
2nd attempt: https://github.com/Regalis11/Barotrauma-development/commit/db8bd7e2a98a5b739ebe85c98b7a0e9f1a942539

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
