### ISSUE TITLE
Deconstructor doesn't put outputted materials into containers contained inside containers

### ISSUE THREAD

**Issue by BlueTheKing** [Regalis11/Barotrauma#7699]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The deconstructor doesn't put any outputted materials into containers, if all output slots are occupied and the items can't be stacked they are dropped on the ground.

**Version**
Unstable 0.15.19.0

**Comment by Regalis11** [comment]
I'm not entirely sure what you mean, containers linked to the deconstructor or items like toolbelts in the deconstructor's output slot?

**Comment by BlueTheKing** [comment]
Containers that are stored in the deconstructor, like crates, storage containers, duffel bags etc.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/66424215a33df9a1236ed3914126fd80e89e9017

**Comment by Rokvach** [comment]
Now the partials not being combined issue is back
![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/afec9f74-ece9-4469-b5a4-a040770e9c15)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b1c7ad3aff3851de428ae4c10e9c16465d80cea2 (I hope!)

**Comment by Rokvach** [comment]
Partials are now combining correctly

I did notice that items stored inside other items, like batteries in stun baton doesn't go into the crate as well as items that can't normally be deconstructed but does go through the deconstructor if you have them with items that does deconstruct doesn't go into crates either, the latter might be fine but I think it would be good to have stored items go into the crates too. 

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/2c9db952-8410-4a6d-8802-9682fdd42ca9)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/0036be310856c92c5df81e6051e70573dedf4ca8

**Comment by Rokvach** [comment]
I decided to test this with nested containers too (Metal crate filled with toolbelts) and both of the above pointed issues happens with that configuration still

**Comment by Rokvach** [comment]
Moving to team 1 as I think the nested containers should work the same way
