### ISSUE TITLE
Bots shoot at the friendlies when they try to kill Swarmfeeders attached to them

### ISSUE THREAD

**Issue by itchyOwl** [Regalis11/Barotrauma#8095]
Need to do something to it. Ignore the targets that have latched on someone else than self?

**Comment by danielasteljoki** [comment]
I don't think there's any way around this except prevent them from shooting, which is a shame. How do melee attacks work with latching? Do they automatically hit the latched thing or does it depend on the hit location?

**Comment by itchyOwl** [comment]
I think melee weapons hit all the targets they hit. In any case. it's not a solution, unless FF is disabled.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@5439185. There's also a number of related fixes and improvements there:

- Fix bots not reacting to monsters when being attacked outside of the sub.
- Fix issues with spotting the enemies outside of the sub.
- Fix bots being able to shoot without any delay when they already have a weapon equipped.
- Reduce the enemy spotting distance outside of the sub (it's dark and the vision is hindered by the suit afterall)

**Comment by Rokvach** [comment]
This doesn't seem to fix the issue of bots attacking friendlies when a swarmfeeder is latched on them, is this intentional? 

I did notice that the bot only reacts to a enemy after they have been attacked once by that enemy while being outside the sub, but that might be because of the spotting distance? As this only happens when I spawn a enemy behind the bot

When a bot is attacking with a melee weapon they don't rotate to face the enemy, tested by being outside the sub and spawning a swarmfeeder behind the bot, they keep facing and even attacking the same direction even though they would get a better hit at the enemy if they rotated to face it.

**Comment by itchyOwl** [comment]
> This doesn't seem to fix the issue of bots attacking friendlies when a swarmfeeder is latched on them, is this intentional?

Do you mean that the bots accidentally attack friendlies when trying to get rid of swarmfeeders latched _on themselves_ or are they accidentally attacking other while trying to attack the swarmfeeders latched _on another friendly character_? The latter was addressed: the bots shouldn't try to attack swarmfeeders attached to other characters.

> I did notice that the bot only reacts to a enemy after they have been attacked once by that enemy while being outside the sub, but that might be because of the spotting distance? As this only happens when I spawn a enemy behind the bot

They can't see behind them. They should be able to spot monsters that should be visible from their perspective though.

> When a bot is attacking with a melee weapon they don't rotate to face the enemy, tested by being outside the sub and spawning a swarmfeeder behind the bot, they keep facing and even attacking the same direction even though they would get a better hit at the enemy if they rotated to face it.

Something to look into. Maybe create a separete issue so that we'll remember to fix it?

**Comment by Rokvach** [comment]
> the bots shouldn't try to attack swarmfeeders attached to other characters.
This still happens, they just start shooting at you trying to kill the swarmfeeders that are attached. Wasn't able to get them not to shoot at me.

**Comment by itchyOwl** [comment]
It seems the previous fix wasn't enough. Maybe now: Regalis11/Barotrauma-development@7cd77e7.
