### ISSUE TITLE
[Unstable 0.17.7.0] If a round starts while you are still joining a server it doesn't show the spectate button on lobby

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#8744]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While you are in the process of downloading mods from a server and a round is started during that time you willl only see the "Start" button on the lobby instead of the "Spectate" button

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/b6eeb3cb-9ece-4836-989f-6e0eed803259)

**Steps To Reproduce**
Join a modded server and have the host start the round while you are in the middle of downloading mods

**Version**
Unstable 0.17.7.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/b281807d93a1b629d481f2e7c9b1e196b44c3343

**Comment by Rokvach** [comment]
This still happens in Unstable 0.17.8.0, doesn't let you join the round no matter what you do as pressing the Start button just tries to launch a round but as the round has already started the process just fails and you are just stuck on the lobby.

**Comment by Regalis11** [comment]
2nd attempt https://github.com/Regalis11/Barotrauma-development/commit/1e8e876a6c5a03cb44ab218744ff9f0b5c4bcb80

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
