### ISSUE TITLE
[Unstable v17.x] Scooter turns players belly-up. No way to roll around?

### ISSUE THREAD

**Issue by CurePindal** [Regalis11/Barotrauma#8857]
- [x ] I have searched the issue tracker to check if the issue has already been reported.

**Description**
When youre diveing and turn around with the scooter it starts to pull you around belly-up with no way to get your belly back down. This is somwhat wrong and confusing (and it also looks very stupid)

Expected: A kind of autoroll into a proper horizontal position (as it was in pre 0.17.x versions). Or at least a manual way to roll your model around. Its important in the dark.

**Steps To Reproduce**
- dive with a scooter horizontally
- turn 180deg into the other horizontal direction and your model is now (and stays) belly up instead of back up.

**Version**
Tested with .17.11 & .17.12. Seems to be the case in all 0.17.x versions?!

![20220420135907_1](https://user-images.githubusercontent.com/3466193/164226118-610a7233-a17e-4cba-9005-f3725f38bf86.jpg)

**Comment by itchyOwl** [comment]
Didn't intentionally change how it worked, so it's a bug.

**Comment by itchyOwl** [comment]
Fixed in Regali11/Barotrauma-development@2fcd518.

**Comment by Rokvach** [comment]
This seems to have caused some strange behavior, moving to Team2
https://www.youtube.com/watch?v=1NcswoRpumo

**Comment by itchyOwl** [comment]
Seems to be an old issue. Just tested a couple of different builds predating the changes, of which the latest was 0.10.6.2. The issue is present in all of them, although it's a bit more noticeable with the new characters we added last summer. Looking into it nevertheless.

**Comment by itchyOwl** [comment]
Fixed in Regalis11/Barotrauma-development@be4a039, which also changes the behavior slightly: you can now slow down.

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by CurePindal** [comment]
This is still a problem. You still stay belly-up and dont even turn around when you stop and move on.

Re-open and fix, plz.
