### ISSUE TITLE
Right-click functionality no longer works in crew tab menu.

### ISSUE THREAD

**Issue by Ek-Videogames** [Regalis11/Barotrauma#8869]
**Description**
Right clicking a person's name in the TAB menu does not properly open the options for steam profile, mute, kick/ban, etc.

### Edit:
To reproduce, this seems to only occur when joining a round in progress. If joined and then a round started it works fine.

**Comment by Regalis11** [comment]
Probably fixed in https://github.com/Regalis11/Barotrauma-development/commit/b7507c4f9b3b769178bbfc6e4e04fe1f145307b1, although I'm not sure if I understood the issue correctly. It seems that I couldn't use the context menu on clients who aren't controlling a character (e.g. clients who are in the lobby or spectating), but it worked the other way around (using it on spectators when I'm controlling a character).

**Comment by Rokvach** [comment]
This could also be related to this issue which still happens sometimes during the start of a round and can take a moment to fix itself and while it is messed up you can't right click any of the crew members

https://github.com/Regalis11/Barotrauma/issues/2961

**Comment by Rokvach** [comment]
Tested, working correctly, closing.
