### ISSUE TITLE
Disconnecting an engine while in use can prevent it from working until broken and fixed again

### ISSUE THREAD

**Issue by Zangdorx** [Regalis11/Barotrauma#8873]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
While in a campaign mission, we unplugged the power input to the motor. When we plugged it back later on, it would refuse to move. The cursor would move correctly depending on the velocity set in the control station. The bubble animation would happen. It would consume power as indicated in the junction box powering it. But the submarine velocity would be stuck at zero km/h.

Plugging and unplugging both the power cable and the control cable did not fix the problem.
Blowing it up using a grenade and then fixing it using a wrench fixed the problem.

**Steps To Reproduce**
Hopefully:
1. Start a campaign
2. Move the submarine
3. Unplug the power to the motor while it moves
4. Wait (maybe)
5. Plug back the power to the motor
6. Set a non-zero velocity in X at the control station
7. See the submarine not gaining any speed

**Version**
v0.17.12.0 on Windows

**Additional information**
The submarine used is a modified version of the Azimuth, here:
[Neo-Azimuth.txt](https://github.com/Regalis11/Barotrauma/files/8526838/Neo-Azimuth.txt)
I changed the extension from `.sub` to `.txt` to be able to add it to the issue.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/f762dbb24bc98d5c964eccb9a6e08e8edabb8270

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.

**Comment by Krisisis** [comment]
This is still an issue, happened to me yesterday the 25. April. #8976

**Comment by Regalis11** [comment]
The fix is not yet out in the public version, but we're trying to release a hotfix soon. Sorry for the inconvenience!

**Comment by mygamingaccount** [comment]
Griefers have found out about this issue.

@Regalis11 I demand you release a fix for this ASAP!
