### ISSUE TITLE
Crash when trying to spawn items for an NPC with no items configured in xml

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#8887]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
The game crashes when trying to spawn an instance of a human prefab that has no item sets configured.

**Steps To Reproduce**
1. Remove item sets from the corpse prefabs in Corpses.xml (or use a mod that includes human prefabs with no items?)
2. Load a level with wrecks (and corpses) in it
3. Crash

**Version**
v0.17.12.0

**Additional information**
https://steamcommunity.com/app/602960/discussions/1/3274689286952848395/

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/53e281108ba9ea12e24f1aa065004154975a7278

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue with the provided steps, working correctly. Closing.

**Comment by aring99** [comment]
Greetings,
The issue was still occuring for me today until trying the development in the discussion forum. Changing my windows/computer region from Turkey to US fixed this issue. Changed it using Select Start > Settings > Time & Language > Language & Region. I don't know why this solution works.

Thank you very much for all your efforts and take care,

**Comment by Regalis11** [comment]
@aring99 Thank you for the extra info! That seemed to be the issue: we were doing some string comparisons using the system language, which prevented ItemSets (which define what items an NPC spawns with) from getting loaded when using Turkish because the game was trying to find _ıtemsets_ (with a dotless i) from the config files.

Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/3d62336e30ce8d57b02b38641738758237935c74

**Comment by Rokvach** [comment]
Tested, wasn't able to reproduce the issue, seems to be working correctly. Closing.

**Comment by Varangianoi** [comment]
The bug for Itemset loading(?) is there for the Turkish players, the NPCS and bandits spawn without anything. It's only fixed in the unstable version.

Related: https://github.com/Regalis11/Barotrauma/issues/9138
![Screenshot_3](https://user-images.githubusercontent.com/75825361/169526713-a56f290f-6ef4-458e-80b1-37e17b393705.png)
