### ISSUE TITLE
Terminal welcome message displaying and wrapping problem

### ISSUE THREAD

**Issue by nokau** [Regalis11/Barotrauma#8924]
- [x] I have searched the issue tracker to check if the issue has already been reported.

**Description**
- While English texts seem to be the least affected, the languages I tested, Traditional Chinese and Japanese, seem to fail to wrap within the terminal UI, which might apply to more languages.
- The terminal UI will cut off the top and the bottom of a lengthy, multiple-lined message. It worsens when using non-English texts, or when the game's resolution is set lower, in this case from 1920x1080 to 1600x900 (windowed).

**Steps To Reproduce**
1. In Submarine Editor, select a long terminal welcome message, then switch the game's language.
2. In Submarine Editor, create/select a long, multiple-line terminal welcome message that enables terminal UI's scrolling, then change the game's resolution from 1920x1080 to 1600x900 (windowed).

**Version**
v0.17.12.0, Windows

**Additional information**
1. The same vanilla message, but with different languages. The Japanese version failed to wrap and goes beyond the right side of the UI.
![2022-04-23 071312-1](https://user-images.githubusercontent.com/39273494/164836744-f65549d4-818c-4e4e-b8e7-b7241014720d.jpg)
2. A lengthy, multiple-line message I put together. The top and bottom texts get cut off when the game's resolution is set from 1920x1080 to 1600x900. The cut-offs existed pre-v0.17.12.0 and were worse if using non-English texts even at 1920x1080.
![2022-04-23 071312-2](https://user-images.githubusercontent.com/39273494/164836760-ae1444db-3233-4a09-8205-b006dabd5684.jpg)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/5ca7ffb33b2da9a5ae791e69d8c15388944e023a

**Comment by Rokvach** [comment]
There's something still wrong in the rendering of the terminal text, the first line is cut for me and it seems to depend on the resolution as to how much there's space at the very top of the message

Lowest resolution after restarting the game
![image](https://user-images.githubusercontent.com/7299826/172085534-841ab4e7-a538-4aa6-b1dd-d9aab0661cb6.png)

Switching from lowest resolution to highest 1440p, without restarting the game
![image](https://user-images.githubusercontent.com/7299826/172085891-0571a1c9-314d-4109-9519-c21d1f9821a0.png)

Restarted game after the above change and now on 1440p
![image](https://user-images.githubusercontent.com/7299826/172086101-5c0d293f-26c4-49be-975f-09ef26d3fa16.png)

Changed resolution to the lowest without restarting
![image](https://user-images.githubusercontent.com/7299826/172086233-4b6f09ce-c6ae-4557-bb52-f104869f1e91.png)

**Comment by Rokvach** [comment]
Tested, didn't spot any issues, can be closed if nothing is found in review relating to this
