### ISSUE TITLE
Catastrophic drop in performance

### ISSUE THREAD

**Issue by PiatraAlatyr** [Regalis11/Barotrauma#8961]
I have a fairly powerful hardware and have never had such problems in the game. Right after the Urban Expanses update, my save performance dropped dramatically. Perhaps it has something to do with the number of items or logic / wires on the submarine. On other saves and in multiplayer, this problem almost never occurred.

-Low FPS (around 5)
-Mouse cursor moves jerkily
-Character not responding to key presses, then executing command backlog (generally walking into a wall for several seconds)
-Hovering over clickables doesn't create usual selection windows
-Audio is totally unaffected
-There is no problem with pause, fps becomes around 100
![image](https://user-images.githubusercontent.com/36773134/165002697-ef902ae4-ca1e-48e8-84e1-6265cacf06c6.png)

**Comment by PiatraAlatyr** [comment]
[Сохранение 1.zip](https://github.com/Regalis11/Barotrauma/files/8553944/1.zip)

**Comment by PiatraAlatyr** [comment]
If you don’t reproduce the problem on my save, then this is something obviously interesting.

**Comment by JoneKone** [comment]
My PC setup:
Vega 56 (irrelevant on this game)
32 gb RAM (2133Mhz while recording the video)
AMD Ryzen 5600x (Stock)
NVME
Ubuntu 21.10

https://www.youtube.com/watch?v=O7v8twy3BaM
![Screenshot from 2022-04-25 23-04-33](https://user-images.githubusercontent.com/1114115/165169402-a6357bdf-2f5b-49f4-b8b8-3599307823e2.png)
![Screenshot from 2022-04-25 23-04-37](https://user-images.githubusercontent.com/1114115/165169419-0a0258fe-0588-40f6-80c9-016932713ed3.png)

**Comment by Chotat0** [comment]
Same problem here, but this issue has been present for the last 2-3 content updates as opposed to being introduced in the newest update. Prior to whichever update caused the lag issue, the game ran at a consistent 144 dropping into the 60s during intense combat and sometimes 30 depending on the size of the sub.

My issue prior to this update caused the FPS to decrease to less than 60 at all times, usually 40-50 and then once the sub gets a single leak the FPS tanks to below 5 and doesn't return even if combat ceases and the sub is drained entirely. I have some screenshots of the console log I'll be posting, just keep in mind these are from the last version of the game, not the current. I'll be attempting to get more current screenshots, assuming the game even runs at all anymore. Issue is present on all subs, no matter the size or player count. Even running the game solo with no bots doesn't improve performance at all.

![image](https://user-images.githubusercontent.com/93625008/165196249-ad1441e2-a4e3-49b7-ac79-62d37dfb9217.png)

**Comment by PiatraAlatyr** [comment]
I found a similar case in the bug tracker. Probably the problem is not new and gradually worsens with each update.
https://github.com/Regalis11/Barotrauma/issues/8510

**Comment by PiatraAlatyr** [comment]
v0.17.15.0 The problem is still there. I noticed that even loading my save takes a suspiciously long time and looks like it freezes.

**Comment by PiatraAlatyr** [comment]
@Regalis11 Can you mark the problem a high priority and investigate it? The case is far from rare and the discussion in Steam support is quite active. https://steamcommunity.com/app/602960/discussions/1/3274689919151838410/
https://steamcommunity.com/app/602960/discussions/1/3274689286964669679/

**Comment by PiatraAlatyr** [comment]
I tried docking and sailing away with no missions. My fps went up to 30 but sometimes dropped back to 5 with all the issues like poor responsiveness returning. Maybe a problem with rendering the environment? However, this is strange, since neither the processor nor the video card is loaded.

**Comment by Galaxies12** [comment]
I've already talked about this in this Steam discussion: https://steamcommunity.com/app/602960/discussions/1/3274689919151838410/

As multiple people have said in there and in this board, there've been a slew of issues. A few are below:
- Intense lag, only around 5fps - 20fps for most people. For a few, this only occurs when in combat, when fighting enemy creatures.
- Input lag. When you hold 'wasd' it takes from .5 seconds to 6 seconds to move your character. For me, it takes over 20 seconds of spamming the F3 button to open the menu, and roughly that same time to hit enter (or to type anything really). Before anyone asks, yes, I did try multiple times to hit the button once and wait.
- STARTGAME errors and missing item errors. This has been a major issue for a long time, not just since Rising Tide. So many people have been plagued by this.


**Roughly** 1/3 - 1/4 of the playerbase has been afflicted by above, with no way of fixing it. It is not a client-side issue, too many people with thousand dollar plus PCs have been experiencing too much lag. As Alatyr has said, MapEntityUpdate is usually a big issue.

I personally have a 4k PC, and get usually 5fps to 20fps. There's also major input lag. This is not an issue on any other game.

If there's anything wrong here or anyone has questions, feel free to contact me over Discord, Steam, Github, or this board.
Discord: Galaxies#6458

**Comment by Regalis11** [comment]
Thank you for all the information on these performance issues! We are indeed investigating the performance issues, and actually already have some optimizations lined up for the next release. These won't fully solve the problems, but address some specific things that were causing heavy lag spikes (for example, AI pathfinding in colonies and the watcher's acid mist).

What makes these problems hard to address is that we still haven't been able to find a clear cause to them, and in fact it could even be that there isn't a clear cause: there's just so much more content and stuff for the CPU to calculate in the game nowadays, that all of it adds up to so much load that it can kill the performance on some systems. We've also been adding new content at quite a fast pace, possibly too fast to the point that we haven't had the time to optimize all of it thoroughly enough. That being said, it's still something we're constantly working on, measuring the game's performance and gradually improving all the small parts that add to the performance usage.

Based on the reports and screenshots of the performance overlay we've gotten, it does seem that there is no single clear cause to the problems, but it appears to be caused by item and character updates taking a long time in total.

It could be that the issues become more severe when using mods or custom subs, or at later stages of the campaign when there's more items and characters around in the sub. If anyone happens to notice that the problems tend to appear when using certain mods or subs, please let us know so we can give those a test and see if there's some specific things causing problems there. Or if you have a campaign save file where the problems are especially severe, sending it to us might also help us. It'd also be useful to know if there's any difference in performance between multiplayer and singleplayer - does the input lag for example occur in both, or just multiplayer?

**Comment by PiatraAlatyr** [comment]
The problem is also reproduced in multiplayer, but it is not as stable. Maybe I just haven’t met companies that are too loaded with items, but with a large number of players and monsters, the game starts to choke and the FPS also drops to 5.
I still don't know where the bottleneck is as the game doesn't use the full power of my PC. The processor is not even close to 100% loaded, as is the video card with RAM.
Thank you for responding to the issue so quickly. We are waiting for the unstable version to confirm that the current efforts to fix the problem really work.

**Comment by Regalis11** [comment]
> I still don't know where the bottleneck is as the game doesn't use the full power of my PC. The processor is not even close to 100% loaded, as is the video card with RAM.

The bottleneck could still be the CPU, since the game can't fully utilize all of the processor cores at the same time. Or to put it in other words, most of the heaviest calculations (physics and item updates) run in a single thread, so the game can get bottlenecked by single-core performance.

This is something where we've also got room for more optimization, but only to a degree. Some things, like the item updates in which the items can affect other items, are very difficult to multithread, and it's likely that the added complexity of coordinating multithreaded item updates would offset any potential performance benefits.

**Comment by BlackMoons** [comment]
A performance enhancing mod staggers item updates to once every N frames. Maybe something like that could be done in vanilla? Like only calculating all the logic/AI movement at 20FPS or 30FPS and using interpolation to smooth the movement to the actual frame rate?

**Comment by ajmcateer** [comment]
[Save 7.zip](https://github.com/Regalis11/Barotrauma/files/8720221/Save.7.zip)

I have a good save to test with I don't know if the save has a mod list but i can get one if you need. I have 3 missions selected and a large crew performance hovers around 60fps when just walking around the sub. but when I go into the level a bit and some baby molochs spawn fps plummets to 5 ish. I was monitoring my CPU usage and no one core gets maxed out. Once a large wave of crawlers spawn that's it. The game is unplayable.

AMD R9 5900x
32GB DDR4 3200mhz ram
EVGA FTW3 3080

**Comment by PiatraAlatyr** [comment]
0.18.2.0 Still have input lag and low fps. Perhaps the fps has risen a little and the lags have become a little less.
![image](https://user-images.githubusercontent.com/36773134/169342663-a9702bdb-b678-4f1d-b848-c27acb188f6f.png)

**Comment by Regalis11** [comment]
Thank you for the extra info! 

I've now found a couple of other things that cause an unnecessary performance hit: namely, certain types of items that spawn other items inside them (like fuel rods that can be used as ammo for the rapid fissile accelerator, and certain combinations of talents). Looking at that screenshot and the provided save, those could contribute to the performance problems your having (although they're not enough to alone cause them). In any case, we've got a fix for those coming up, possibly even in the next unstable.

I also did some testing with the save @ajmcateer provided, and it seems that some of the mods you're using are extremely heavy for performance. Here's a list of the items that take the most time to update in that save:

```
Diving Grenade: 100897491
Military Mk-II Hardsuit: 112818
Railgun Piercing Halfshells: 22052
Alien Power Cell: 21174
Railgun Halfshells: 17227
5.7x28mm Magazine: 14331
Relay Component: 11868
SMG Magazine: 10886
Motion Detector: 9791
Grenade Launcher: 7630
Junction Box: 7339
Fuel Rod: 7286
```

So diving grenades are a whopping x1000 times heavier to update than the other top ten heaviest items _combined_.

**Comment by PiatraAlatyr** [comment]
> Thank you for the extra info!
> 
> I've now found a couple of other things that cause an unnecessary performance hit: namely, certain types of items that spawn other items inside them (like fuel rods that can be used as ammo for the rapid fissile accelerator, and certain combinations of talents). Looking at that screenshot and the provided save, those could contribute to the performance problems your having (although they're not enough to alone cause them). In any case, we've got a fix for those coming up, possibly even in the next unstable.

Does this apply to my save as well? I have only 2 modifications, one of which is a submarine, and the second is Meaningful Upgrades.

**Comment by ajmcateer** [comment]
@Regalis11 While I am a programmer I have never developed a game. I am very curious, how could an item like a, steel bar tucked away in a cabinet cause such a performance hit?

The sub (The Iroh) does have a lot of components, so to me that makes sense.

**Comment by PiatraAlatyr** [comment]
I still don't understand how updating outposts could affect my fps during a mission. There have been changes in the behavior of bots, and this may be one of the reasons. There are also a lot of bots at the outposts and the FPS situation there is getting worse.

**Comment by Regalis11** [comment]
> I am very curious, how could an item like a, steel bar tucked away in a cabinet cause such a performance hit?

That's a good question, I was confused about that myself as well. It seems that it happens because many materials have an "AI target" that allows AIs to react to them. In the case of steel, it's there because some pets can eat it and need the AI target to find it. The AI targets normally have a negligible performance impact, but there's such an enormous amount of materials in that sub that it adds up to a measurable performance hit. I'm glad we noticed it - that's something we need to optimize as well!

> I still don't understand how updating outposts could affect my fps during a mission.

It does not, during missions the degraded performance is caused by other factors.

**Comment by Regalis11** [comment]
We've now got some more optimizations being tested internally, hopefully coming to unstable very soon

> - Status effects that target NearbyCharacters and run every frame can be pretty heavy, which causes issues when there's lots of items with that kind of effects around. Namely, volatile fuel rods caused noticeable performance problems if there were large amounts of them around. I added an "interval" property to status effects to allow only executing these effects periodically, and made volatile rods and diving suits use it.
> - Many talents apply afflictions that unlock some kinds of buffs/effects on characters. Most of these used the strength of the affliction as a sort of timer, constantly decreasing the strength of the affliction, which meant the talent needed to keep reapplying the affliction every frame to keep it active. While this wasn't usually that bad for performance, in a campaign with a dozen or so characters with a ton of talents (some of which apply effects to the whole crew), the compounded performance hit was sometimes pretty major. I added a "duration" property to the afflictions (the affliction is automatically removed after the duration passes) so the talents can now apply them periodically instead of every frame. Affects the following talents (these should all be tested):
>     - Skedaddle
>     - Crew Layabout
>     - Enrolling to Clown College (-> Skillful Melodies)
>     - Inspiring Tunes
>     - True Potential (-> Soothing Sounds)
>     - Evasive Maneuvers
>     - Down with the Ship
>     - Commander (-> Inspired to Act)
>     - Maintenance Routine (-> Well Drilled)
>     - Inspire to Battle (-> Battle Ready)
>     - Melodic Respite
>     - Electrochemist (-> Guarded)
> - HumanAIController.CalculateHullSafety enumerated through all items to find if there's dangerous items in a hull, which had a measurable performance hit when there's tons of items in the sub. Optimized by storing the dangerous items in a separate list.
> - Stop updating items more aggressively:
>     - Static AITargets don't force the item to stay active (many common materials, like steel, have these because pets can eat them).
>     - Don't check the item's impact queue if the item is inactive (impacts make them active).
>     - Having ItemComponents with sounds doesn't force an item to stay active. Just having sounds doesn't mean we need to update them - it's only necessary if the item has sounds that play always or if it's currently playing something. This could potentially cause some issues with sounds (looping sounds continuing to loop when they shouldn't, some sounds not playing).
>     - Having ItemComponents with StatusEffects doesn't force an item to stay active. Not necessary because the StatusEffects that are applied in Update would only run if the component is active, which keeps the item itself active. Other effects (OnUse, OnImpact, OnBroken, and such) don't need the item or the component to be active. This could potentially cause issues with status effects (some effects not executing).

**Comment by PiatraAlatyr** [comment]
It's hard to believe that all this causes such lags. We'll see when we play.

**Comment by Regalis11** [comment]
> It's hard to believe that all this causes such lags

I'm not saying they are the only cause of the performance problems, nor that those optimizations will solve them entirely. The bad performance seems to be a result of many small things going on at once, and improving those is a continuous process that will never be fully "done". However, I did notice a clear improvement in the performance in your save after doing those optimizations - there is still a lot of work to be done, but I hope they will make the game a bit more playable for you.

**Comment by PiatraAlatyr** [comment]
> However, I did notice a clear improvement in the performance in your save after doing those optimizations - there is still a lot of work to be done, but I hope they will make the game a bit more playable for you.

Thx. I will wait for these improvements to be released in the unstable version.

**Comment by idogadol** [comment]
Please comment when there's a fix in unstable

**Comment by Ek-Videogames** [comment]
> > I am very curious, how could an item like a, steel bar tucked away in a cabinet cause such a performance hit?
> 
> That's a good question, I was confused about that myself as well. It seems that it happens because many materials have an "AI target" that allows AIs to react to them. In the case of steel, it's there because some pets can eat it and need the AI target to find it. The AI targets normally have a negligible performance impact, but there's such an enormous amount of materials in that sub that it adds up to a measurable performance hit. I'm glad we noticed it - that's something we need to optimize as well! And it actually seems that there are tons and tons of steel bars outside cabinets too in that save - those need some extra physics-related calculations as well.
> 
> I'm glad we noticed it - that's something we need to optimize as well!
> 
> > I still don't understand how updating outposts could affect my fps during a mission.
> 
> It does not, during missions the degraded performance is caused by other factors.

True, now i'm curious what the cause of heavy updates are for the vanilla items, particularly some of the non-logic vanilla items that seem like they shouldn't have reason be constantly doing large item updates while idle. Whatever the cause is will help inform if it is possible to improve performance on the mod's end in these cases as well.

I will note that one performance problem I was already aware of - it seems the "InWater" effect is much more performance intensive on average than other 'constantly active' effects. For example - if having a high number of PUCS suits on-board (due to the increased complexity of the hull/water oxygen usage logic) can cause a noticeable performance impact.

As for lighting - It's kind of always been a bit of an performance issue even from early versions (playing on lowest resolution has been the default for most multiplayer servers) it may be wise at some future point to revisit the entire lighting rendering system at a fundamental level to see what optimizations can be done, possibly even using alternative proven shader methods.

**Comment by PiatraAlatyr** [comment]
@Regalis11 I tested the latest unstable build and there are definitely improvements. But still very far from what it should be. Since the FPS drop to 5 is not permanent now, I can say that these drops are more affected by the DrawMap parameter. At the beginning of the lags, for some reason, it jumps twice, like some other, but less significant things. For example, I swam out of the submarine and walked around a small outpost. The difference in fps in places is crushing.
![Снимок экрана (1833)](https://user-images.githubusercontent.com/36773134/171206489-214bc786-d097-4d83-b33f-05cbd2d3b338.png)
![Снимок экрана (1835)](https://user-images.githubusercontent.com/36773134/171206501-443838dd-2788-4332-bc31-59fac2dfff24.png)
![Снимок экрана (1843)](https://user-images.githubusercontent.com/36773134/171208324-4be63e7b-635d-4405-8bf4-cffefe124619.png)

**Comment by Rokvach** [comment]
I've been doing some tests using the [Сохранение 1.zip](https://github.com/Regalis11/Barotrauma/files/8553944/1.zip) save provided above, I isolated the submarine from that save and made a new submarine using it [subinside.zip](https://github.com/Regalis11/Barotrauma/files/8813120/subinside.zip) I did notice that the performance of the submarine itself isn't the cause of the fps issues at least not anymore with the most recent optimizations.

With just that submarine on the first level of the campaign my fps is at around 160, it was 40 when testing the save itself. 

Then I spawned the equal amount of bots as there were on the save onto the submarine and my fps dropped from ~160 to ~110

Then I teleported towards the end of the Aphotic Plateau biome and my fps jumps between 70-100, so not like it is on the save but still quite bad

I then made sure that all of my bots had orders and my fps is now between 60-90

To get it to 40 I might need to make sure that all of my bots has some items on their inventories and talents, this is just speculation.

**Comment by Rokvach** [comment]
Continuation on the above findings now with the latest optimizations that are coming to the next Unstable build. 

> Then I teleported towards the end of the Aphotic Plateau biome and my fps jumps between 70-100, so not like it is on the save but still quite bad

FPS is now at 150

> I then made sure that all of my bots had orders and my fps is now between 60-90

I gave all my bots orders, repair damaged items, clean items and reload ammo. FPS is around 148 and can briefly drop to 120 when all the bots activate when I drop items to the floor.

**Comment by Rokvach** [comment]
Testing the save [Сохранение 1.zip](https://github.com/Regalis11/Barotrauma/files/8553944/1.zip) again and my fps is now at 93 and can jump to 100, so double than it was prior to the latest optimizations

**Comment by idogadol** [comment]
FPS goes down for my crew and me from ~140 to 5 whenever something spawns, then jumps back to either ~140 or a low framerate which can be anywhere between 15 to 30 depending on what we face, until we're done facing it.
Thalami are framey until we nuke them, getting rid of all the amoeba inside, and making the framerate go back to normal.
Pirate vessels cause frame drops regardless of how many living AI remain inside them.
There are also many frame drops when facing a hammerhead matriarch/a swarm of hammerheads.

**Comment by PiatraAlatyr** [comment]
> Testing the save [Сохранение 1.zip](https://github.com/Regalis11/Barotrauma/files/8553944/1.zip) again and my fps is now at 93 and can jump to 100, so double than it was prior to the latest optimizations

Yes, performance has roughly doubled. Great job. But unfortunately 5-20 multiplied by 2 is 10-40. This brings the game to a playable level, but the lags that lower the fps to 5 and cause input lag are still present.

**Comment by Regalis11** [comment]
@PiatraAlatyr Rokvach was referring to some additional optimizations we did for the latest unstable (v0.18.5.0) which we just released a moment ago

> - Optimized bot AIs: in particular, the cleanup, repair, pump water and load items objectives. Should significantly improve performance when the bots are doing these objectives when there's a large number of items in the sub.
> - Optimized entity culling logic (determines which items/structures are currently visible in the screen).
> - Optimized a bunch of textures.

I'd be very interested in hearing how much those improved the performance at your end, so please let us know if/when you get around to testing the new unstable!

**Comment by PiatraAlatyr** [comment]
@Regalis11 It's already more impressive. Without active actions, that is, "in idle", the fps on this save is already 30-40. That is, it has become much more stable, sometimes lags still happen, but seemingly less frequently. The frame rate outside the submarine is no longer 90, but 130 frames. A more detailed performance debug also helps. It is clear that the problem is in Items, BackStructures and BackCharectersItems. These three parameters jump a lot when the "5 fps problem" happens. 
As noted earlier, after the lags go through, many NPCs start moving. They are probably scanning all available items within the submarine and routes to decide what to do. It seems to me that if you give each bot its own separate time when he decides what to do, then it will be possible to avoid a strong peak load. I believe that the same situation occurs when a large swarm of monsters appears on the map, and an FPS drawdown occurs.
So it's not just about the quality of the AI algorithms for the bots, but also the amount of AI itself, as they all calculate their actions at the same moment, causing a large queue of calculations. But these are just my guesses. I don't know how else I can help catch this performance issue with only the performance debug window. In general, performance has indeed improved significantly. I will play on the weekend, see how the game behaves in different game situations. Maybe something to add to my observations.
![Снимок экрана (1852)](https://user-images.githubusercontent.com/36773134/171881315-fbd840f6-f024-493e-bb8b-47a49602b731.png)
![Снимок экрана (1845)](https://user-images.githubusercontent.com/36773134/171881366-1758cbc1-3b80-49be-8bc2-046c2ffb2b11.png)
![Снимок экрана (1847)](https://user-images.githubusercontent.com/36773134/171881381-65fb673e-a51f-4d94-8611-b6a889fefd5a.png)

**Comment by PiatraAlatyr** [comment]
@Regalis11
I tested version 18.8. In general, the FPS did not rise, but the peaks of the lags were definitely less. I would even say that they almost disappeared. They still occur, but are very short when the swarm appears. Speaking of the appearance of the swarm. This is not the first time I go through my save and the events have always been the same, the swarm appeared far enough from the boat. But now he spawns closer. Sometimes even too close.
There is also a fairly large drawdown in frames when fighting pirates. The number of particles in the frame at this moment is almost at the limit. I use a mod that allows you to increase the visibility range of the periscope, perhaps because of this, sometimes I see much more than the game provides. But in close combat, when a pirate boat is above you or below you, the FPS drawdowns are similar.
In general, the problem areas are the same. Overall FPS around 30 is certainly better than 5, but it's still not good. If there is another content update, there is a risk that the FPS will again become completely unplayable.
I also noticed some bug, if at the moment of the lag I switch the character to the captain behind the sonar, then according to the parameters it looks like the previous view of the shooter is still being rendered, because the particle index does not drop, as well as low fps, but when I exit the sonar, everything returns back to normal.
![Снимок экрана (1863)](https://user-images.githubusercontent.com/36773134/173356976-29642818-e2be-44ed-8b22-632811d06af1.png)
![Снимок экрана (1864)](https://user-images.githubusercontent.com/36773134/173357491-ad346419-b917-4247-aad1-dbdd6bcd6bbd.png)
![Снимок экрана (1867)](https://user-images.githubusercontent.com/36773134/173358275-d6bc9b85-9f8c-4b77-9445-e3729530a8e8.png)
![Снимок экрана (1866)](https://user-images.githubusercontent.com/36773134/173358289-e0978c44-bd8f-4a92-8149-aa5700368719.png)

**Comment by PiatraAlatyr** [comment]
And one more thing, when loading this save, the game stops responding for a while. And one more thing, when loading this save, the game stops responding for a while. This didn't usually happen until the fateful 17.15 release.
![Снимок экрана (1860)](https://user-images.githubusercontent.com/36773134/173359233-add5b8ac-14f4-4bb6-a360-e4b7d9496d2f.png)

**Comment by Regalis11** [comment]
Thank you for the help again! We will be doing some more profiling and optimization to address these problems.

We decided to close this ticket now though: since this ticket is pretty much about general performance problems and not about a specific bug, it doesn't quite work with the way we handle tickets. Optimization is a continuous process, so it's kind of impossible to say that it's "done" at some point. But that doesn't mean we won't be continuing our work with improving the performance! Thanks to everyone who contributed to this ticket and helped us get the game running a little more smoothly for this update.

**Comment by Chotat0** [comment]
Issue is NOT fixed with the newest update. Took some new showperf screenshots since you added more data to it.
![20220617154104_1](https://user-images.githubusercontent.com/93625008/174392582-07eb10ea-14d6-41f1-9fd7-878bb49f79b5.jpg)
 
![20220617154134_1](https://user-images.githubusercontent.com/93625008/174392583-a402cd74-2b0a-41f7-89da-f02589365ce1.jpg)
![20220617154136_1](https://user-images.githubusercontent.com/93625008/174392585-63bb5b51-a288-40f4-bf62-898d293fa43b.jpg)
![20220617154150_1](https://user-images.githubusercontent.com/93625008/174392587-938b01fb-b05a-4e3e-baa1-8fa7a9d03c4b.jpg)
![20220617154159_1](https://user-images.githubusercontent.com/93625008/174392588-436878de-33da-4258-9286-008c1ebb7fde.jpg)
![20220617154202_1](https://user-images.githubusercontent.com/93625008/174392589-5ed4609e-415d-4c49-aa8c-950527f9d256.jpg)

**Comment by c01dc0ffee** [comment]
`GameScreen.Draw` calls `Submarine.CullEntities`, which iterates over all MapEntity instances and calls `entity.IsVisible(camView)`:

![image](https://user-images.githubusercontent.com/38895080/174464602-7674840e-218e-45b1-b85f-76cbc4663fce.png)

git blame says it was introduced 3 years ago. I imagine doing things like culling entities that aren't on screen would help improve performance somewhat.
