### ISSUE TITLE
Game crashes when trying to load a submarine which only consists of a hull and a spawnpoint

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9103]
**Description**
No crash report was generated but it threw an exception in VS

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/fb9519a4-03d7-4d94-8775-077e73d0a111)

**Steps To Reproduce**
Place a hull and a spawnpoint inside the hull in sub editor and launch sub editor test mode

**Version**
0.17.15.0
Branch: dev
Commit: 
https://github.com/Regalis11/Barotrauma-development/commit/7b6277c8c8b51643149b45ad4374bb5b68e1eeb7

**Comment by Regalis11** [comment]
Seems to have been caused by `feature/start-items`, moving to team 1

**Comment by Regalis11** [comment]
This was blocking my work on https://github.com/Regalis11/Barotrauma-development/issues/3327 so had to take a look at this. Should be fixed in https://github.com/Regalis11/Barotrauma-development/commit/c1f07cbd9d9b800f9b486998f76a6a75ba8e117f, alongside a couple of other issues I found:

> - Fixed crashing if the sub contains no cargo spawnpoint or waypoints.
> - Fixed crashing if the cargo spawnpoint is outside hulls.
> - Fixed items getting spawned on waypoints outside the sub if there's no cargo waypoint.

**Comment by Rokvach** [comment]
Still crashes if I just place a hull and add a spawnpoint inside it and press Test

![image.png](https://images.zenhubusercontent.com/5c924117534a9b0a86cdddce/a0b055d1-ed17-4440-b101-45f1f08c8a21)
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Barotrauma
  StackTrace:
   at Barotrauma.CargoManager.GetOrCreateCargoContainerFor(ItemPrefab item, ISpatialEntity cargoRoomOrSpawnPoint, List`1& availableContainers)
   at Barotrauma.AutoItemPlacer.SpawnStartItems(Submarine sub)
   at Barotrauma.AutoItemPlacer.SpawnItems()
   at Barotrauma.GameSession.InitializeLevel(Level level)
   at Barotrauma.GameSession.StartRound(LevelData levelData, Boolean mirrorLevel, SubmarineInfo startOutpost, SubmarineInfo endOutpost)
   at Barotrauma.SubEditorScreen.TestSubmarine(GUIButton button, Object obj)
   at Barotrauma.GUIButton.Update(Single deltaTime)
   at Barotrauma.GUI.Update(Single deltaTime)
   at Barotrauma.GameMain.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Microsoft.Xna.Framework.Game.Run()
   at Barotrauma.Program.Main(String[] args)
```

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
