### ISSUE TITLE
[Wallet] Money request always goes through if nobody votes on it

### ISSUE THREAD

**Issue by Rokvach** [Regalis11/Barotrauma#9139]
**Description**
Requesting money always goes through if nobody votes on it, the client who requested the money is counted as a vote

**Steps To Reproduce**
Have a client request money and nobody else on the server votes on it

**Version**
Unstable 0.18.1.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4c7c2d81a19841fb162046ab3060970b64edca9c

**Comment by Rokvach** [comment]
This issue was still present on the latest Unstable build 0.18.2.0. I had 3 players on the server, 1 player started a money request and 2 players including myself didn't vote on it. The requester was counted as a vote so the vote passed and the money fast transferred.

**Comment by Regalis11** [comment]
Hopefully fixed now https://github.com/Regalis11/Barotrauma-development/commit/ea280c8d8916507aecd474b205c925be33c31366

> The client who initiated a vote cannot take part in that vote (except if they're the only client who can vote, in which case the vote automatically passes).

**Comment by Rokvach** [comment]
Tested, working correctly. Closing.
