### ISSUE TITLE
Ballast flora won't die when submerged even if it's healthbar seems to go to 0

### ISSUE THREAD

**Issue by Regalis11** [Regalis11/Barotrauma#9316]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When the ballast flora is submerged, it won't die even if do enough damage to it to zero the healthbar. Happens because we clamp the damage to the flora's remaining health, and then halve the damage if it's submerged (meaning the health won't go to exactly to zero even if the damage should've been enough to kill it).

### Reproduction steps

1. `ballastflora infect`
2. `ballastflora growthwarp 100`
3. Damage the root with e.g. plasma cutter until the health bar is empty

### Bug prevalence

Happens regularly

### Version

0.17.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/3becf259115869de427b517a6e307b646036a676

**Comment by Rokvach** [comment]
I got these errors while testing this

1. Load up singleplayer
2. Use ballastflora infect
3. Use godmode and find a welder onboard the sub
4. Kill ballast flora with the welder
5. Once the root dies undock from the outpost
6. Error should show up when the next level loads in

![image](https://user-images.githubusercontent.com/7299826/173244132-964dd89b-bc7c-43c9-8a00-f58f1065feb5.png)

**Comment by Rokvach** [comment]
The above error doesn't seem to happen all the time, we didn't encounter it during community testing while we got ballast flora

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/a9c08e782438a03d1e0707847cf6521629f5dd6b

**Comment by NilanthAnimosus** [comment]
Tested further, the health bar disappears (Is removed from the clients side) once all branches have died and despawned related to the ballast flora. issue is likely syncing of ballast flora health related / not sent to client in order for client to hide it properly.

**Comment by Regalis11** [comment]
Should be fixed now https://github.com/Regalis11/Barotrauma-development/commit/b0515bdc5a5f274cd806f287c6e21f31d994b82f

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/36e3a2755f5fc201a748a32b63cc93a8eb30d90a, Health bar no longer shows but you do still get damage particles hitting the empty air over the pump with a welder until the branches have fully disappeared.

I think that's a tiny issue nobody will notice (As without the health bar its still far more obvious you have killed it now). I think this can be closed unless the visual issue wants to be resolved.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/cc4d98a926e9774fbfc14bfc354719b57c34408f

**Comment by NilanthAnimosus** [comment]
Tested against bugfixes commit https://github.com/Regalis11/Barotrauma-development/commit/6efb667a91d39ee7715a094a89a32ed20b73d6ec, needs further looking into.

the damage particles are still there, it appears perhaps they are coming from a branch that is not a "Root" despite its in the centre of the ballast and invisible, not sure whats going on there.

**Comment by Regalis11** [comment]
Couldn't find a way to reproduce this. Are you sure there wasn't a branch behind the pump?

**Comment by NilanthAnimosus** [comment]
My second test shows it does work fine (and not have damage particles), which implies my last test indeed had a none-root branch directly in the same place as the center of the pump somehow. I did end up ending that test early when I encountered some desync issues.

I did breakpoint it on the first test and I saw it wasn't a root I was hitting but there was no visible branch at the pump (Could it go behind the pump?). when I said appears I was considering the possibility the client somehow did not have the root classed as a root and did not know the full mechanics but given it does hide the damage particles correctly in the second test without changing the code I tested against I'm inclined to believe this was just a branch behind the pump and not the root.

Closing this as it doesn't seem to be an issue anymore.
