### ISSUE TITLE
Hatch - disappeared animation of leaking water

### ISSUE THREAD

**Issue by MaaiG** [Regalis11/Barotrauma#9333]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

No animation of the water flowing through the lower hatch:
https://user-images.githubusercontent.com/93348499/173435488-21dd5c01-d350-44f7-9440-262706134283.mp4
In some previous versions this animation was at the hatch as you can see in the video from v0.15.13.0: https://github.com/Regalis11/Barotrauma/issues/7496

P.S. Related issue: https://github.com/Regalis11/Barotrauma/issues/7496

### Reproduction steps

1. Start editor
2. Water flooding
3. Open any `hatch` between the hulls (not external hull)
4. Disappeared animation of leaking water!
_5. By the way, for a hole as big as a hatch, the rate of flooding of the lower hull is too slow (IMHO)._

### Bug prevalence

Happens every time I play

### Version

0.17.16.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I built a minimal test sub to diagnose this, but couldn't find any problems:
![gaps](https://user-images.githubusercontent.com/14351070/173509545-fe9cf65e-57db-4641-ad48-9c6f5ab5420d.png)

So I suspect this requires some more specific circumstances to occur, maybe hulls of a specific size or some specific layout. Would it be possible to post that sub you're testing in the video here so I could give that one a try?

Thanks and sorry for the trouble!

**Comment by MaaiG** [comment]
> that sub you're testing in the video here so I could give that one a try?

Dear Regalis! No problem - my mini test bench: [__Test-Water.zip](https://github.com/Regalis11/Barotrauma/files/8897632/__Test-Water.zip)
_PS  Thank you for your constant technical support._

**Comment by Regalis11** [comment]
Thanks! I still couldn't repro it even with this sub, but then I realized the problem was that I was testing in the latest unstable version - it seems this problem only occurs in the public build. So, should be fixed for the upcoming update.

**Comment by Rokvach** [comment]
Closing as no issues

**Comment by MaaiG** [comment]
v0.18.11.0
I thought you’d fix both problems but the valve animation still doesn’t work.
