### ISSUE TITLE
Multiple selection motiondetectors will cause the game crash

### ISSUE THREAD

**Issue by Raven-233486** [Regalis11/Barotrauma#9401]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

![QQ图片20220618175503](https://user-images.githubusercontent.com/72175577/174432637-0a9735e6-97e0-4577-80c1-33298e25d4dc.png)

### Reproduction steps

1.multiple choosing two or more motiondetectors 
2.change their target setting
3.then the game crash

### Bug prevalence

Happens every time I play

### Version

0.18.12.0

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
I did get a console error when deselecting everything though (but not a crash), fixed that in https://github.com/Regalis11/Barotrauma-development/commit/ba58012a611829fd2c9319254a311efbfd101b0f

**Comment by Regalis11** [comment]
Got another report about this with a crash report included: https://github.com/Regalis11/Barotrauma/issues/9426

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/62f84506446b74e7b4d8234583f00e953d86ca38

Note for testing: this only seems to happen when editing multiple sensors at the same time

**Comment by NilanthAnimosus** [comment]
Tested, working correctly. Closing

**Comment by DominicBeaudoin** [comment]
I am still having this issue in v0.18.12.0 (ReleaseWindows, branch release, revision 85532fbbc).

I can get the crash to occur 100% by following these steps:
- Open the submarine editor
- Add 2 or more motion detectors
- Select 2 or more of them
- Add or remove any of the targets (monster, human, wall, although I haven't tested with "wall") by clicking on a checkmark
