### ISSUE TITLE
No lighting in ResearchModule_02_Colony

### ISSUE THREAD

**Issue by ubertpendragon** [Regalis11/Barotrauma#9593]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

Lamps not wired
![image](https://user-images.githubusercontent.com/73229309/179509430-8c200ba6-fea5-4b04-83e9-dac2d2fec920.png)
![image](https://user-images.githubusercontent.com/73229309/179510120-222bb1fc-fe8c-4509-83e9-09d9ac30229c.png)

Module very dark
![image](https://user-images.githubusercontent.com/73229309/179509497-a02250b5-90bf-4a90-94a4-c3102a14856e.png)

Side issue:
Decorative Navigation terminals are interactable
![image](https://user-images.githubusercontent.com/73229309/179509747-c36b41a6-5309-483d-a0b6-1a8cb8513a49.png)

### Version

0.18.15.0

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/dd09ff479c6a5ceb741cc7dd9d7e0b9b38714cf3. Pushed to dev to avoid conflicts.

**Comment by NilanthAnimosus** [comment]
Tested on 0.19.0.0 - Two lights are still not connected to power (One near the leftmost door on the lower level, one in the top centre)

![image](https://user-images.githubusercontent.com/29177976/180105233-a491366d-cd55-4efa-b696-d4c1e176527e.png)

![image](https://user-images.githubusercontent.com/29177976/180105262-cea602ef-de82-4769-8aef-c01b2e35762c.png)

Though not as terribly dark, they do have a lack of a wire (Intentional or?)

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/4f00163c303e03a12703b16569a2ce594838b02e

**Comment by NilanthAnimosus** [comment]
Tested against release commit https://github.com/Regalis11/Barotrauma-development/commit/3391dc7033d5d12b9167b38a6269ffd1096e546d. works correctly, closing.

Notes: 2 of the lights are not wired, however they have been specified as default on and no power consumption so this is fine now, though the top middle on is a little dim it is a functional light.
