### ISSUE TITLE
Bots can't repair a wall near Typhon's stowage compartment

### ISSUE THREAD

**Issue by gameman7** [Regalis11/Barotrauma#9684]
### Disclaimers

- [ ] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

If there's damage in the room "Stowage compartment" (By the whey it's the curve in the room) the AI can't fix it, they just try to run in place. if you try to fix it you just need to crouch. ![Barotrauma Screenshot 2022 08 06 - 22 25 36 14](https://user-images.githubusercontent.com/110705929/183276756-3b9441cf-fe30-4ce0-aec7-61e9b3ed65d2.png)
Where my mouse is at, is where the AI can't fix the damage.
(Sorry if this don't help :p)

### Reproduction steps

1. wait for damage in that room it needs to be in a certain spot.
2. Tell your AI to fix it.
3. and if they don't crouch (I don't know if they do crouch) they just should
 try to fix it but just fail and walk in place

### Bug prevalence

Just once

### Version

0.18.15.0

### Which operating system did you encounter this bug on?

Windows

**Comment by gameman7** [comment]
Note: it happened again and now i got a screenshot
![Barotrauma Screenshot 2022 08 07 - 13 45 39 20](https://user-images.githubusercontent.com/110705929/183310455-6ca6a30c-8f2d-4e69-ba19-d1a111472d35.png)
![Barotrauma Screenshot 2022 08 07 - 13 46 01 74](https://user-images.githubusercontent.com/110705929/183310466-477b98bf-7a57-4949-bc47-7c7bf58d069e.png)

**Comment by Regalis11** [comment]
Addressed in https://github.com/Regalis11/Barotrauma-development/commit/553dc482307ed1776adba4f56ec07c1972f258af

**Comment by Rokvach** [comment]
Looks like this is partially fixed, the bots are able to fix the wall enough that there's no more water flooding in but they don't seem to be able to reach and fix the wall itself

The wall is considered fixed even though its 97% damaged only because there is no water leaking into the sub

![image](https://user-images.githubusercontent.com/7299826/189622717-bfcc91b9-5182-4709-8aff-adc156cb8fea.png)
![image](https://user-images.githubusercontent.com/7299826/189622824-372aa6ea-a7a8-40fb-9f54-24c55890a373.png)

**Comment by Regalis11** [comment]
Hopefully fixed in https://github.com/Regalis11/Barotrauma-development/commit/5da5cc44d9ea552da144b7cff41cab3eba66276c

**Comment by Rokvach** [comment]
Tested, bots are able to fix that part of the wall just fine now. Working correctly, closing.
