### ISSUE TITLE
reloadwearables crashes game in submarine edior

### ISSUE THREAD

**Issue by shangjiaxuan** [Regalis11/Barotrauma#9775]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [X] My issue happened while using mods.

### What happened?

reloadwearables crashes game in submarine edior run.

Seems like the game still updates sprites while the sprites are reloading, resulting in threading issue with invalid state.

### Reproduction steps

1. Use submarine editor
2. Enter test mode
3. Console command `reloadwearables`

### Bug prevalence

Happens every now and then

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

### Relevant error messages and crash reports

```shell
Barotrauma Client crash report (generated on 8/27/2022 11:38:10 AM)


Barotrauma seems to have crashed. Sorry for the inconvenience! 


D58898302FF8D35C7702373E3C15BA38


Game version 0.18.15.0 (ReleaseWindows, branch workshop-update-fix, revision d547319732)
Graphics mode: 1920x1080 (BorderlessWindowed)
VSync ON
Language: English
Selected content packages: Vanilla, [VH] The Iroh, Nemesis, Fubuki-PRO, Fubuki, Apo-5 "Chainsaw", Apo-4A "Saber", Apo-3A "Dagger", 万年风雪-EX, 万年风雪, [BOS]Van-新典范, I401-Iona萝莉伊欧娜, Houshou Marine songs, anime sound【cloud】+Weapon sound, Gawr Gura A sonar, Posters, Anime Poster Pack, Performance Fix, Analyze Item, CatGene, 抱卵（英文非空）, GeneFarm基因农场, Genes+Revived, Indigo project, Waifu in the Deep v0.5a, Lootbelt, Calic's Resource Storage Containers, Better Vanilla Turret Ammo, 32x Stack, All The Talent Trees, Unlock All Talents, CsForBarotrauma, Lua For Barotrauma
Level seed: no level loaded
Loaded submarine: 万年风雪 (A2705F73BA20EAACC0A5920992DF7420)
Selected screen: Barotrauma.GameScreen
SteamManager initialized


System info:
    Operating system: Microsoft Windows NT 10.0.19044.0 64 bit
    GPU name: NVIDIA GeForce GTX 1650
    Display mode: {Width:1920 Height:1080 Format:Color AspectRatio:1.7777778}
    GPU status: Normal


Exception: Texture is disposed (System.InvalidOperationException)
Target site: Void CheckValid(Microsoft.Xna.Framework.Graphics.Texture2D)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.CheckValid(Texture2D texture) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 249
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 472
   at Barotrauma.Sprite.Draw(ISpriteBatch spriteBatch, Vector2 pos, Color color, Vector2 origin, Single rotate, Vector2 scale, SpriteEffects spriteEffect, Nullable`1 depth)
   at Barotrauma.PhysicsBody.Draw(SpriteBatch spriteBatch, Sprite sprite, Color color, Nullable`1 depth, Single scale, Boolean mirrorX, Boolean mirrorY)
   at Barotrauma.Limb.Draw(SpriteBatch spriteBatch, Camera cam, Nullable`1 overrideColor, Boolean disableDeformations)
   at Barotrauma.Lights.LightManager.RenderLightMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Camera cam, RenderTarget2D backgroundObstructor)
   at Barotrauma.GameScreen.DrawMap(GraphicsDevice graphics, SpriteBatch spriteBatch, Double deltaTime)
   at Barotrauma.GameScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch)
   at Barotrauma.GameMain.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 669
   at Microsoft.Xna.Framework.Game.Tick() in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 511
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 94
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 398
   at Microsoft.Xna.Framework.Game.Run() in G:\Repositories\Barotrauma\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 368
   at Barotrauma.Program.Main(String[] args)


Last debug messages:
[8/27/2022 11:38:10 AM] reloadwearables
[8/27/2022 11:38:05 AM] Failed to initialize Steamworks network relay: Failed, Failed, Failed, No response from server
[8/27/2022 11:37:37 AM] WARNING: Could not compress a texture because the dimensions aren't a multiple of 4 (path: LocalMods/2655395672/Content/items/Weapons/Overrided.png, size: 373x470)
[8/27/2022 11:37:24 AM] Analyze Item: Executing init.lua
[8/27/2022 11:37:24 AM] Performance Fix: Executing init.lua
[8/27/2022 11:37:24 AM] Performance Fix: Executing init.lua
[8/27/2022 11:37:23 AM] Using LuaSetup.lua from the content package.
[8/27/2022 11:37:23 AM] Force load package: Analyze Item
[8/27/2022 11:37:20 AM] Forced run C# of Analyze Item
[8/27/2022 11:37:20 AM] Forced run C# of Analyze Item
[8/27/2022 11:37:20 AM] Cs! Version d547319732
[8/27/2022 11:37:20 AM] Lua! Version d547319732
[8/27/2022 11:37:09 AM] WARNING: The following errors occurred while loading the content package "Fubuki-PRO". The package might not work correctly.
Failed to load file "C:/Users/shang/AppData/Local/Daedalic Entertainment GmbH/Barotrauma/WorkshopMods/Installed/2488592579/desktop.ini" of type "None": file not found.
[8/27/2022 11:36:37 AM] Hash calculation for content package "CatGene (no humanhusk.xml)" didn't match expected hash (F70976F798ED8A5D1661FFABC7E92719 != E75F3D90ABC13BFFE0A6B7406AF2A8C7)
[8/27/2022 11:36:35 AM] Attempting to open ALC device "OpenAL Soft on Realtek HD Audio 2nd output (Realtek(R) Audio)"
[8/27/2022 11:36:33 AM] Logged in as shangjiaxuan (SteamID STEAM_1:1:245008170)
```

**Comment by NilanthAnimosus** [comment]
Thank you for the report!

it seems the game is still drawing sprites that it has disposed of and unloaded before having loaded new textures for them. wouldn't call this a threading issue as much as we shouldn't even be attempting to draw these while this command is active (or its not intended for usage in game).

This command will actually cause a crash regardless of it being in multiplayer game, a single player campaign or the sub editor test screen (which I think is also just the same as playing in game), it is probably intended to reload such from the main menu.

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/fbbd2265125a19694a23a50bc9db7e46ced2864a

**Comment by Rokvach** [comment]
I was only able to reproduce this once from 5 times testing

Only the use of the command has been restricted but the game still crashes sometimes if you switch from character editor to singleplayer after using the command

```
Exception: Texture is disposed (System.InvalidOperationException)
Target site: Void CheckValid(Microsoft.Xna.Framework.Graphics.Texture2D)
Stack trace: 
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.CheckValid(Texture2D texture) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 245
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Nullable`1 sourceRectangle, Color color, Single rotation, Vector2 origin, Vector2 scale, SpriteEffects effects, Single layerDepth) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Graphics\SpriteBatch.cs:line 387
   at Barotrauma.Sprite.Draw(ISpriteBatch spriteBatch, Vector2 pos, Color color, Vector2 origin, Single rotate, Vector2 scale, SpriteEffects spriteEffect, Nullable`1 depth) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Sprite\Sprite.cs:line 218
   at Barotrauma.CharacterInfo.DrawIcon(SpriteBatch spriteBatch, Vector2 screenPos, Vector2 targetAreaSize) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterInfo.cs:line 445
   at Barotrauma.CharacterInfo.<CreateIcon>b__36_0(SpriteBatch sb, GUICustomComponent component) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Characters\CharacterInfo.cs:line 565
   at Barotrauma.GUICustomComponent.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUICustomComponent.cs:line 35
   at Barotrauma.GUIComponent.DrawManually(SpriteBatch spriteBatch, Boolean alsoChildren, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 575
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 587
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 587
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 587
   at Barotrauma.GUIComponent.DrawChildren(SpriteBatch spriteBatch, Boolean recursive) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIComponent.cs:line 587
   at Barotrauma.GUIListBox.Draw(SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUIListBox.cs:line 1294
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Barotrauma.GUI.Draw(Camera cam, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GUI\GUI.cs:line 251
   at Barotrauma.MainMenuScreen.Draw(Double deltaTime, GraphicsDevice graphics, SpriteBatch spriteBatch) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Screens\MainMenuScreen.cs:line 962
   at Barotrauma.GameMain.Draw(GameTime gameTime) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\GameMain.cs:line 957
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 666
   at Microsoft.Xna.Framework.Game.Tick() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 508
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop() in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\SDL\SDLGamePlatform.cs:line 92
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in <DEV>\Libraries\MonoGame.Framework\Src\MonoGame.Framework\Game.cs:line 397
   at Barotrauma.Program.Main(String[] args) in <DEV>\Barotrauma\BarotraumaClient\ClientSource\Program.cs:line 58
```

**Comment by Regalis11** [comment]
I noticed that there was actually bigger underlying issue in the ReloadTexture command, which caused both this and https://github.com/Regalis11/Barotrauma/issues/9815. Fixed properly in https://github.com/Regalis11/Barotrauma-development/commit/8a032439540555d6d1c31b0597077dbab947e4f2 and reallowed using the command anywhere.

> Fixed ReloadTexture method causing "texture is disposed" exceptions in some situations. Seems to have happened as a result of https://github.com/Regalis11/Barotrauma-development/commit/63bb08faa949256a6bd2a006a98fc237d92a6147 and https://github.com/Regalis11/Barotrauma-development/commit/a6a653dfdc495c19b29003ae97f04f1c07903df9. Other sprites might've shared the same texture, which caused the previous exception if they weren't refreshed. A reference to the disposed texture was also kept in textureRefCounts, causing the same exception if another sprite tries to use it later.

**Comment by Rokvach** [comment]
Tested I wasn't able to cause a crash no matter what I did, working correctly. Closing.
