### ISSUE TITLE
PUCS with welding fuel slowly consumes medical items + does not kill by oxygen inside a hull with oxygen

### ISSUE THREAD

**Issue by Vykn** [Regalis11/Barotrauma#9811]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

When placing welding fuel inside a PUCS and wearing it, if there is an item inside the auto-injector slot, its condition will go down at the same rate as the fuel.

Additionally, the oxygenlow gain when wearing PUCS with welding fuel inside a hull with oxygen is too low to increase over time, as the character will decrease oxygenlow by breathing faster than the welding fuel increases it, and so a character will be completely fine while breathing welding fuel, if in a room with oxygen.

This also happens with incendium tanks.

I believe the issue is that the StatusEffect for the welding fuels in the PUCS item xml does not have a targetslot="0" in them, like the oxygen tanks. (line 673 & 677 of engineer_talent_items.xml)
![Screenshot (314)](https://user-images.githubusercontent.com/37850646/188102405-61871337-7d42-47b6-9919-8cba26c65fbd.png)

### Reproduction steps

1. Be in a hull with oxygen "quickstart dugong"
2. Spawn a PUCS, morphine, and welding fuel "spawnitem pucs inventory" "spawnitem morphine inventory" "spawnitem weldingfueltank inventory"
3. Place the morphine and welding fuel inside the PUCS
4. Observe as the morphine's condition goes down, and also that the character's oxygenlow decreases faster than the welding fuel increases it.

### Bug prevalence

Happens every time I play

### Version

0.18.15.1 / 0.18.15.2 on macOS

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/9593b98331ff47c73866d454735469e9fb0d5bfc

**Comment by Rokvach** [comment]
> Additionally, the oxygenlow gain when wearing PUCS with welding fuel inside a hull with oxygen is too low to increase over time, as the character will decrease oxygenlow by breathing faster than the welding fuel increases it, and so a character will be completely fine while breathing welding fuel, if in a room with oxygen.

This still happens but I'm unsure if this is the intended behavior

**Comment by Rokvach** [comment]
Tested, the welding fuel does get slowly consumed while in a oxygenated room, but that is most likely intentional. The issue of medical items getting consumed has been fixed, no issues. Closing.
