### ISSUE TITLE
[Unstable] Mechanic tutorial soft lock

### ISSUE THREAD

**Issue by evilfactory** [Regalis11/Barotrauma#9925]
### Disclaimers

- [X] I have searched the issue tracker to check if the issue has already been reported.
- [ ] My issue happened while using mods.

### What happened?

https://user-images.githubusercontent.com/36804725/192008037-677ccdd7-ad06-4f36-a27a-33a7f37f13bd.mp4

Not sure how to reproduce, but it may have caused by me taking the iron ore too fast

### Bug prevalence

Happens every now and then

### Version

0.19.6.0 (unstable)

### Which operating system did you encounter this bug on?

Windows

**Comment by Regalis11** [comment]
Fixed in https://github.com/Regalis11/Barotrauma-development/commit/044b46aa6815e59a2ca30dea4b2365fe266fad75

**Comment by Rokvach** [comment]
Tested, no issues. Closing.

**Comment by Rokvach** [comment]
Nvm I ran into this while speedrunning through the tutorial

Can still happen with both deconstructing and fabricating by just spam clicking the output slot as soon as you start the deconstruction/fabrication, was still able to complete the tutorial however by just fabricating a second wrench.

**Comment by Rokvach** [comment]
Tested, no issues. closing.
